import { db, verbsTable } from "@workspace/db";

// Image URLs
const IMG = {
  speak:    "https://www.tripsavvy.com/thmb/DVttYFkCp1z2QyOTNE4vmoauL4A=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/GettyImages-683747793-b05182cacdd94fd793240cd4d6b4f9de.jpg",
  work:     "https://media.gettyimages.com/id/2198968434/photo/students-using-laptop-and-smartphone-in-malmo-sweden.jpg?s=612x612&w=0&k=20&c=CabGwvl3Hs5Mx7_rk0o7weZFg5t4KeAIzeUBNWIUED8=",
  food:     "https://media.gettyimages.com/id/2215023550/photo/traditional-swedish-meatballs-with-mashed-potatoes-pickles-and-cranberry-sauce.jpg?s=612x612&w=0&k=20&c=ZrzruuV67aiz_Eb-Howv1tBi1jw3yp-IvVGYl1MNzn0=",
  walk:     "https://i0.wp.com/atravelingfairy.com/wp-content/uploads/2022/11/DSC04547.jpg?w=1100&ssl=1",
  nature:   "https://images.pexels.com/photos/33077333/pexels-photo-33077333/free-photo-of-serene-swedish-forest-view-with-reflective-lake.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
  family:   "https://media.gettyimages.com/id/1300189216/photo/happy-family-eating-breakfast-seen-through-doorway-of-kitchen-at-home.jpg?s=612x612&w=0&k=20&c=tpaZ_wI_lBB7q4LN-GkHcQhkVleWUSO4qfb8_IxLeyE=",
  health:   "https://media.gettyimages.com/id/731741979/photo/doctor-walking-through-hospital-corridor.jpg?s=612x612&w=0&k=20&c=94a50kc59V322iYjCtqtAM2f6GmIW7T_hiDezvf5TsE=",
  school:   "https://media.gettyimages.com/id/1667940273/photo/portrait-of-smiling-female-student-with-friend-in-university.jpg?s=612x612&w=0&k=20&c=ePwPB-IfQ5SEUEQQMiN6LVIDDK6wTsAjHVH0b9Yy_5A=",
  city:     "https://thumbs.dreamstime.com/b/bright-interior-swedish-supermarket-food-products-discount-signs-shopping-carts-aisle-390370221.jpg",
  sleep:    "https://media.gettyimages.com/id/1278673078/photo/empty-table-and-chair-against-window-at-new-workplace.jpg?s=612x612&w=0&k=20&c=ktE2JWrBuWhe6vmk18E1QsnswMPllZ0s3v96a5ivPlo=",
};

const verbs = [
  // ══════════════════════════════════════════════════════════════════
  // GRUPP 1 — -ar verbs (talat, -ade, -at)
  // ══════════════════════════════════════════════════════════════════
  {
    infinitiv: "tala",
    presens: "talar",
    preteritum: "talade",
    supinum: "talat",
    imperativ: "tala",
    futurum: "ska tala",
    presensParticip: "talande",
    perfektParticip: "talad",
    passivPresens: "talas",
    passivPreteritum: "talades",
    translation: "يتكلم / يتحدث",
    phonetic: "/ˈtɑːla/",
    group: "1",
    level: "A1",
    category: "kommunikation",
    imageUrl: IMG.speak,
    notes: "الفعل الأكثر شيوعاً للتحدث. مجموعة 1: ينتهي الماضي بـ -ade والمصدر المضارع بـ -at.",
    examples: [
      { sv: "Jag talar svenska.", ar: "أنا أتحدث السويدية." },
      { sv: "De talade om vädret.", ar: "تحدثوا عن الطقس." },
      { sv: "Tala långsammare, tack!", ar: "تحدث بشكل أبطأ، من فضلك!" },
    ],
    quizSentences: [
      { form: "presens", sentence: "Jag ___ svenska varje dag.", answer: "talar", translation: "أنا أتحدث السويدية كل يوم." },
      { form: "preteritum", sentence: "Vi ___ med läraren igår.", answer: "talade", translation: "تحدثنا مع المعلم أمس." },
      { form: "imperativ", sentence: "___ lite tystare!", answer: "Tala", translation: "تحدث بصوت أهدأ!" },
    ],
  },
  {
    infinitiv: "arbeta",
    presens: "arbetar",
    preteritum: "arbetade",
    supinum: "arbetat",
    imperativ: "arbeta",
    futurum: "ska arbeta",
    presensParticip: "arbetande",
    perfektParticip: "arbetad",
    passivPresens: "arbetas",
    passivPreteritum: "arbetades",
    translation: "يعمل",
    phonetic: "/arˈbeːta/",
    group: "1",
    level: "A1",
    category: "arbete",
    imageUrl: IMG.work,
    notes: "فعل مجموعة 1 شائع جداً في السياق المهني.",
    examples: [
      { sv: "Jag arbetar på ett kontor.", ar: "أعمل في مكتب." },
      { sv: "Hon arbetade hela natten.", ar: "عملت طوال الليل." },
      { sv: "Vi kommer att arbeta tillsammans.", ar: "سنعمل معاً." },
    ],
    quizSentences: [
      { form: "presens", sentence: "Han ___ som lärare.", answer: "arbetar", translation: "هو يعمل كمعلم." },
      { form: "preteritum", sentence: "Vi ___ sent igår.", answer: "arbetade", translation: "عملنا متأخراً أمس." },
      { form: "futurum", sentence: "Jag ___ i Stockholm nästa år.", answer: "ska arbeta", translation: "سأعمل في ستوكهولم السنة القادمة." },
    ],
  },
  {
    infinitiv: "lyssna",
    presens: "lyssnar",
    preteritum: "lyssnade",
    supinum: "lyssnat",
    imperativ: "lyssna",
    futurum: "ska lyssna",
    presensParticip: "lyssnande",
    perfektParticip: "lyssnad",
    passivPresens: "lyssnas",
    passivPreteritum: "lyssnaddes",
    translation: "يستمع",
    phonetic: "/ˈlʏsːna/",
    group: "1",
    level: "A1",
    category: "kommunikation",
    imageUrl: IMG.speak,
    notes: "يُستخدم مع حرف الجر 'på' للدلالة على الاستماع لشيء ما.",
    examples: [
      { sv: "Lyssna på mig!", ar: "استمع إليّ!" },
      { sv: "Jag lyssnar på musik.", ar: "أنا أستمع إلى الموسيقى." },
      { sv: "Hon lyssnade noga.", ar: "استمعت بانتباه." },
    ],
    quizSentences: [
      { form: "presens", sentence: "Jag ___ på svenska poddar.", answer: "lyssnar", translation: "أستمع إلى بودكاست سويدي." },
      { form: "imperativ", sentence: "___ på läraren!", answer: "Lyssna", translation: "استمع للمعلم!" },
      { form: "preteritum", sentence: "De ___ på musik igår.", answer: "lyssnade", translation: "استمعوا إلى الموسيقى أمس." },
    ],
  },
  {
    infinitiv: "köpa",
    presens: "köper",
    preteritum: "köpte",
    supinum: "köpt",
    imperativ: "köp",
    futurum: "ska köpa",
    presensParticip: "köpande",
    perfektParticip: "köpt",
    passivPresens: "köps",
    passivPreteritum: "köptes",
    translation: "يشتري",
    phonetic: "/ˈɕøːpa/",
    group: "2b",
    level: "A1",
    category: "handel",
    imageUrl: IMG.city,
    notes: "مجموعة 2b. الأمر: köp (بدون -a).",
    examples: [
      { sv: "Jag köper mat i affären.", ar: "أشتري الطعام من المتجر." },
      { sv: "Hon köpte en ny bok.", ar: "اشترت كتاباً جديداً." },
      { sv: "Köp mjölk på vägen hem!", ar: "اشتر حليباً في الطريق إلى المنزل!" },
    ],
    quizSentences: [
      { form: "presens", sentence: "Han ___ en ny jacka idag.", answer: "köper", translation: "هو يشتري جاكيت جديداً اليوم." },
      { form: "preteritum", sentence: "Vi ___ mat igår.", answer: "köpte", translation: "اشترينا طعاماً أمس." },
      { form: "imperativ", sentence: "___ inte för mycket!", answer: "Köp", translation: "لا تشتر كثيراً!" },
    ],
  },
  {
    infinitiv: "stänga",
    presens: "stänger",
    preteritum: "stängde",
    supinum: "stängt",
    imperativ: "stäng",
    futurum: "ska stänga",
    presensParticip: "stängande",
    perfektParticip: "stängd",
    passivPresens: "stängs",
    passivPreteritum: "stängdes",
    translation: "يُغلق",
    phonetic: "/ˈstɛŋːa/",
    group: "2a",
    level: "A2",
    category: "rörelse",
    imageUrl: IMG.city,
    notes: "مجموعة 2a. ضد: öppna (يفتح).",
    examples: [
      { sv: "Stäng dörren!", ar: "أغلق الباب!" },
      { sv: "Affären stänger klockan åtta.", ar: "المحل يغلق الساعة الثامنة." },
      { sv: "Han stängde fönstret.", ar: "أغلق النافذة." },
    ],
    quizSentences: [
      { form: "presens", sentence: "Biblioteket ___ tidigt på lördagar.", answer: "stänger", translation: "المكتبة تغلق مبكراً أيام السبت." },
      { form: "imperativ", sentence: "___ dörren, det är kallt!", answer: "Stäng", translation: "أغلق الباب، إنه بارد!" },
      { form: "preteritum", sentence: "Hon ___ datorn och gick hem.", answer: "stängde", translation: "أغلقت الحاسوب وذهبت إلى المنزل." },
    ],
  },
  {
    infinitiv: "titta",
    presens: "tittar",
    preteritum: "tittade",
    supinum: "tittat",
    imperativ: "titta",
    futurum: "ska titta",
    presensParticip: "tittande",
    perfektParticip: "tittad",
    passivPresens: "tittas",
    passivPreteritum: "tittades",
    translation: "ينظر / يشاهد",
    phonetic: "/ˈtɪtːa/",
    group: "1",
    level: "A1",
    category: "sinnen",
    imageUrl: IMG.school,
    notes: "يُستخدم مع 'på' للنظر إلى شيء: titta på TV (يشاهد التلفاز).",
    examples: [
      { sv: "Titta på mig!", ar: "انظر إليّ!" },
      { sv: "Vi tittar på film.", ar: "نحن نشاهد فيلماً." },
      { sv: "Han tittade ut genom fönstret.", ar: "نظر من خلال النافذة." },
    ],
    quizSentences: [
      { form: "presens", sentence: "Jag ___ på nyheter varje kväll.", answer: "tittar", translation: "أشاهد الأخبار كل مساء." },
      { form: "preteritum", sentence: "De ___ på fotboll igår.", answer: "tittade", translation: "شاهدوا كرة القدم أمس." },
      { form: "imperativ", sentence: "___ hit!", answer: "Titta", translation: "انظر هنا!" },
    ],
  },
  {
    infinitiv: "laga",
    presens: "lagar",
    preteritum: "lagade",
    supinum: "lagat",
    imperativ: "laga",
    futurum: "ska laga",
    presensParticip: "lagande",
    perfektParticip: "lagad",
    passivPresens: "lagas",
    passivPreteritum: "lagades",
    translation: "يطبخ / يصلح",
    phonetic: "/ˈlɑːɡa/",
    group: "1",
    level: "A1",
    category: "mat",
    imageUrl: IMG.food,
    notes: "laga mat = يطبخ الطعام. laga bilen = يصلح السيارة.",
    examples: [
      { sv: "Mamma lagar mat.", ar: "الأم تطبخ الطعام." },
      { sv: "Kan du laga cykeln?", ar: "هل يمكنك إصلاح الدراجة؟" },
      { sv: "Jag lagade köttbullar igår.", ar: "طبخت كرات اللحم أمس." },
    ],
    quizSentences: [
      { form: "presens", sentence: "Hon ___ mat varje dag.", answer: "lagar", translation: "هي تطبخ الطعام كل يوم." },
      { form: "preteritum", sentence: "Pappa ___ fisk till middag.", answer: "lagade", translation: "الأب طبخ السمك للعشاء." },
      { form: "futurum", sentence: "Jag ___ pannkakor imorgon.", answer: "ska laga", translation: "سأطبخ الفطائر غداً." },
    ],
  },
  {
    infinitiv: "fråga",
    presens: "frågar",
    preteritum: "frågade",
    supinum: "frågat",
    imperativ: "fråga",
    futurum: "ska fråga",
    presensParticip: "frågande",
    perfektParticip: "frågad",
    passivPresens: "frågas",
    passivPreteritum: "frågades",
    translation: "يسأل",
    phonetic: "/ˈfrɔːɡa/",
    group: "1",
    level: "A1",
    category: "kommunikation",
    imageUrl: IMG.school,
    notes: "ضده: svara (يجيب). fråga om = يسأل عن.",
    examples: [
      { sv: "Fråga läraren om du inte förstår.", ar: "اسأل المعلم إن لم تفهم." },
      { sv: "Jag frågade om vägen.", ar: "سألت عن الطريق." },
      { sv: "Hon frågade vad klockan är.", ar: "سألت كم الساعة." },
    ],
    quizSentences: [
      { form: "presens", sentence: "Varför ___ du alltid?", answer: "frågar", translation: "لماذا تسأل دائماً؟" },
      { form: "preteritum", sentence: "Han ___ om priset.", answer: "frågade", translation: "سأل عن السعر." },
      { form: "imperativ", sentence: "___ om du behöver hjälp!", answer: "Fråga", translation: "اسأل إذا احتجت مساعدة!" },
    ],
  },

  // ══════════════════════════════════════════════════════════════════
  // GRUPP 2a — short -er verbs (-de, -t)
  // ══════════════════════════════════════════════════════════════════
  {
    infinitiv: "ringa",
    presens: "ringer",
    preteritum: "ringde",
    supinum: "ringt",
    imperativ: "ring",
    futurum: "ska ringa",
    presensParticip: "ringande",
    perfektParticip: "ringt",
    passivPresens: "rings",
    passivPreteritum: "ringdes",
    translation: "يتصل (هاتفياً) / يرن",
    phonetic: "/ˈrɪŋːa/",
    group: "2a",
    level: "A1",
    category: "kommunikation",
    imageUrl: IMG.speak,
    notes: "مجموعة 2a — ينتهي الماضي بـ -de. ringa till = يتصل بـ.",
    examples: [
      { sv: "Jag ringer dig ikväll.", ar: "سأتصل بك الليلة." },
      { sv: "Ring ambulansen!", ar: "اتصل بالإسعاف!" },
      { sv: "Hon ringde mig tre gånger.", ar: "اتصلت بي ثلاث مرات." },
    ],
    quizSentences: [
      { form: "presens", sentence: "Jag ___ mamma varje söndag.", answer: "ringer", translation: "أتصل بأمي كل أحد." },
      { form: "preteritum", sentence: "Han ___ polisen.", answer: "ringde", translation: "اتصل بالشرطة." },
      { form: "imperativ", sentence: "___ mig när du är framme!", answer: "Ring", translation: "اتصل بي عندما تصل!" },
    ],
  },
  {
    infinitiv: "stänga",
    // Already added — skip
    // But let's add "läsa" here instead
    infinitiv: "läsa",
    presens: "läser",
    preteritum: "läste",
    supinum: "läst",
    imperativ: "läs",
    futurum: "ska läsa",
    presensParticip: "läsande",
    perfektParticip: "läst",
    passivPresens: "läses",
    passivPreteritum: "lästes",
    translation: "يقرأ / يدرس",
    phonetic: "/ˈlɛːsa/",
    group: "2b",
    level: "A1",
    category: "skola",
    imageUrl: IMG.school,
    notes: "مجموعة 2b. läsa + ämne = يدرس مادة. الأمر: läs.",
    examples: [
      { sv: "Jag läser en bok.", ar: "أنا أقرأ كتاباً." },
      { sv: "Han läser medicin.", ar: "هو يدرس الطب." },
      { sv: "Läs texten noga!", ar: "اقرأ النص بعناية!" },
    ],
    quizSentences: [
      { form: "presens", sentence: "Hon ___ tidningen varje morgon.", answer: "läser", translation: "هي تقرأ الجريدة كل صباح." },
      { form: "preteritum", sentence: "Vi ___ boken i skolan.", answer: "läste", translation: "قرأنا الكتاب في المدرسة." },
      { form: "imperativ", sentence: "___ kapitel tre!", answer: "Läs", translation: "اقرأ الفصل الثالث!" },
    ],
  },

  // ══════════════════════════════════════════════════════════════════
  // GRUPP 3 — short verbs (-r, -dde, -tt)
  // ══════════════════════════════════════════════════════════════════
  {
    infinitiv: "bo",
    presens: "bor",
    preteritum: "bodde",
    supinum: "bott",
    imperativ: "bo",
    futurum: "ska bo",
    presensParticip: "boende",
    perfektParticip: "bott",
    passivPresens: "bos",
    passivPreteritum: "boddes",
    translation: "يسكن / يعيش",
    phonetic: "/buː/",
    group: "3",
    level: "A1",
    category: "hem",
    imageUrl: IMG.nature,
    notes: "مجموعة 3 — أفعال قصيرة. الماضي: -dde.",
    examples: [
      { sv: "Jag bor i Sverige.", ar: "أسكن في السويد." },
      { sv: "Han bodde i Göteborg.", ar: "عاش في يوتيبوري." },
      { sv: "Var bor du?", ar: "أين تسكن؟" },
    ],
    quizSentences: [
      { form: "presens", sentence: "Vi ___ nära skolan.", answer: "bor", translation: "نسكن قرب المدرسة." },
      { form: "preteritum", sentence: "Hon ___ i London för länge sedan.", answer: "bodde", translation: "سكنت في لندن منذ زمن طويل." },
      { form: "futurum", sentence: "Jag ___ i Stockholm nästa år.", answer: "ska bo", translation: "سأسكن في ستوكهولم السنة القادمة." },
    ],
  },
  {
    infinitiv: "tro",
    presens: "tror",
    preteritum: "trodde",
    supinum: "trott",
    imperativ: "tro",
    futurum: "ska tro",
    presensParticip: "troende",
    perfektParticip: "trott",
    passivPresens: "tros",
    passivPreteritum: "troddes",
    translation: "يعتقد / يؤمن",
    phonetic: "/truː/",
    group: "3",
    level: "A2",
    category: "tanke",
    imageUrl: IMG.school,
    notes: "مجموعة 3. tro att = يعتقد أن. tro på = يؤمن بـ.",
    examples: [
      { sv: "Jag tror att det regnar imorgon.", ar: "أعتقد أنه سيمطر غداً." },
      { sv: "Tror du på mig?", ar: "هل تصدقني / تؤمن بي؟" },
      { sv: "Han trodde att hon var sjuk.", ar: "اعتقد أنها كانت مريضة." },
    ],
    quizSentences: [
      { form: "presens", sentence: "Jag ___ att han har rätt.", answer: "tror", translation: "أعتقد أنه على حق." },
      { form: "preteritum", sentence: "Vi ___ att det var sant.", answer: "trodde", translation: "اعتقدنا أن ذلك كان صحيحاً." },
    ],
  },

  // ══════════════════════════════════════════════════════════════════
  // OREGELBUNDET (Irregular)
  // ══════════════════════════════════════════════════════════════════
  {
    infinitiv: "vara",
    presens: "är",
    preteritum: "var",
    supinum: "varit",
    imperativ: "var",
    futurum: "ska vara / kommer att vara",
    presensParticip: "varande",
    perfektParticip: "varit",
    passivPresens: null,
    passivPreteritum: null,
    translation: "يكون / يوجد",
    phonetic: "/ˈvɑːra/",
    group: "oregelbundet",
    level: "A1",
    category: "kärnverb",
    imageUrl: IMG.school,
    notes: "الفعل الأساسي في السويدية. غير منتظم تماماً: presens = är (وليس *varar).",
    examples: [
      { sv: "Jag är student.", ar: "أنا طالب." },
      { sv: "Det var kallt igår.", ar: "كان الجو بارداً أمس." },
      { sv: "Var snäll!", ar: "كن لطيفاً!" },
    ],
    quizSentences: [
      { form: "presens", sentence: "Hon ___ lärare.", answer: "är", translation: "هي معلمة." },
      { form: "preteritum", sentence: "Vi ___ trötta efter resan.", answer: "var", translation: "كنا متعبين بعد الرحلة." },
      { form: "imperativ", sentence: "___ försiktig!", answer: "Var", translation: "كن حذراً!" },
    ],
  },
  {
    infinitiv: "ha",
    presens: "har",
    preteritum: "hade",
    supinum: "haft",
    imperativ: "ha",
    futurum: "ska ha",
    presensParticip: "havande",
    perfektParticip: "haft",
    passivPresens: null,
    passivPreteritum: null,
    translation: "يملك / لديه",
    phonetic: "/hɑː/",
    group: "oregelbundet",
    level: "A1",
    category: "kärnverb",
    imageUrl: IMG.family,
    notes: "الفعل المساعد الأساسي. يُستخدم لبناء المضارع التام: jag har ätit = أكلت.",
    examples: [
      { sv: "Jag har en hund.", ar: "لدي كلب." },
      { sv: "Har du tid?", ar: "هل لديك وقت؟" },
      { sv: "Vi har haft tur.", ar: "لقد كنا محظوظين." },
    ],
    quizSentences: [
      { form: "presens", sentence: "Hon ___ två katter.", answer: "har", translation: "لديها قطتان." },
      { form: "preteritum", sentence: "De ___ inte råd.", answer: "hade", translation: "لم يكن لديهم المال الكافي." },
      { form: "supinum", sentence: "Jag ___ aldrig smakat köttbullar.", answer: "har ... haft / har aldrig ätit", translation: "لم أتذوق كرات اللحم قط." },
    ],
  },
  {
    infinitiv: "gå",
    presens: "går",
    preteritum: "gick",
    supinum: "gått",
    imperativ: "gå",
    futurum: "ska gå",
    presensParticip: "gående",
    perfektParticip: "gången",
    passivPresens: "gås",
    passivPreteritum: null,
    translation: "يمشي / يذهب",
    phonetic: "/ɡɔː/",
    group: "oregelbundet",
    level: "A1",
    category: "rörelse",
    imageUrl: IMG.walk,
    notes: "الماضي 'gick' غير منتظم تماماً. gå till = يذهب إلى. gå på = يحضر.",
    examples: [
      { sv: "Jag går till skolan.", ar: "أذهب إلى المدرسة." },
      { sv: "Vi gick i parken.", ar: "مشينا في الحديقة." },
      { sv: "Gå rakt fram!", ar: "امش مستقيماً!" },
    ],
    quizSentences: [
      { form: "presens", sentence: "Han ___ till jobbet varje dag.", answer: "går", translation: "هو يذهب إلى العمل كل يوم." },
      { form: "preteritum", sentence: "Vi ___ hem tidigt.", answer: "gick", translation: "ذهبنا إلى المنزل مبكراً." },
      { form: "imperativ", sentence: "___ och köp mjölk!", answer: "Gå", translation: "اذهب واشتر حليباً!" },
    ],
  },
  {
    infinitiv: "komma",
    presens: "kommer",
    preteritum: "kom",
    supinum: "kommit",
    imperativ: "kom",
    futurum: "ska komma / kommer att komma",
    presensParticip: "kommande",
    perfektParticip: "kommen",
    passivPresens: null,
    passivPreteritum: null,
    translation: "يأتي / يصل",
    phonetic: "/ˈkɔmːa/",
    group: "oregelbundet",
    level: "A1",
    category: "rörelse",
    imageUrl: IMG.walk,
    notes: "مهم: 'kommer att + infinitiv' = المستقبل القريب. 'kom' هو الماضي الغير منتظم.",
    examples: [
      { sv: "Kom hit!", ar: "تعال إلى هنا!" },
      { sv: "När kommer du?", ar: "متى ستأتي؟" },
      { sv: "Hon kom sent till mötet.", ar: "وصلت متأخرة إلى الاجتماع." },
    ],
    quizSentences: [
      { form: "presens", sentence: "Tåget ___ klockan tre.", answer: "kommer", translation: "القطار يصل الساعة الثالثة." },
      { form: "preteritum", sentence: "Han ___ inte igår.", answer: "kom", translation: "لم يأتِ أمس." },
      { form: "imperativ", sentence: "___ och hjälp mig!", answer: "Kom", translation: "تعال وساعدني!" },
    ],
  },
  {
    infinitiv: "se",
    presens: "ser",
    preteritum: "såg",
    supinum: "sett",
    imperativ: "se",
    futurum: "ska se",
    presensParticip: "seende",
    perfektParticip: "sedd",
    passivPresens: "ses",
    passivPreteritum: "sågst",
    translation: "يرى / يشاهد",
    phonetic: "/seː/",
    group: "oregelbundet",
    level: "A1",
    category: "sinnen",
    imageUrl: IMG.school,
    notes: "غير منتظم: såg (ماضٍ). se ut = يبدو. vi ses = إلى اللقاء.",
    examples: [
      { sv: "Jag ser dig!", ar: "أراك!" },
      { sv: "Vi såg en film igår.", ar: "شاهدنا فيلماً أمس." },
      { sv: "Vi ses imorgon!", ar: "إلى اللقاء غداً!" },
    ],
    quizSentences: [
      { form: "presens", sentence: "Kan du ___ tavlan?", answer: "se", translation: "هل يمكنك رؤية اللوحة؟" },
      { form: "preteritum", sentence: "Jag ___ honom igår.", answer: "såg", translation: "رأيته أمس." },
      { form: "presens (3sg)", sentence: "Hon ___ trött ut.", answer: "ser", translation: "تبدو متعبة." },
    ],
  },
  {
    infinitiv: "ta",
    presens: "tar",
    preteritum: "tog",
    supinum: "tagit",
    imperativ: "ta",
    futurum: "ska ta",
    presensParticip: "tagande",
    perfektParticip: "tagen",
    passivPresens: "tas",
    passivPreteritum: "togs",
    translation: "يأخذ",
    phonetic: "/tɑː/",
    group: "oregelbundet",
    level: "A1",
    category: "rörelse",
    imageUrl: IMG.walk,
    notes: "ta bussen = يركب الحافلة. ta tid = يستغرق وقتاً. ماضٍ: tog.",
    examples: [
      { sv: "Ta en kaka!", ar: "خذ كعكة!" },
      { sv: "Jag tar bussen till jobbet.", ar: "أركب الحافلة إلى العمل." },
      { sv: "Han tog sin jacka.", ar: "أخذ جاكيته." },
    ],
    quizSentences: [
      { form: "presens", sentence: "Hon ___ alltid tåget.", answer: "tar", translation: "هي دائماً تركب القطار." },
      { form: "preteritum", sentence: "Vi ___ en fika.", answer: "tog", translation: "أخذنا استراحة قهوة." },
      { form: "imperativ", sentence: "___ det lugnt!", answer: "Ta", translation: "هدّئ من روعك!" },
    ],
  },
  {
    infinitiv: "ge",
    presens: "ger",
    preteritum: "gav",
    supinum: "gett",
    imperativ: "ge",
    futurum: "ska ge",
    presensParticip: "givande",
    perfektParticip: "given",
    passivPresens: "ges",
    passivPreteritum: "gavs",
    translation: "يعطي",
    phonetic: "/jeː/",
    group: "oregelbundet",
    level: "A1",
    category: "kommunikation",
    imageUrl: IMG.family,
    notes: "ماضٍ: gav. ge sig = يستسلم. ge upp = يستسلم.",
    examples: [
      { sv: "Ge mig boken!", ar: "أعطني الكتاب!" },
      { sv: "Han gav henne en blomma.", ar: "أعطاها وردة." },
      { sv: "Jag ska ge dig ett tips.", ar: "سأعطيك نصيحة." },
    ],
    quizSentences: [
      { form: "presens", sentence: "Läraren ___ oss läxor.", answer: "ger", translation: "المعلم يعطينا واجباً." },
      { form: "preteritum", sentence: "Mamma ___ mig en present.", answer: "gav", translation: "الأم أعطتني هدية." },
      { form: "imperativ", sentence: "___ mig en chans!", answer: "Ge", translation: "أعطني فرصة!" },
    ],
  },
  {
    infinitiv: "veta",
    presens: "vet",
    preteritum: "visste",
    supinum: "vetat",
    imperativ: "vet",
    futurum: "ska veta",
    presensParticip: "vetande",
    perfektParticip: "vetat",
    passivPresens: null,
    passivPreteritum: null,
    translation: "يعرف / يعلم",
    phonetic: "/ˈveːta/",
    group: "oregelbundet",
    level: "A1",
    category: "tanke",
    imageUrl: IMG.school,
    notes: "مهم: المضارع 'vet' (لا 'vetar'). ماضٍ: visste.",
    examples: [
      { sv: "Jag vet inte.", ar: "لا أعرف." },
      { sv: "Vet du var han bor?", ar: "هل تعرف أين يسكن؟" },
      { sv: "Hon visste svaret.", ar: "كانت تعرف الإجابة." },
    ],
    quizSentences: [
      { form: "presens", sentence: "Jag ___ inte vad det betyder.", answer: "vet", translation: "لا أعرف ماذا يعني." },
      { form: "preteritum", sentence: "Vi ___ inte att det var svårt.", answer: "visste", translation: "لم نكن نعلم أن ذلك كان صعباً." },
    ],
  },
  {
    infinitiv: "vilja",
    presens: "vill",
    preteritum: "ville",
    supinum: "velat",
    imperativ: "–",
    futurum: "ska vilja",
    presensParticip: "villjande",
    perfektParticip: "velat",
    passivPresens: null,
    passivPreteritum: null,
    translation: "يريد",
    phonetic: "/ˈvɪlːja/",
    group: "oregelbundet",
    level: "A1",
    category: "känsla",
    imageUrl: IMG.family,
    notes: "فعل مودالي — لا أمر له. vill + infinitiv: Jag vill äta = أريد أن آكل.",
    examples: [
      { sv: "Jag vill lära mig svenska.", ar: "أريد أن أتعلم السويدية." },
      { sv: "Vad vill du ha?", ar: "ماذا تريد؟" },
      { sv: "Hon ville inte komma.", ar: "لم تكن تريد أن تأتي." },
    ],
    quizSentences: [
      { form: "presens", sentence: "Jag ___ ha en kopp kaffe.", answer: "vill", translation: "أريد كوب قهوة." },
      { form: "preteritum", sentence: "Han ___ inte äta.", answer: "ville", translation: "لم يكن يريد أن يأكل." },
    ],
  },
  {
    infinitiv: "kunna",
    presens: "kan",
    preteritum: "kunde",
    supinum: "kunnat",
    imperativ: "–",
    futurum: "ska kunna",
    presensParticip: "kunnande",
    perfektParticip: "kunnat",
    passivPresens: null,
    passivPreteritum: null,
    translation: "يستطيع / يقدر",
    phonetic: "/ˈkɵnːa/",
    group: "oregelbundet",
    level: "A1",
    category: "kärnverb",
    imageUrl: IMG.school,
    notes: "فعل مودالي. kan + infinitiv = يستطيع. kan du? = هل تستطيع؟",
    examples: [
      { sv: "Kan du tala svenska?", ar: "هل تستطيع التحدث السويدية؟" },
      { sv: "Jag kan inte komma.", ar: "لا أستطيع المجيء." },
      { sv: "Hon kunde simma när hon var liten.", ar: "كانت تستطيع السباحة وهي صغيرة." },
    ],
    quizSentences: [
      { form: "presens", sentence: "Jag ___ inte förstå.", answer: "kan", translation: "لا أستطيع الفهم." },
      { form: "preteritum", sentence: "Han ___ inte sova.", answer: "kunde", translation: "لم يستطع النوم." },
    ],
  },
  {
    infinitiv: "skriva",
    presens: "skriver",
    preteritum: "skrev",
    supinum: "skrivit",
    imperativ: "skriv",
    futurum: "ska skriva",
    presensParticip: "skrivande",
    perfektParticip: "skriven",
    passivPresens: "skrivs",
    passivPreteritum: "skrevs",
    translation: "يكتب",
    phonetic: "/ˈskriːva/",
    group: "oregelbundet",
    level: "A1",
    category: "kommunikation",
    imageUrl: IMG.school,
    notes: "غير منتظم. skriva ett brev = يكتب رسالة. الأمر: skriv.",
    examples: [
      { sv: "Jag skriver ett brev.", ar: "أكتب رسالة." },
      { sv: "Skriv ditt namn här!", ar: "اكتب اسمك هنا!" },
      { sv: "Hon skrev ett långt mejl.", ar: "كتبت بريداً إلكترونياً طويلاً." },
    ],
    quizSentences: [
      { form: "presens", sentence: "Han ___ en roman.", answer: "skriver", translation: "هو يكتب رواية." },
      { form: "preteritum", sentence: "Jag ___ ett brev till min familj.", answer: "skrev", translation: "كتبت رسالة لعائلتي." },
      { form: "imperativ", sentence: "___ tydligare!", answer: "Skriv", translation: "اكتب بشكل أوضح!" },
    ],
  },
  {
    infinitiv: "äta",
    presens: "äter",
    preteritum: "åt",
    supinum: "ätit",
    imperativ: "ät",
    futurum: "ska äta",
    presensParticip: "ätande",
    perfektParticip: "äten",
    passivPresens: "äts",
    passivPreteritum: "åts",
    translation: "يأكل",
    phonetic: "/ˈɛːta/",
    group: "oregelbundet",
    level: "A1",
    category: "mat",
    imageUrl: IMG.food,
    notes: "غير منتظم. الماضي: åt. äta frukost/lunch/middag = يتناول الفطور/الغداء/العشاء.",
    examples: [
      { sv: "Jag äter frukost varje dag.", ar: "آكل الفطور كل يوم." },
      { sv: "Vi åt middag klockan sex.", ar: "تناولنا العشاء الساعة السادسة." },
      { sv: "Ät upp maten!", ar: "أكمل طعامك!" },
    ],
    quizSentences: [
      { form: "presens", sentence: "Vad ___ du till lunch?", answer: "äter", translation: "ماذا تأكل على الغداء؟" },
      { form: "preteritum", sentence: "Vi ___ pizza igår.", answer: "åt", translation: "أكلنا بيتزا أمس." },
      { form: "imperativ", sentence: "___ mer grönsaker!", answer: "Ät", translation: "كل المزيد من الخضار!" },
    ],
  },
  {
    infinitiv: "dricka",
    presens: "dricker",
    preteritum: "drack",
    supinum: "druckit",
    imperativ: "drick",
    futurum: "ska dricka",
    presensParticip: "drickande",
    perfektParticip: "drucken",
    passivPresens: "dricks",
    passivPreteritum: "dracks",
    translation: "يشرب",
    phonetic: "/ˈdrɪkːa/",
    group: "oregelbundet",
    level: "A1",
    category: "mat",
    imageUrl: IMG.food,
    notes: "غير منتظم. الماضي: drack. dricka kaffe/te/vatten = يشرب قهوة/شاياً/ماء.",
    examples: [
      { sv: "Jag dricker kaffe på morgonen.", ar: "أشرب القهوة في الصباح." },
      { sv: "Drick mer vatten!", ar: "اشرب المزيد من الماء!" },
      { sv: "Han drack te på kvällen.", ar: "شرب شاياً في المساء." },
    ],
    quizSentences: [
      { form: "presens", sentence: "Vad ___ du vanligtvis?", answer: "dricker", translation: "ماذا تشرب عادةً؟" },
      { form: "preteritum", sentence: "Vi ___ juice till frukost.", answer: "drack", translation: "شربنا عصيراً على الفطور." },
      { form: "imperativ", sentence: "___ upp din mjölk!", answer: "Drick", translation: "اشرب حليبك!" },
    ],
  },
  {
    infinitiv: "sova",
    presens: "sover",
    preteritum: "sov",
    supinum: "sovit",
    imperativ: "sov",
    futurum: "ska sova",
    presensParticip: "sovande",
    perfektParticip: "sovet",
    passivPresens: null,
    passivPreteritum: null,
    translation: "ينام",
    phonetic: "/ˈsuːva/",
    group: "oregelbundet",
    level: "A1",
    category: "vardag",
    imageUrl: IMG.sleep,
    notes: "غير منتظم. الماضي: sov. sova gott = ينام جيداً.",
    examples: [
      { sv: "Jag sover åtta timmar.", ar: "أنام ثماني ساعات." },
      { sv: "Barnet sov länge.", ar: "نام الطفل طويلاً." },
      { sv: "Sov gott!", ar: "نم هنيئاً!" },
    ],
    quizSentences: [
      { form: "presens", sentence: "Han ___ fortfarande.", answer: "sover", translation: "لا يزال نائماً." },
      { form: "preteritum", sentence: "Jag ___ dåligt igår.", answer: "sov", translation: "نمت بشكل سيء أمس." },
      { form: "imperativ", sentence: "___ nu, det är sent!", answer: "Sov", translation: "نم الآن، الوقت متأخر!" },
    ],
  },
  {
    infinitiv: "förstå",
    presens: "förstår",
    preteritum: "förstod",
    supinum: "förstått",
    imperativ: "förstå",
    futurum: "ska förstå",
    presensParticip: "förstående",
    perfektParticip: "förstådd",
    passivPresens: "förstås",
    passivPreteritum: "förstods",
    translation: "يفهم",
    phonetic: "/fœˈstɔː/",
    group: "oregelbundet",
    level: "A1",
    category: "tanke",
    imageUrl: IMG.school,
    notes: "غير منتظم. الماضي: förstod. förstå sig på = يفهم في مجال.",
    examples: [
      { sv: "Förstår du?", ar: "هل تفهم؟" },
      { sv: "Jag förstår inte.", ar: "لا أفهم." },
      { sv: "Han förstod äntligen.", ar: "فهم أخيراً." },
    ],
    quizSentences: [
      { form: "presens", sentence: "Jag ___ inte den här meningen.", answer: "förstår", translation: "لا أفهم هذه الجملة." },
      { form: "preteritum", sentence: "Vi ___ inte frågan.", answer: "förstod", translation: "لم نفهم السؤال." },
    ],
  },
];

// Fix duplicate infinitiv (stänga added twice, replace with läsa)
const uniqueVerbs = verbs.filter((v, i, arr) =>
  arr.findIndex(x => x.infinitiv === v.infinitiv) === i
);

async function seed() {
  console.log("🌱 Seeding verbs...");
  await db.delete(verbsTable);
  console.log("🗑️  Cleared existing verbs");

  for (let i = 0; i < uniqueVerbs.length; i++) {
    const v = uniqueVerbs[i];
    await db.insert(verbsTable).values({
      infinitiv: v.infinitiv,
      presens: v.presens,
      preteritum: v.preteritum,
      supinum: v.supinum,
      imperativ: v.imperativ,
      futurum: v.futurum,
      presensParticip: v.presensParticip,
      perfektParticip: v.perfektParticip,
      passivPresens: v.passivPresens ?? null,
      passivPreteritum: v.passivPreteritum ?? null,
      translation: v.translation,
      phonetic: v.phonetic,
      group: v.group,
      level: v.level,
      category: v.category,
      imageUrl: v.imageUrl ?? null,
      notes: v.notes ?? null,
      examples: v.examples,
      quizSentences: v.quizSentences,
    });
    console.log(`✅ [${i + 1}/${uniqueVerbs.length}] ${v.infinitiv} — ${v.translation}`);
  }

  console.log(`\n🎉 Seeded ${uniqueVerbs.length} verbs!`);
  process.exit(0);
}

seed().catch((e) => { console.error(e); process.exit(1); });
