import { db, verbsTable } from "@workspace/db";

// Extra verbs batch 2 — inserts without deleting existing data

const IMG = {
  love:      "https://images.pexels.com/photos/1024993/pexels-photo-1024993.jpeg?auto=compress&cs=tinysrgb&w=612&h=408&dpr=1",
  laugh:     "https://images.pexels.com/photos/1446948/pexels-photo-1446948.jpeg?auto=compress&cs=tinysrgb&w=612&h=408&dpr=1",
  dance:     "https://images.pexels.com/photos/1701202/pexels-photo-1701202.jpeg?auto=compress&cs=tinysrgb&w=612&h=408&dpr=1",
  cook:      "https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=612&h=408&dpr=1",
  home:      "https://images.pexels.com/photos/1080721/pexels-photo-1080721.jpeg?auto=compress&cs=tinysrgb&w=612&h=408&dpr=1",
  drive:     "https://images.pexels.com/photos/3802510/pexels-photo-3802510.jpeg?auto=compress&cs=tinysrgb&w=612&h=408&dpr=1",
  build:     "https://images.pexels.com/photos/1216589/pexels-photo-1216589.jpeg?auto=compress&cs=tinysrgb&w=612&h=408&dpr=1",
  nature:    "https://images.pexels.com/photos/2422461/pexels-photo-2422461.jpeg?auto=compress&cs=tinysrgb&w=612&h=408&dpr=1",
  emotion:   "https://images.pexels.com/photos/3807571/pexels-photo-3807571.jpeg?auto=compress&cs=tinysrgb&w=612&h=408&dpr=1",
  social:    "https://images.pexels.com/photos/1320701/pexels-photo-1320701.jpeg?auto=compress&cs=tinysrgb&w=612&h=408&dpr=1",
  photo:     "https://images.pexels.com/photos/1264210/pexels-photo-1264210.jpeg?auto=compress&cs=tinysrgb&w=612&h=408&dpr=1",
  art:       "https://images.pexels.com/photos/102127/pexels-photo-102127.jpeg?auto=compress&cs=tinysrgb&w=612&h=408&dpr=1",
  shop:      "https://images.pexels.com/photos/5632388/pexels-photo-5632388.jpeg?auto=compress&cs=tinysrgb&w=612&h=408&dpr=1",
  morning:   "https://images.pexels.com/photos/3771069/pexels-photo-3771069.jpeg?auto=compress&cs=tinysrgb&w=612&h=408&dpr=1",
  sport:     "https://images.pexels.com/photos/3621104/pexels-photo-3621104.jpeg?auto=compress&cs=tinysrgb&w=612&h=408&dpr=1",
  money:     "https://images.pexels.com/photos/4386373/pexels-photo-4386373.jpeg?auto=compress&cs=tinysrgb&w=612&h=408&dpr=1",
  speak:     "https://images.pexels.com/photos/7516363/pexels-photo-7516363.jpeg?auto=compress&cs=tinysrgb&w=612&h=408&dpr=1",
  dream:     "https://images.pexels.com/photos/3771115/pexels-photo-3771115.jpeg?auto=compress&cs=tinysrgb&w=612&h=408&dpr=1",
};

const extraVerbs2 = [
  // ══════════════════════════════════════════════════════════════════
  // GRUPP 1 — -ar verbs
  // ══════════════════════════════════════════════════════════════════
  {
    infinitiv: "älska",
    presens: "älskar",
    preteritum: "älskade",
    supinum: "älskat",
    imperativ: "älska",
    futurum: "ska älska",
    presensParticip: "älskande",
    perfektParticip: "älskad",
    passivPresens: "älskas",
    passivPreteritum: "älskades",
    translation: "يُحبّ / يعشق",
    phonetic: "/ˈɛlska/",
    group: "1",
    level: "A1",
    category: "känsla",
    imageUrl: IMG.love,
    notes: "من أهم الأفعال وأكثرها استخداماً. يختلف عن 'tycka om' (أحب بمعنى يُعجبني).",
    examples: [
      { sv: "Jag älskar dig.", ar: "أنا أحبك." },
      { sv: "Hon älskar att läsa böcker.", ar: "هي تعشق القراءة." },
      { sv: "Vi älskar Sverige!", ar: "نحن نحب السويد!" },
    ],
    quizSentences: [
      { form: "presens", sentence: "Jag ___ glass!", answer: "älskar", translation: "أنا أعشق الآيسكريم!" },
      { form: "preteritum", sentence: "De ___ varandra sedan barndomen.", answer: "älskade", translation: "أحبّا بعضهما منذ الطفولة." },
      { form: "imperativ", sentence: "___ livet!", answer: "Älska", translation: "أحبّ الحياة!" },
    ],
  },
  {
    infinitiv: "gilla",
    presens: "gillar",
    preteritum: "gillade",
    supinum: "gillat",
    imperativ: "gilla",
    futurum: "ska gilla",
    presensParticip: "gillande",
    perfektParticip: "gillad",
    passivPresens: "gillas",
    passivPreteritum: "gillades",
    translation: "يُعجبه / يُحبّ (بمعنى خفيف)",
    phonetic: "/ˈjɪla/",
    group: "1",
    level: "A1",
    category: "känsla",
    imageUrl: IMG.social,
    notes: "أخفّ وطأةً من 'älska'. يُستخدم أيضاً للإعجاب على وسائل التواصل الاجتماعي.",
    examples: [
      { sv: "Jag gillar kaffe.", ar: "أنا أحب القهوة." },
      { sv: "Gillar du musik?", ar: "هل تُحبّ الموسيقى؟" },
      { sv: "Hon gillades av alla.", ar: "كانت محبوبة من الجميع." },
    ],
    quizSentences: [
      { form: "presens", sentence: "Jag ___ att spela fotboll.", answer: "gillar", translation: "أنا أحب لعب كرة القدم." },
      { form: "preteritum", sentence: "Han ___ inte filmen.", answer: "gillade", translation: "لم يُعجبه الفيلم." },
      { form: "imperativ", sentence: "___ och dela inlägget!", answer: "Gilla", translation: "أعجب ووزّع المنشور!" },
    ],
  },
  {
    infinitiv: "hata",
    presens: "hatar",
    preteritum: "hatade",
    supinum: "hatat",
    imperativ: "hata",
    futurum: "ska hata",
    presensParticip: "hatande",
    perfektParticip: "hatad",
    passivPresens: "hatas",
    passivPreteritum: "hatades",
    translation: "يكره",
    phonetic: "/ˈhɑːta/",
    group: "1",
    level: "A2",
    category: "känsla",
    imageUrl: IMG.emotion,
    notes: "عكس 'älska'. يُستخدم للتعبير عن الكره الشديد.",
    examples: [
      { sv: "Jag hatar att vänta.", ar: "أنا أكره الانتظار." },
      { sv: "Han hatar väder som är kallt.", ar: "هو يكره الطقس البارد." },
      { sv: "De hatar varandra.", ar: "يكرهان بعضهما." },
    ],
    quizSentences: [
      { form: "presens", sentence: "Jag ___ måndag morgnar.", answer: "hatar", translation: "أنا أكره صباحات الاثنين." },
      { form: "preteritum", sentence: "Hon ___ den gamla jobbet.", answer: "hatade", translation: "كانت تكره العمل القديم." },
      { form: "imperativ", sentence: "___ inte dig själv!", answer: "Hata", translation: "لا تكره نفسك!" },
    ],
  },
  {
    infinitiv: "önska",
    presens: "önskar",
    preteritum: "önskade",
    supinum: "önskat",
    imperativ: "önska",
    futurum: "ska önska",
    presensParticip: "önskande",
    perfektParticip: "önskad",
    passivPresens: "önskas",
    passivPreteritum: "önskades",
    translation: "يتمنّى / يرغب",
    phonetic: "/ˈœnska/",
    group: "1",
    level: "A2",
    category: "känsla",
    imageUrl: IMG.dream,
    notes: "يُستخدم للتعبير عن الأمنيات والرغبات. 'Jag önskar att...' = أتمنى لو...",
    examples: [
      { sv: "Jag önskar dig lycka till!", ar: "أتمنى لك الحظ السعيد!" },
      { sv: "Hon önskade sig en ny cykel.", ar: "تمنّت لنفسها دراجة جديدة." },
      { sv: "Vi önskar er en trevlig resa.", ar: "نتمنى لكم رحلة ممتعة." },
    ],
    quizSentences: [
      { form: "presens", sentence: "Jag ___ att det var sommar.", answer: "önskar", translation: "أتمنى لو كان الصيف." },
      { form: "preteritum", sentence: "Han ___ god jul till alla.", answer: "önskade", translation: "تمنى للجميع عيد ميلاد مجيد." },
      { form: "imperativ", sentence: "___ dig något roligt!", answer: "Önska", translation: "تمنَّ شيئاً ممتعاً لنفسك!" },
    ],
  },
  {
    infinitiv: "skratta",
    presens: "skrattar",
    preteritum: "skrattade",
    supinum: "skrattat",
    imperativ: "skratta",
    futurum: "ska skratta",
    presensParticip: "skrattande",
    perfektParticip: "skrattad",
    passivPresens: "skrattas",
    passivPreteritum: "skrattades",
    translation: "يضحك",
    phonetic: "/ˈskrɑta/",
    group: "1",
    level: "A1",
    category: "känsla",
    imageUrl: IMG.laugh,
    notes: "الضحك! يُستخدم أيضاً في: 'skratta åt' = يضحك على شيء.",
    examples: [
      { sv: "Vi skrattar hela tiden.", ar: "نحن نضحك طوال الوقت." },
      { sv: "Hon skrattade högt.", ar: "ضحكت بصوت عالٍ." },
      { sv: "Skratta inte åt mig!", ar: "لا تضحك عليّ!" },
    ],
    quizSentences: [
      { form: "presens", sentence: "Han ___ mycket när han tittar på komedier.", answer: "skrattar", translation: "هو يضحك كثيراً عندما يشاهد الكوميديا." },
      { form: "preteritum", sentence: "Alla ___ åt vitsen.", answer: "skrattade", translation: "ضحك الجميع على النكتة." },
      { form: "imperativ", sentence: "___ lite, det är roligt!", answer: "Skratta", translation: "اضحك قليلاً، إنه ممتع!" },
    ],
  },
  {
    infinitiv: "ropa",
    presens: "ropar",
    preteritum: "ropade",
    supinum: "ropat",
    imperativ: "ropa",
    futurum: "ska ropa",
    presensParticip: "ropande",
    perfektParticip: "ropad",
    passivPresens: "ropas",
    passivPreteritum: "ropades",
    translation: "يصرخ / ينادي",
    phonetic: "/ˈruːpa/",
    group: "1",
    level: "A2",
    category: "kommunikation",
    imageUrl: IMG.speak,
    notes: "يُستخدم للنداء أو الصراخ. 'ropa på' = ينادي على شخص.",
    examples: [
      { sv: "Hon ropade på hjälp.", ar: "نادت طلباً للمساعدة." },
      { sv: "Barnen ropade av glädje.", ar: "صرخ الأطفال فرحاً." },
      { sv: "Ropa inte inomhus!", ar: "لا تصرخ داخل المبنى!" },
    ],
    quizSentences: [
      { form: "presens", sentence: "Han ___ på sin kompis.", answer: "ropar", translation: "هو ينادي صديقه." },
      { form: "preteritum", sentence: "Hon ___ men ingen svarade.", answer: "ropade", translation: "نادت لكن لم يُجبها أحد." },
      { form: "imperativ", sentence: "___ om du behöver hjälp!", answer: "Ropa", translation: "نادِ إذا احتجت مساعدة!" },
    ],
  },
  {
    infinitiv: "baka",
    presens: "bakar",
    preteritum: "bakade",
    supinum: "bakat",
    imperativ: "baka",
    futurum: "ska baka",
    presensParticip: "bakande",
    perfektParticip: "bakad",
    passivPresens: "bakas",
    passivPreteritum: "bakades",
    translation: "يخبز",
    phonetic: "/ˈbɑːka/",
    group: "1",
    level: "A2",
    category: "mat",
    imageUrl: IMG.cook,
    notes: "من الأنشطة المنزلية الشائعة. 'baka bröd' = يخبز خبزاً، 'baka kaka' = يخبز كعكاً.",
    examples: [
      { sv: "Jag bakar bröd varje söndag.", ar: "أنا أخبز الخبز كل أحد." },
      { sv: "Hon bakade en tårta till sin mamma.", ar: "خبزت كعكة لأمها." },
      { sv: "Baka inte för länge — den bränns!", ar: "لا تخبز طويلاً — سيحترق!" },
    ],
    quizSentences: [
      { form: "presens", sentence: "Han ___ pepparkakor till jul.", answer: "bakar", translation: "هو يخبز كعك الزنجبيل لعيد الميلاد." },
      { form: "preteritum", sentence: "Vi ___ bullar igår.", answer: "bakade", translation: "خبزنا الكعك بالقرفة أمس." },
      { form: "imperativ", sentence: "___ mer, det är jättegott!", answer: "Baka", translation: "اخبز أكثر، إنه لذيذ جداً!" },
    ],
  },
  {
    infinitiv: "odla",
    presens: "odlar",
    preteritum: "odlade",
    supinum: "odlat",
    imperativ: "odla",
    futurum: "ska odla",
    presensParticip: "odlande",
    perfektParticip: "odlad",
    passivPresens: "odlas",
    passivPreteritum: "odlades",
    translation: "يزرع / يُنمّي (نباتاً)",
    phonetic: "/ˈuːdla/",
    group: "1",
    level: "B1",
    category: "natur",
    imageUrl: IMG.nature,
    notes: "شائع جداً في السويد حيث يُحبّ الناس زراعة الخضروات. 'odla grönsaker' = يزرع خضروات.",
    examples: [
      { sv: "Hon odlar tomater på balkongen.", ar: "هي تزرع الطماطم على الشرفة." },
      { sv: "Vi odlade gurkor i somras.", ar: "زرعنا الخيار الصيف الماضي." },
      { sv: "Odla dina egna grönsaker!", ar: "ازرع خضرواتك بنفسك!" },
    ],
    quizSentences: [
      { form: "presens", sentence: "Han ___ äpplen i trädgården.", answer: "odlar", translation: "هو يزرع التفاح في الحديقة." },
      { form: "preteritum", sentence: "De ___ potatis förra året.", answer: "odlade", translation: "زرعوا البطاطس العام الماضي." },
      { form: "imperativ", sentence: "___ egna örter, det är lätt!", answer: "Odla", translation: "ازرع أعشابك الخاصة، إنه سهل!" },
    ],
  },
  {
    infinitiv: "måla",
    presens: "målar",
    preteritum: "målade",
    supinum: "målat",
    imperativ: "måla",
    futurum: "ska måla",
    presensParticip: "målande",
    perfektParticip: "målad",
    passivPresens: "målas",
    passivPreteritum: "målades",
    translation: "يرسم / يدهن",
    phonetic: "/ˈmoːla/",
    group: "1",
    level: "A2",
    category: "konst",
    imageUrl: IMG.art,
    notes: "يُستخدم للرسم الفني وللدهان (كالجدران). 'måla tavla' = يرسم لوحة، 'måla vägg' = يدهن جداراً.",
    examples: [
      { sv: "Han målar vackra landskap.", ar: "هو يرسم مناظر طبيعية جميلة." },
      { sv: "Vi målade köket gult.", ar: "دهنّا المطبخ باللون الأصفر." },
      { sv: "Måla vad du känner!", ar: "ارسم ما تشعر به!" },
    ],
    quizSentences: [
      { form: "presens", sentence: "Hon ___ porträtt av sina vänner.", answer: "målar", translation: "هي ترسم صوراً لأصدقائها." },
      { form: "preteritum", sentence: "De ___ huset förra sommaren.", answer: "målade", translation: "دهنوا المنزل الصيف الماضي." },
      { form: "imperativ", sentence: "___ rummet vitt!", answer: "Måla", translation: "اصبغ الغرفة باللون الأبيض!" },
    ],
  },
  {
    infinitiv: "rita",
    presens: "ritar",
    preteritum: "ritade",
    supinum: "ritat",
    imperativ: "rita",
    futurum: "ska rita",
    presensParticip: "ritande",
    perfektParticip: "ritad",
    passivPresens: "ritas",
    passivPreteritum: "ritades",
    translation: "يرسم (بقلم / رصاص)",
    phonetic: "/ˈriːta/",
    group: "1",
    level: "A1",
    category: "konst",
    imageUrl: IMG.art,
    notes: "الفرق بين 'rita' (رسم بقلم/خطوط) و'måla' (رسم بألوان/دهان).",
    examples: [
      { sv: "Barnet ritar en häst.", ar: "الطفل يرسم حصاناً." },
      { sv: "Kan du rita en karta?", ar: "هل تستطيع رسم خريطة؟" },
      { sv: "Rita hur du vill!", ar: "ارسم كيف تشاء!" },
    ],
    quizSentences: [
      { form: "presens", sentence: "Han ___ alltid i sin dagbok.", answer: "ritar", translation: "هو يرسم دائماً في دفتر يومياته." },
      { form: "preteritum", sentence: "Hon ___ en teckning av sin familj.", answer: "ritade", translation: "رسمت صورة لعائلتها." },
      { form: "imperativ", sentence: "___ en cirkel på tavlan!", answer: "Rita", translation: "ارسم دائرة على السبورة!" },
    ],
  },
  {
    infinitiv: "fotografera",
    presens: "fotograferar",
    preteritum: "fotograferade",
    supinum: "fotograferat",
    imperativ: "fotografera",
    futurum: "ska fotografera",
    presensParticip: "fotograferande",
    perfektParticip: "fotograferad",
    passivPresens: "fotograferas",
    passivPreteritum: "fotograferades",
    translation: "يُصوّر / يلتقط صوراً",
    phonetic: "/fʊtʊˈɡrɑːfera/",
    group: "1",
    level: "A2",
    category: "fritid",
    imageUrl: IMG.photo,
    notes: "في الحديث اليومي يُستخدم 'ta kort' أو 'ta bilder' بدلاً منه كثيراً.",
    examples: [
      { sv: "Hon fotograferar naturen.", ar: "هي تُصوّر الطبيعة." },
      { sv: "Vi fotograferade hela dagen.", ar: "صوّرنا طوال اليوم." },
      { sv: "Fotografera inte utan tillstånd!", ar: "لا تُصوّر بدون إذن!" },
    ],
    quizSentences: [
      { form: "presens", sentence: "Han ___ bröllop som jobb.", answer: "fotograferar", translation: "هو يُصوّر حفلات الأعراس كعمل." },
      { form: "preteritum", sentence: "Hon ___ solnedgången.", answer: "fotograferade", translation: "صوّرت غروب الشمس." },
      { form: "imperativ", sentence: "___ oss, tack!", answer: "Fotografera", translation: "صوّرنا من فضلك!" },
    ],
  },
  {
    infinitiv: "dansa",
    presens: "dansar",
    preteritum: "dansade",
    supinum: "dansat",
    imperativ: "dansa",
    futurum: "ska dansa",
    presensParticip: "dansande",
    perfektParticip: "dansad",
    passivPresens: "dansas",
    passivPreteritum: "dansades",
    translation: "يرقص",
    phonetic: "/ˈdɑnsa/",
    group: "1",
    level: "A1",
    category: "fritid",
    imageUrl: IMG.dance,
    notes: "شائع جداً في السويد خاصةً في حفلات Midsommar وحفلات الميلاد.",
    examples: [
      { sv: "De dansar på festen.", ar: "هم يرقصون في الحفلة." },
      { sv: "Kan du dansa vals?", ar: "هل تستطيع الرقص الفالس؟" },
      { sv: "Dansa med mig!", ar: "ارقص معي!" },
    ],
    quizSentences: [
      { form: "presens", sentence: "Hon ___ balett sedan hon var liten.", answer: "dansar", translation: "هي ترقص الباليه منذ أن كانت صغيرة." },
      { form: "preteritum", sentence: "Vi ___ hela natten.", answer: "dansade", translation: "رقصنا طوال الليل." },
      { form: "imperativ", sentence: "___ nu, musiken är perfekt!", answer: "Dansa", translation: "ارقص الآن، الموسيقى مثالية!" },
    ],
  },
  {
    infinitiv: "hoppa",
    presens: "hoppar",
    preteritum: "hoppade",
    supinum: "hoppat",
    imperativ: "hoppa",
    futurum: "ska hoppa",
    presensParticip: "hoppande",
    perfektParticip: "hoppad",
    passivPresens: "hoppas",
    passivPreteritum: "hoppades",
    translation: "يقفز / يثب",
    phonetic: "/ˈhɔpa/",
    group: "1",
    level: "A1",
    category: "sport",
    imageUrl: IMG.sport,
    notes: "يُستخدم أيضاً بمعنى 'hoppa över' = يتخطى/يتجاوز شيئاً.",
    examples: [
      { sv: "Barnen hoppar på trampolin.", ar: "الأطفال يقفزون على الترامبولين." },
      { sv: "Han hoppade över staketet.", ar: "قفز فوق السياج." },
      { sv: "Hoppa inte, det är farligt!", ar: "لا تقفز، إنه خطير!" },
    ],
    quizSentences: [
      { form: "presens", sentence: "Hon ___ rep varje morgon.", answer: "hoppar", translation: "هي تقفز بالحبل كل صباح." },
      { form: "preteritum", sentence: "Han ___ högt i tävlingen.", answer: "hoppade", translation: "قفز عالياً في المسابقة." },
      { form: "imperativ", sentence: "___ om du törs!", answer: "Hoppa", translation: "اقفز إذا كنت جريئاً!" },
    ],
  },
  {
    infinitiv: "krama",
    presens: "kramar",
    preteritum: "kramade",
    supinum: "kramat",
    imperativ: "krama",
    futurum: "ska krama",
    presensParticip: "kramande",
    perfektParticip: "kramad",
    passivPresens: "kramas",
    passivPreteritum: "kramades",
    translation: "يحتضن / يعانق",
    phonetic: "/ˈkrɑːma/",
    group: "1",
    level: "A1",
    category: "social",
    imageUrl: IMG.love,
    notes: "السويديون أقل ميلاً للأحضان مع الغرباء، لكنهم يحتضنون الأصدقاء والعائلة بدفء.",
    examples: [
      { sv: "Hon kramade sitt barn.", ar: "احتضنت طفلها." },
      { sv: "De kramades vid återseendet.", ar: "تعانقا عند لقائهما." },
      { sv: "Krama om mig!", ar: "احضنني!" },
    ],
    quizSentences: [
      { form: "presens", sentence: "Han ___ sin hund varje dag.", answer: "kramar", translation: "هو يحتضن كلبه كل يوم." },
      { form: "preteritum", sentence: "Vi ___ varandra länge.", answer: "kramade", translation: "احتضنّا بعضنا طويلاً." },
      { form: "imperativ", sentence: "___ din kompis, hon är ledsen.", answer: "Krama", translation: "احضن صديقتك، إنها حزينة." },
    ],
  },
  {
    infinitiv: "vinka",
    presens: "vinkar",
    preteritum: "vinkade",
    supinum: "vinkat",
    imperativ: "vinka",
    futurum: "ska vinka",
    presensParticip: "vinkande",
    perfektParticip: "vinkad",
    passivPresens: "vinkas",
    passivPreteritum: "vinkades",
    translation: "يُلوّح / يُشير باليد",
    phonetic: "/ˈvɪŋka/",
    group: "1",
    level: "A1",
    category: "kommunikation",
    imageUrl: IMG.social,
    notes: "يُستخدم للتحية بالإشارة أو للتلويح وداعاً.",
    examples: [
      { sv: "Hon vinkade hejdå vid tåget.", ar: "لوّحت بالوداع عند القطار." },
      { sv: "Barnen vinkade till busschauffören.", ar: "لوّح الأطفال لسائق الحافلة." },
      { sv: "Vinka om du ser mig!", ar: "لوّح لي إذا رأيتني!" },
    ],
    quizSentences: [
      { form: "presens", sentence: "Han ___ till sin granne varje morgon.", answer: "vinkar", translation: "هو يُلوّح لجاره كل صباح." },
      { form: "preteritum", sentence: "Hon ___ farväl från fönstret.", answer: "vinkade", translation: "لوّحت بالوداع من النافذة." },
      { form: "imperativ", sentence: "___ om du behöver hjälp!", answer: "Vinka", translation: "أشِر إذا احتجت مساعدة!" },
    ],
  },
  {
    infinitiv: "peka",
    presens: "pekar",
    preteritum: "pekade",
    supinum: "pekat",
    imperativ: "peka",
    futurum: "ska peka",
    presensParticip: "pekande",
    perfektParticip: "pekad",
    passivPresens: "pekas",
    passivPreteritum: "pekades",
    translation: "يُشير / يدلّ",
    phonetic: "/ˈpeːka/",
    group: "1",
    level: "A2",
    category: "kommunikation",
    imageUrl: IMG.speak,
    notes: "يُستخدم للإشارة بالإصبع. 'peka på' = يُشير إلى. قد يُعتبر وقحاً في بعض السياقات.",
    examples: [
      { sv: "Peka på kartan var vi är.", ar: "أشِر على الخريطة أين نحن." },
      { sv: "Han pekade ut rätt väg.", ar: "أشار إلى الطريق الصحيح." },
      { sv: "Peka inte på folk!", ar: "لا تُشر بإصبعك على الناس!" },
    ],
    quizSentences: [
      { form: "presens", sentence: "Hon ___ på tavlan och förklarar.", answer: "pekar", translation: "هي تُشير إلى اللوحة وتشرح." },
      { form: "preteritum", sentence: "Han ___ åt fel håll.", answer: "pekade", translation: "أشار في الاتجاه الخاطئ." },
      { form: "imperativ", sentence: "___ på vad du vill ha!", answer: "Peka", translation: "أشِر إلى ما تريده!" },
    ],
  },
  {
    infinitiv: "nicka",
    presens: "nickar",
    preteritum: "nickade",
    supinum: "nickat",
    imperativ: "nicka",
    futurum: "ska nicka",
    presensParticip: "nickande",
    perfektParticip: "nickad",
    passivPresens: "nickas",
    passivPreteritum: "nickades",
    translation: "يُومئ برأسه",
    phonetic: "/ˈnɪka/",
    group: "1",
    level: "A2",
    category: "kommunikation",
    imageUrl: IMG.social,
    notes: "الإيماء بالرأس علامة على الموافقة أو التحية. يُستخدم أيضاً في كرة القدم (ضربة رأس).",
    examples: [
      { sv: "Hon nickade ja.", ar: "أومأت برأسها بالموافقة." },
      { sv: "Han nickade till hälsning.", ar: "أومأ برأسه تحيةً." },
      { sv: "Nicka om du förstår.", ar: "أومئ برأسك إذا فهمت." },
    ],
    quizSentences: [
      { form: "presens", sentence: "Han ___ alltid när han håller med.", answer: "nickar", translation: "هو يُومئ دائماً عندما يوافق." },
      { form: "preteritum", sentence: "Hon ___ och log.", answer: "nickade", translation: "أومأت وابتسمت." },
      { form: "imperativ", sentence: "___ om du hör mig!", answer: "Nicka", translation: "أومئ إذا كنت تسمعني!" },
    ],
  },
  {
    infinitiv: "duscha",
    presens: "duschar",
    preteritum: "duschade",
    supinum: "duschat",
    imperativ: "duscha",
    futurum: "ska duscha",
    presensParticip: "duschande",
    perfektParticip: "duschad",
    passivPresens: "duschas",
    passivPreteritum: "duschades",
    translation: "يستحمّ (بالدش)",
    phonetic: "/ˈdʊʃa/",
    group: "1",
    level: "A1",
    category: "daglig rutin",
    imageUrl: IMG.morning,
    notes: "من الأفعال اليومية الأساسية. 'ta en dusch' = يأخذ دشاً (نفس المعنى).",
    examples: [
      { sv: "Jag duschar varje morgon.", ar: "أنا أستحمّ كل صباح." },
      { sv: "Han duschade efter träningen.", ar: "استحمّ بعد التدريب." },
      { sv: "Duscha snabbt, vi har bråttom!", ar: "استحمّ بسرعة، نحن في عجلة!" },
    ],
    quizSentences: [
      { form: "presens", sentence: "Hon ___ alltid kallt.", answer: "duschar", translation: "هي تستحمّ دائماً بماء بارد." },
      { form: "preteritum", sentence: "Vi ___ på idrottshallen.", answer: "duschade", translation: "استحممنا في الصالة الرياضية." },
      { form: "imperativ", sentence: "___ och kom sedan!", answer: "Duscha", translation: "استحمّ ثم تعال!" },
    ],
  },
  {
    infinitiv: "bada",
    presens: "badar",
    preteritum: "badade",
    supinum: "badat",
    imperativ: "bada",
    futurum: "ska bada",
    presensParticip: "badande",
    perfektParticip: "badadad",
    passivPresens: "badas",
    passivPreteritum: "badades",
    translation: "يسبح (في بحيرة/بحر) / يستحمّ",
    phonetic: "/ˈbɑːda/",
    group: "1",
    level: "A1",
    category: "fritid",
    imageUrl: IMG.sport,
    notes: "في السويد 'bada' يعني السباحة في الطبيعة (بحيرة أو بحر) وليس فقط في الحوض. السويديون يُحبّون السباحة في الصيف.",
    examples: [
      { sv: "Vi badade i sjön hela sommaren.", ar: "سبحنا في البحيرة طوال الصيف." },
      { sv: "Barnen badar på stranden.", ar: "الأطفال يسبحون على الشاطئ." },
      { sv: "Bada inte ensam i havet!", ar: "لا تسبح وحدك في البحر!" },
    ],
    quizSentences: [
      { form: "presens", sentence: "Hon ___ i havet varje sommar.", answer: "badar", translation: "هي تسبح في البحر كل صيف." },
      { form: "preteritum", sentence: "Vi ___ tills det blev mörkt.", answer: "badade", translation: "سبحنا حتى حلّ الظلام." },
      { form: "imperativ", sentence: "___ nu, vattnet är varmt!", answer: "Bada", translation: "اسبح الآن، الماء دافئ!" },
    ],
  },
  {
    infinitiv: "vakna",
    presens: "vaknar",
    preteritum: "vaknade",
    supinum: "vaknat",
    imperativ: "vakna",
    futurum: "ska vakna",
    presensParticip: "vaknande",
    perfektParticip: "vaknad",
    passivPresens: "vaknas",
    passivPreteritum: "vaknades",
    translation: "يستيقظ",
    phonetic: "/ˈvɑkna/",
    group: "1",
    level: "A1",
    category: "daglig rutin",
    imageUrl: IMG.morning,
    notes: "يختلف عن 'väcka' (يوقظ شخصاً آخر). 'vakna upp' = يصحو / ينتبه.",
    examples: [
      { sv: "Jag vaknar alltid klockan sju.", ar: "أنا أستيقظ دائماً الساعة السابعة." },
      { sv: "Hon vaknade av bullret.", ar: "استيقظت من الضجيج." },
      { sv: "Vakna nu, det är dags!", ar: "استيقظ الآن، حان الوقت!" },
    ],
    quizSentences: [
      { form: "presens", sentence: "Han ___ tidigt varje dag.", answer: "vaknar", translation: "هو يستيقظ مبكراً كل يوم." },
      { form: "preteritum", sentence: "Vi ___ sent på morgonen.", answer: "vaknade", translation: "استيقظنا متأخرين في الصباح." },
      { form: "imperativ", sentence: "___ och lukta på kaffet!", answer: "Vakna", translation: "استيقظ واشمّ رائحة القهوة!" },
    ],
  },
  {
    infinitiv: "skynda",
    presens: "skyndar",
    preteritum: "skyndade",
    supinum: "skyndat",
    imperativ: "skynda",
    futurum: "ska skynda",
    presensParticip: "skyndande",
    perfektParticip: "skyndad",
    passivPresens: "skyndas",
    passivPreteritum: "skyndades",
    translation: "يستعجل / يُسرع",
    phonetic: "/ˈʃʏnda/",
    group: "1",
    level: "A2",
    category: "rörelse",
    imageUrl: IMG.sport,
    notes: "يُستخدم في 'skynda sig' (يتعجّل) و'skynda på' (يُعجّل شيئاً). شائع في التحذيرات.",
    examples: [
      { sv: "Skynda dig, bussen går!", ar: "استعجل، الحافلة ستذهب!" },
      { sv: "Han skyndade till jobbet.", ar: "أسرع إلى العمل." },
      { sv: "Skynda inte, vi har tid.", ar: "لا تتعجل، عندنا وقت." },
    ],
    quizSentences: [
      { form: "presens", sentence: "Hon ___ alltid till möten.", answer: "skyndar", translation: "هي دائماً تتعجّل للاجتماعات." },
      { form: "preteritum", sentence: "Vi ___ oss men missade tåget ändå.", answer: "skyndade", translation: "تعجّلنا لكننا فاتنا القطار رغم ذلك." },
      { form: "imperativ", sentence: "___ dig nu!", answer: "Skynda", translation: "استعجل الآن!" },
    ],
  },
  {
    infinitiv: "parkera",
    presens: "parkerar",
    preteritum: "parkerade",
    supinum: "parkerat",
    imperativ: "parkera",
    futurum: "ska parkera",
    presensParticip: "parkerande",
    perfektParticip: "parkerad",
    passivPresens: "parkeras",
    passivPreteritum: "parkerades",
    translation: "يُوقف السيارة / يركن",
    phonetic: "/parˈkeːra/",
    group: "1",
    level: "A2",
    category: "transport",
    imageUrl: IMG.drive,
    notes: "'parkering' = موقف السيارات. 'parkeringsförbud' = ممنوع الوقوف.",
    examples: [
      { sv: "Var kan jag parkera?", ar: "أين يمكنني وقوف السيارة؟" },
      { sv: "Han parkerade framför affären.", ar: "أوقف سيارته أمام المتجر." },
      { sv: "Parkera inte här!", ar: "لا توقف السيارة هنا!" },
    ],
    quizSentences: [
      { form: "presens", sentence: "Hon ___ alltid på p-huset.", answer: "parkerar", translation: "هي دائماً توقف سيارتها في المرأب." },
      { form: "preteritum", sentence: "Vi ___ gratis idag.", answer: "parkerade", translation: "أوقفنا السيارة مجاناً اليوم." },
      { form: "imperativ", sentence: "___ bilen och kom in!", answer: "Parkera", translation: "أوقف السيارة وتفضل للداخل!" },
    ],
  },
  {
    infinitiv: "samla",
    presens: "samlar",
    preteritum: "samlade",
    supinum: "samlat",
    imperativ: "samla",
    futurum: "ska samla",
    presensParticip: "samlande",
    perfektParticip: "samlad",
    passivPresens: "samlas",
    passivPreteritum: "samlades",
    translation: "يجمع / يُجمّع / يُجنّد",
    phonetic: "/ˈsɑmla/",
    group: "1",
    level: "A2",
    category: "fritid",
    imageUrl: IMG.home,
    notes: "'samla på sig' = يتراكم لديه. 'samla poäng' = يجمع نقاطاً.",
    examples: [
      { sv: "Han samlar på frimärken.", ar: "هو يجمع الطوابع البريدية." },
      { sv: "Vi samlade in pengar till välgörenhet.", ar: "جمعنا المال للأعمال الخيرية." },
      { sv: "Samla ihop dina saker!", ar: "اجمع أغراضك!" },
    ],
    quizSentences: [
      { form: "presens", sentence: "Hon ___ gamla myntar.", answer: "samlar", translation: "هي تجمع العملات القديمة." },
      { form: "preteritum", sentence: "De ___ löv i parken.", answer: "samlade", translation: "جمعوا الأوراق في الحديقة." },
      { form: "imperativ", sentence: "___ alla i vardagsrummet!", answer: "Samla", translation: "اجمع الجميع في غرفة المعيشة!" },
    ],
  },
  {
    infinitiv: "sortera",
    presens: "sorterar",
    preteritum: "sorterade",
    supinum: "sorterat",
    imperativ: "sortera",
    futurum: "ska sortera",
    presensParticip: "sorterande",
    perfektParticip: "sorterad",
    passivPresens: "sorteras",
    passivPreteritum: "sorterades",
    translation: "يُصنّف / يُرتّب / يفرز",
    phonetic: "/sɔrˈteːra/",
    group: "1",
    level: "B1",
    category: "hem",
    imageUrl: IMG.home,
    notes: "مهمّ جداً في السويد لفرز النفايات. 'sortera sopor' = يفرز النفايات للتدوير.",
    examples: [
      { sv: "Sortera soporna rätt!", ar: "افرز النفايات بشكل صحيح!" },
      { sv: "Hon sorterade kläderna efter färg.", ar: "رتّبت الملابس حسب اللون." },
      { sv: "Vi sorterar alltid papper och plast.", ar: "نحن نفرز دائماً الورق والبلاستيك." },
    ],
    quizSentences: [
      { form: "presens", sentence: "Han ___ posten varje fredag.", answer: "sorterar", translation: "هو يُرتّب البريد كل جمعة." },
      { form: "preteritum", sentence: "Vi ___ böckerna i alfabetisk ordning.", answer: "sorterade", translation: "رتّبنا الكتب بالترتيب الأبجدي." },
      { form: "imperativ", sentence: "___ glaset i rätt påse!", answer: "Sortera", translation: "ضع الزجاج في الكيس الصحيح!" },
    ],
  },
  {
    infinitiv: "diska",
    presens: "diskar",
    preteritum: "diskade",
    supinum: "diskat",
    imperativ: "diska",
    futurum: "ska diska",
    presensParticip: "diskande",
    perfektParticip: "diskad",
    passivPresens: "diskas",
    passivPreteritum: "diskades",
    translation: "يغسل الصحون",
    phonetic: "/ˈdɪska/",
    group: "1",
    level: "A1",
    category: "hem",
    imageUrl: IMG.home,
    notes: "'disk' = غسيل الصحون. 'diskmaskin' = غسالة الصحون. 'diskmedel' = صابون الجلي.",
    examples: [
      { sv: "Kan du diska idag?", ar: "هل يمكنك غسل الصحون اليوم؟" },
      { sv: "Han diskade efter middagen.", ar: "غسل الصحون بعد العشاء." },
      { sv: "Diska, det är din tur!", ar: "اغسل الصحون، جاء دورك!" },
    ],
    quizSentences: [
      { form: "presens", sentence: "Hon ___ medan han torkar.", answer: "diskar", translation: "هي تغسل بينما هو يُجفّف." },
      { form: "preteritum", sentence: "Vi ___ ihop efter festen.", answer: "diskade", translation: "غسلنا الصحون معاً بعد الحفلة." },
      { form: "imperativ", sentence: "___ nu, det luktar!", answer: "Diska", translation: "اغسل الصحون الآن، إنها تُنتن!" },
    ],
  },
  {
    infinitiv: "reparera",
    presens: "reparerar",
    preteritum: "reparerade",
    supinum: "reparerat",
    imperativ: "reparera",
    futurum: "ska reparera",
    presensParticip: "repererande",
    perfektParticip: "reparerad",
    passivPresens: "repareras",
    passivPreteritum: "reparerades",
    translation: "يُصلح / يُرمّم",
    phonetic: "/reparˈeːra/",
    group: "1",
    level: "B1",
    category: "hem",
    imageUrl: IMG.build,
    notes: "في الكلام العادي يُستخدم أيضاً 'laga' (أبسط وأكثر شيوعاً). 'reparera' أكثر رسمية.",
    examples: [
      { sv: "Han reparerade bilen själv.", ar: "أصلح السيارة بنفسه." },
      { sv: "Vi behöver reparera taket.", ar: "نحتاج لإصلاح السقف." },
      { sv: "Reparera det innan det blir värre!", ar: "أصلحه قبل أن يزداد سوءاً!" },
    ],
    quizSentences: [
      { form: "presens", sentence: "Hon ___ gamla möbler och säljer dem.", answer: "reparerar", translation: "هي تُصلح الأثاث القديم وتبيعه." },
      { form: "preteritum", sentence: "Mekanikern ___ motorn.", answer: "reparerade", translation: "أصلح الميكانيكي المحرّك." },
      { form: "imperativ", sentence: "___ cykeln innan du åker!", answer: "Reparera", translation: "أصلح الدراجة قبل أن تنطلق!" },
    ],
  },
  {
    infinitiv: "räkna",
    presens: "räknar",
    preteritum: "räknade",
    supinum: "räknat",
    imperativ: "räkna",
    futurum: "ska räkna",
    presensParticip: "räknande",
    perfektParticip: "räknad",
    passivPresens: "räknas",
    passivPreteritum: "räknades",
    translation: "يعدّ / يحسب",
    phonetic: "/ˈrɛkna/",
    group: "1",
    level: "A1",
    category: "matematik",
    imageUrl: IMG.money,
    notes: "'räkna med' = يحسب مع / يعتمد على. 'räkna ut' = يحسب النتيجة.",
    examples: [
      { sv: "Barnet lärde sig räkna till tio.", ar: "تعلّم الطفل العدّ حتى عشرة." },
      { sv: "Kan du räkna ut priset?", ar: "هل يمكنك حساب السعر؟" },
      { sv: "Räkna pengarna innan du betalar!", ar: "عدّ المال قبل أن تدفع!" },
    ],
    quizSentences: [
      { form: "presens", sentence: "Hon ___ alltid noga i affären.", answer: "räknar", translation: "هي تحسب دائماً بدقة في المتجر." },
      { form: "preteritum", sentence: "Han ___ felen i rapporten.", answer: "räknade", translation: "عدّ الأخطاء في التقرير." },
      { form: "imperativ", sentence: "___ till tio och sedan ska vi gå.", answer: "Räkna", translation: "عُدّ حتى عشرة ثم سنذهب." },
    ],
  },
  {
    infinitiv: "låna",
    presens: "lånar",
    preteritum: "lånade",
    supinum: "lånat",
    imperativ: "låna",
    futurum: "ska låna",
    presensParticip: "lånande",
    perfektParticip: "lånad",
    passivPresens: "lånas",
    passivPreteritum: "lånades",
    translation: "يستعير / يُقرض",
    phonetic: "/ˈloːna/",
    group: "1",
    level: "A2",
    category: "ekonomi",
    imageUrl: IMG.money,
    notes: "يُستخدم بمعنيين: 'låna av' = يستعير من، و'låna ut' = يُقرض لشخص آخر.",
    examples: [
      { sv: "Kan jag låna din penna?", ar: "هل يمكنني استعارة قلمك؟" },
      { sv: "Han lånade pengar av banken.", ar: "اقترض مالاً من البنك." },
      { sv: "Låna inte mer än du kan betala tillbaka!", ar: "لا تقترض أكثر مما تستطيع سداده!" },
    ],
    quizSentences: [
      { form: "presens", sentence: "Hon ___ böcker från biblioteket.", answer: "lånar", translation: "هي تستعير كتباً من المكتبة." },
      { form: "preteritum", sentence: "Vi ___ en bil av grannarna.", answer: "lånade", translation: "استعرنا سيارة من الجيران." },
      { form: "imperativ", sentence: "___ inte saker utan att fråga!", answer: "Låna", translation: "لا تستعر أشياء بدون أن تسأل!" },
    ],
  },
  {
    infinitiv: "servera",
    presens: "serverar",
    preteritum: "serverade",
    supinum: "serverat",
    imperativ: "servera",
    futurum: "ska servera",
    presensParticip: "serverande",
    perfektParticip: "serverad",
    passivPresens: "serveras",
    passivPreteritum: "serverades",
    translation: "يُقدّم (الطعام/الشراب)",
    phonetic: "/serˈveːra/",
    group: "1",
    level: "A2",
    category: "mat",
    imageUrl: IMG.cook,
    notes: "يُستخدم في المطاعم والضيافة. 'servering' = طاولات المطعم.",
    examples: [
      { sv: "Restaurangen serverar lunch klockan tolv.", ar: "يُقدّم المطعم الغداء الساعة الثانية عشرة." },
      { sv: "Hon serverade kaffe åt gästerna.", ar: "قدّمت القهوة للضيوف." },
      { sv: "Servera maten varm!", ar: "قدّم الطعام ساخناً!" },
    ],
    quizSentences: [
      { form: "presens", sentence: "Kyparen ___ bordet bredvid oss.", answer: "serverar", translation: "النادل يُقدّم الطلب للطاولة المجاورة." },
      { form: "preteritum", sentence: "Vi ___ tre rätter till middagen.", answer: "serverade", translation: "قدّمنا ثلاثة أطباق في العشاء." },
      { form: "imperativ", sentence: "___ drinken kall!", answer: "Servera", translation: "قدّم المشروب بارداً!" },
    ],
  },
  {
    infinitiv: "undra",
    presens: "undrar",
    preteritum: "undrade",
    supinum: "undrat",
    imperativ: "undra",
    futurum: "ska undra",
    presensParticip: "undrande",
    perfektParticip: "undrad",
    passivPresens: "undras",
    passivPreteritum: "undrades",
    translation: "يتساءل / يتعجّب",
    phonetic: "/ˈɵndra/",
    group: "1",
    level: "A2",
    category: "tanke",
    imageUrl: IMG.speak,
    notes: "يُستخدم للتساؤل والتفكير. 'Jag undrar om...' = أتساءل إذا كان...",
    examples: [
      { sv: "Jag undrar vad hon tänker.", ar: "أتساءل ماذا تفكّر." },
      { sv: "Han undrade om hon kom.", ar: "تساءل إذا كانت ستأتي." },
      { sv: "Undrar du hur det fungerar?", ar: "أتتساءل كيف يعمل هذا؟" },
    ],
    quizSentences: [
      { form: "presens", sentence: "Jag ___ vad klockan är.", answer: "undrar", translation: "أتساءل كم الساعة." },
      { form: "preteritum", sentence: "Hon ___ om det var sant.", answer: "undrade", translation: "تساءلت إذا كان ذلك صحيحاً." },
      { form: "imperativ", sentence: "___ inte, fråga istället!", answer: "Undra", translation: "لا تتساءل، اسأل بدلاً من ذلك!" },
    ],
  },
  {
    infinitiv: "skämta",
    presens: "skämtar",
    preteritum: "skämtade",
    supinum: "skämtat",
    imperativ: "skämta",
    futurum: "ska skämta",
    presensParticip: "skämtande",
    perfektParticip: "skämtad",
    passivPresens: "skämtas",
    passivPreteritum: "skämtades",
    translation: "يمزح / يُداعب",
    phonetic: "/ˈʃɛmta/",
    group: "1",
    level: "B1",
    category: "kommunikation",
    imageUrl: IMG.laugh,
    notes: "'Du skämtar!' = إنت بتمزح! أو لا يُعقل! 'skämta med' = يمزح مع شخص.",
    examples: [
      { sv: "Du skämtar väl?", ar: "إنت بتمزح، أليس كذلك؟" },
      { sv: "Han skämtade med sina kollegor.", ar: "مازح زملاءه في العمل." },
      { sv: "Skämta inte om sådant!", ar: "لا تمزح في مثل هذه الأمور!" },
    ],
    quizSentences: [
      { form: "presens", sentence: "Han ___ alltid på möten.", answer: "skämtar", translation: "هو يمزح دائماً في الاجتماعات." },
      { form: "preteritum", sentence: "Vi ___ hela kvällen.", answer: "skämtade", translation: "مزحنا طوال المساء." },
      { form: "imperativ", sentence: "___ lite, livet är för kort!", answer: "Skämta", translation: "امزح قليلاً، الحياة قصيرة جداً!" },
    ],
  },
  {
    infinitiv: "acceptera",
    presens: "accepterar",
    preteritum: "accepterade",
    supinum: "accepterat",
    imperativ: "acceptera",
    futurum: "ska acceptera",
    presensParticip: "accepterande",
    perfektParticip: "accepterad",
    passivPresens: "accepteras",
    passivPreteritum: "accepterades",
    translation: "يقبل / يتقبّل",
    phonetic: "/aksɛpˈteːra/",
    group: "1",
    level: "A2",
    category: "social",
    imageUrl: IMG.social,
    notes: "يُستخدم للقبول والموافقة. يختلف عن 'godkänna' (يُوافق رسمياً).",
    examples: [
      { sv: "Jag accepterar ditt erbjudande.", ar: "أقبل عرضك." },
      { sv: "Hon accepterade situationen.", ar: "قبلت الوضع وتقبّلته." },
      { sv: "Acceptera inte sådant beteende!", ar: "لا تتقبّل مثل هذا السلوك!" },
    ],
    quizSentences: [
      { form: "presens", sentence: "Han ___ inte kreditkort.", answer: "accepterar", translation: "هو لا يقبل بطاقات الائتمان." },
      { form: "preteritum", sentence: "Vi ___ villkoren i kontraktet.", answer: "accepterade", translation: "قبلنا شروط العقد." },
      { form: "imperativ", sentence: "___ dig för den du är!", answer: "Acceptera", translation: "اقبل نفسك كما أنت!" },
    ],
  },
  {
    infinitiv: "tvinga",
    presens: "tvingar",
    preteritum: "tvingade",
    supinum: "tvingat",
    imperativ: "tvinga",
    futurum: "ska tvinga",
    presensParticip: "tvingande",
    perfektParticip: "tvingad",
    passivPresens: "tvingas",
    passivPreteritum: "tvingades",
    translation: "يُجبر / يُرغم",
    phonetic: "/ˈtvɪŋa/",
    group: "1",
    level: "B1",
    category: "social",
    imageUrl: IMG.speak,
    notes: "'tvingas' (المبني للمجهول) = يُضطرّ. يُستخدم أيضاً: 'tvinga sig att' = يُجبر نفسه.",
    examples: [
      { sv: "Ingen kan tvinga dig.", ar: "لا أحد يستطيع إجبارك." },
      { sv: "Han tvingades lämna landet.", ar: "أُجبر على مغادرة البلاد." },
      { sv: "Tvinga inte barnen!", ar: "لا تُجبر الأطفال!" },
    ],
    quizSentences: [
      { form: "presens", sentence: "Hon ___ honom att städa.", answer: "tvingar", translation: "هي تُجبره على التنظيف." },
      { form: "preteritum", sentence: "De ___ oss att vänta.", answer: "tvingade", translation: "أجبرونا على الانتظار." },
      { form: "imperativ", sentence: "___ inte din åsikt på andra!", answer: "Tvinga", translation: "لا تفرض رأيك على الآخرين!" },
    ],
  },
  {
    infinitiv: "tappa",
    presens: "tappar",
    preteritum: "tappade",
    supinum: "tappat",
    imperativ: "tappa",
    futurum: "ska tappa",
    presensParticip: "tappande",
    perfektParticip: "tappad",
    passivPresens: "tappas",
    passivPreteritum: "tappades",
    translation: "يُسقط / يفقد (بغير قصد)",
    phonetic: "/ˈtɑpa/",
    group: "1",
    level: "A2",
    category: "vardagsliv",
    imageUrl: IMG.home,
    notes: "يختلف عن 'förlora' (يخسر في مسابقة). 'tappa' = يُسقط/يفقد شيئاً بغير قصد.",
    examples: [
      { sv: "Jag tappade min telefon.", ar: "أسقطت هاتفي." },
      { sv: "Hon tappade bort nyckeln.", ar: "فقدت المفتاح." },
      { sv: "Tappa inte hoppet!", ar: "لا تفقد الأمل!" },
    ],
    quizSentences: [
      { form: "presens", sentence: "Han ___ alltid sina saker.", answer: "tappar", translation: "هو يضيّع أغراضه دائماً." },
      { form: "preteritum", sentence: "Hon ___ plånboken på bussen.", answer: "tappade", translation: "فقدت محفظتها في الحافلة." },
      { form: "imperativ", sentence: "___ inte hoppet, det ordnar sig!", answer: "Tappa", translation: "لا تفقد الأمل، ستتحسّن الأمور!" },
    ],
  },
  {
    infinitiv: "plocka",
    presens: "plockar",
    preteritum: "plockade",
    supinum: "plockat",
    imperativ: "plocka",
    futurum: "ska plocka",
    presensParticip: "plockande",
    perfektParticip: "plockad",
    passivPresens: "plockas",
    passivPreteritum: "plockades",
    translation: "يلتقط / يقطف / يُزيل",
    phonetic: "/ˈplɔka/",
    group: "1",
    level: "A2",
    category: "natur",
    imageUrl: IMG.nature,
    notes: "يُستخدم لقطف الفاكهة والتوت، والتقاط الأشياء. 'plocka upp' = يلتقط من الأرض.",
    examples: [
      { sv: "Vi plockade svamp i skogen.", ar: "قطفنا الفطر في الغابة." },
      { sv: "Plocka upp det du tappade!", ar: "التقط ما أسقطته!" },
      { sv: "Hon plockade jordgubbar hela dan.", ar: "قطفت الفراولة طوال اليوم." },
    ],
    quizSentences: [
      { form: "presens", sentence: "Han ___ blåbär i skogen.", answer: "plockar", translation: "هو يقطف التوت الأزرق في الغابة." },
      { form: "preteritum", sentence: "Vi ___ ihop allt skräp.", answer: "plockade", translation: "جمعنا كل القمامة." },
      { form: "imperativ", sentence: "___ upp leksaken från golvet!", answer: "Plocka", translation: "التقط اللعبة من الأرض!" },
    ],
  },
  {
    infinitiv: "klättra",
    presens: "klättrar",
    preteritum: "klättrade",
    supinum: "klättrat",
    imperativ: "klättra",
    futurum: "ska klättra",
    presensParticip: "klättrande",
    perfektParticip: "klättrad",
    passivPresens: "klättras",
    passivPreteritum: "klättrandes",
    translation: "يتسلّق",
    phonetic: "/ˈklɛtra/",
    group: "1",
    level: "B1",
    category: "sport",
    imageUrl: IMG.sport,
    notes: "'klättra i träd' = يتسلّق الأشجار. 'klättring' = رياضة التسلّق.",
    examples: [
      { sv: "Barnen klättrade i trädet.", ar: "تسلّق الأطفال الشجرة." },
      { sv: "Han klättrar på klippor på helgen.", ar: "هو يتسلّق الصخور في عطلة نهاية الأسبوع." },
      { sv: "Klättra inte utan säkerhetsutrustning!", ar: "لا تتسلّق بدون معدّات الأمان!" },
    ],
    quizSentences: [
      { form: "presens", sentence: "Hon ___ inne på klättercentret.", answer: "klättrar", translation: "هي تتسلّق داخل مركز التسلّق." },
      { form: "preteritum", sentence: "Vi ___ till toppen av berget.", answer: "klättrade", translation: "تسلّقنا حتى قمة الجبل." },
      { form: "imperativ", sentence: "___ försiktigt, det är halt!", answer: "Klättra", translation: "تسلّق بحذر، الأرض زلقة!" },
    ],
  },
  {
    infinitiv: "låsa",
    presens: "låsar",
    preteritum: "låste",
    supinum: "låst",
    imperativ: "lås",
    futurum: "ska låsa",
    presensParticip: "låsande",
    perfektParticip: "låst",
    passivPresens: "låses",
    passivPreteritum: "låstes",
    translation: "يقفل / يُغلق بالمفتاح",
    phonetic: "/ˈloːsa/",
    group: "2b",
    level: "A2",
    category: "hem",
    imageUrl: IMG.home,
    notes: "مجموعة 2b: الماضي بـ -te. 'låsa in' = يحبس. 'låsa upp' = يفتح القفل.",
    examples: [
      { sv: "Kom ihåg att låsa dörren!", ar: "لا تنسَ إقفال الباب!" },
      { sv: "Han låste cykeln vid stationen.", ar: "أقفل دراجته عند المحطة." },
      { sv: "Lås inte in dig själv!", ar: "لا تحبس نفسك!" },
    ],
    quizSentences: [
      { form: "presens", sentence: "Hon ___ alltid bilen.", answer: "låsar", translation: "هي دائماً تقفل السيارة." },
      { form: "preteritum", sentence: "Vi ___ huset och reste.", answer: "låste", translation: "أقفلنا المنزل وسافرنا." },
      { form: "imperativ", sentence: "___ dörren när du går!", answer: "Lås", translation: "أقفل الباب عندما تذهب!" },
    ],
  },
  {
    infinitiv: "vägra",
    presens: "vägrar",
    preteritum: "vägrade",
    supinum: "vägrat",
    imperativ: "vägra",
    futurum: "ska vägra",
    presensParticip: "vägrande",
    perfektParticip: "vägrad",
    passivPresens: "vägras",
    passivPreteritum: "vägrade",
    translation: "يرفض / يأبى",
    phonetic: "/ˈvɛːɡra/",
    group: "1",
    level: "B1",
    category: "social",
    imageUrl: IMG.speak,
    notes: "أقوى من 'neka'. يُستخدم للرفض القاطع.",
    examples: [
      { sv: "Han vägrar äta grönsaker.", ar: "هو يرفض أكل الخضروات." },
      { sv: "Hon vägrade skriva under.", ar: "رفضت التوقيع." },
      { sv: "Vägra inte ta emot hjälp!", ar: "لا ترفض قبول المساعدة!" },
    ],
    quizSentences: [
      { form: "presens", sentence: "Hon ___ att ge upp.", answer: "vägrar", translation: "هي ترفض الاستسلام." },
      { form: "preteritum", sentence: "Han ___ att betala boten.", answer: "vägrade", translation: "رفض دفع الغرامة." },
      { form: "imperativ", sentence: "___ inte om de behandlar dig fel!", answer: "Vägra", translation: "ارفض إذا عاملوك بشكل سيئ!" },
    ],
  },

  // ══════════════════════════════════════════════════════════════════
  // GRUPP 2a — -er verbs, past -de
  // ══════════════════════════════════════════════════════════════════
  {
    infinitiv: "köra",
    presens: "kör",
    preteritum: "körde",
    supinum: "kört",
    imperativ: "kör",
    futurum: "ska köra",
    presensParticip: "körande",
    perfektParticip: "körd",
    passivPresens: "körs",
    passivPreteritum: "kördes",
    translation: "يقود (سيارة) / يُشغّل",
    phonetic: "/ˈɕøːra/",
    group: "2a",
    level: "A2",
    category: "transport",
    imageUrl: IMG.drive,
    notes: "من أهم أفعال التنقّل. 'köra bil' = يقود سيارة. 'köra fast' = يُوقِف الشرطةُ سائقاً.",
    examples: [
      { sv: "Kan du köra mig hem?", ar: "هل يمكنك إيصالي إلى البيت؟" },
      { sv: "Hon körde för fort.", ar: "قادت بسرعة زائدة." },
      { sv: "Kör försiktigt i regnet!", ar: "قد بحذر في المطر!" },
    ],
    quizSentences: [
      { form: "presens", sentence: "Han ___ till jobbet varje dag.", answer: "kör", translation: "هو يقود إلى العمل كل يوم." },
      { form: "preteritum", sentence: "Vi ___ genom hela Sverige.", answer: "körde", translation: "قدنا عبر السويد كلها." },
      { form: "imperativ", sentence: "___ till höger här!", answer: "Kör", translation: "اتجه يميناً هنا!" },
    ],
  },
  {
    infinitiv: "hyra",
    presens: "hyr",
    preteritum: "hyrde",
    supinum: "hyrt",
    imperativ: "hyr",
    futurum: "ska hyra",
    presensParticip: "hyrande",
    perfektParticip: "hyrd",
    passivPresens: "hyrs",
    passivPreteritum: "hyrdes",
    translation: "يستأجر / يُؤجّر",
    phonetic: "/ˈhyːra/",
    group: "2a",
    level: "A2",
    category: "boende",
    imageUrl: IMG.home,
    notes: "'hyra ut' = يُؤجّر لشخص. 'hyra in' = يستأجر (خدمة). 'hyra' = الإيجار (اسم أيضاً).",
    examples: [
      { sv: "Vi hyr en lägenhet i Stockholm.", ar: "نستأجر شقة في ستوكهولم." },
      { sv: "Han hyrde en bil för semestern.", ar: "استأجر سيارة للإجازة." },
      { sv: "Hyr inte dyrt om du kan bo billigare!", ar: "لا تستأجر بثمن مرتفع إذا كان بإمكانك العيش بأقل!" },
    ],
    quizSentences: [
      { form: "presens", sentence: "Hon ___ ut sitt rum på sommaren.", answer: "hyr", translation: "هي تُؤجّر غرفتها في الصيف." },
      { form: "preteritum", sentence: "Vi ___ stuga i fjällen.", answer: "hyrde", translation: "استأجرنا كوخاً في الجبال." },
      { form: "imperativ", sentence: "___ cykel istället för bil!", answer: "Hyr", translation: "استأجر دراجة بدلاً من سيارة!" },
    ],
  },
  {
    infinitiv: "bygga",
    presens: "bygger",
    preteritum: "byggde",
    supinum: "byggt",
    imperativ: "bygg",
    futurum: "ska bygga",
    presensParticip: "byggande",
    perfektParticip: "byggd",
    passivPresens: "byggs",
    passivPreteritum: "byggdes",
    translation: "يبني / يُشيّد",
    phonetic: "/ˈbʏɡa/",
    group: "2a",
    level: "A2",
    category: "konstruktion",
    imageUrl: IMG.build,
    notes: "يُستخدم للبناء المادي وأيضاً المجازي: 'bygga förtroende' = يبني الثقة.",
    examples: [
      { sv: "De byggde ett nytt hus.", ar: "بنوا منزلاً جديداً." },
      { sv: "Sverige bygger mycket nu.", ar: "السويد تبني كثيراً الآن." },
      { sv: "Bygg inte på sumpmark!", ar: "لا تبنِ على أرض مستنقعية!" },
    ],
    quizSentences: [
      { form: "presens", sentence: "Kommunen ___ nya bostäder.", answer: "bygger", translation: "البلدية تبني مساكن جديدة." },
      { form: "preteritum", sentence: "Vi ___ ett staket runt trädgården.", answer: "byggde", translation: "بنينا سياجاً حول الحديقة." },
      { form: "imperativ", sentence: "___ ihop möblerna enligt instruktionen!", answer: "Bygg", translation: "اِبنِ الأثاث وفق التعليمات!" },
    ],
  },
  {
    infinitiv: "drömma",
    presens: "drömmer",
    preteritum: "drömde",
    supinum: "drömt",
    imperativ: "drömm",
    futurum: "ska drömma",
    presensParticip: "drömmande",
    perfektParticip: "drömd",
    passivPresens: "drömms",
    passivPreteritum: "drömdes",
    translation: "يحلم",
    phonetic: "/ˈdrœma/",
    group: "2a",
    level: "A2",
    category: "känsla",
    imageUrl: IMG.dream,
    notes: "يُستخدم للحلم أثناء النوم وللأحلام والطموحات. 'drömma om' = يحلم بـ.",
    examples: [
      { sv: "Jag drömde om dig i natt.", ar: "حلمت بك الليلة." },
      { sv: "Hon drömmer om att bli läkare.", ar: "هي تحلم بأن تصبح طبيبة." },
      { sv: "Drömm stort!", ar: "احلم بكبر!" },
    ],
    quizSentences: [
      { form: "presens", sentence: "Han ___ om att resa runt världen.", answer: "drömmer", translation: "هو يحلم بالسفر حول العالم." },
      { form: "preteritum", sentence: "Jag ___ att jag flög.", answer: "drömde", translation: "حلمت أنني كنت أطير." },
      { form: "imperativ", sentence: "___ om det bästa!", answer: "Drömm", translation: "احلم بالأفضل!" },
    ],
  },
  {
    infinitiv: "besöka",
    presens: "besöker",
    preteritum: "besökte",
    supinum: "besökt",
    imperativ: "besök",
    futurum: "ska besöka",
    presensParticip: "besökande",
    perfektParticip: "besökt",
    passivPresens: "besöks",
    passivPreteritum: "besöktes",
    translation: "يزور",
    phonetic: "/bɛˈsøːka/",
    group: "2b",
    level: "A2",
    category: "social",
    imageUrl: IMG.social,
    notes: "مجموعة 2b. 'besök' = زيارة (اسم). يختلف عن 'hälsa på' (يعود/يزور بشكل غير رسمي).",
    examples: [
      { sv: "Vi besöker farmor på söndag.", ar: "سنزور جدتنا يوم الأحد." },
      { sv: "Hon besökte museet i Göteborg.", ar: "زارت المتحف في غوتنبرغ." },
      { sv: "Besök oss när du kan!", ar: "زرنا عندما تستطيع!" },
    ],
    quizSentences: [
      { form: "presens", sentence: "Han ___ sina föräldrar varje helg.", answer: "besöker", translation: "هو يزور والديه كل عطلة نهاية أسبوع." },
      { form: "preteritum", sentence: "Vi ___ Stockholm förra sommaren.", answer: "besökte", translation: "زرنا ستوكهولم الصيف الماضي." },
      { form: "imperativ", sentence: "___ oss när du är i stan!", answer: "Besök", translation: "زرنا عندما تكون في المدينة!" },
    ],
  },

  // ══════════════════════════════════════════════════════════════════
  // GRUPP 2b — -er verbs, past -te
  // ══════════════════════════════════════════════════════════════════
  {
    infinitiv: "mäta",
    presens: "mäter",
    preteritum: "mätte",
    supinum: "mätt",
    imperativ: "mät",
    futurum: "ska mäta",
    presensParticip: "mätande",
    perfektParticip: "mätt",
    passivPresens: "mäts",
    passivPreteritum: "mättes",
    translation: "يقيس",
    phonetic: "/ˈmɛːta/",
    group: "2b",
    level: "B1",
    category: "matematik",
    imageUrl: IMG.build,
    notes: "يُستخدم لقياس الأبعاد والكميات. 'mätare' = جهاز القياس. 'mäta upp' = يقيس بدقة.",
    examples: [
      { sv: "Mät fönstret innan du köper gardiner.", ar: "قِس النافذة قبل شراء الستائر." },
      { sv: "Hon mätte sin feber.", ar: "قاست حرارتها." },
      { sv: "Vi mätte upp rummet.", ar: "قسنا الغرفة." },
    ],
    quizSentences: [
      { form: "presens", sentence: "Han ___ temperaturen varje morgon.", answer: "mäter", translation: "هو يقيس درجة الحرارة كل صباح." },
      { form: "preteritum", sentence: "Vi ___ hur lång tavlan var.", answer: "mätte", translation: "قسنا طول اللوحة." },
      { form: "imperativ", sentence: "___ två gånger, skär en gång!", answer: "Mät", translation: "قِس مرتين، اقطع مرة!" },
    ],
  },
  {
    infinitiv: "försöka",
    presens: "försöker",
    preteritum: "försökte",
    supinum: "försökt",
    imperativ: "försök",
    futurum: "ska försöka",
    presensParticip: "försökande",
    perfektParticip: "försökt",
    passivPresens: "försöks",
    passivPreteritum: "försöktes",
    translation: "يُحاول",
    phonetic: "/fœrˈsøːka/",
    group: "2b",
    level: "A1",
    category: "handling",
    imageUrl: IMG.sport,
    notes: "من أهم الأفعال للتعبير عن المحاولة. 'försök igen!' = حاول مرة أخرى!",
    examples: [
      { sv: "Jag försöker lära mig svenska.", ar: "أنا أحاول تعلّم السويدية." },
      { sv: "Hon försökte men misslyckades.", ar: "حاولت لكنها فشلت." },
      { sv: "Försök inte lura mig!", ar: "لا تحاول خداعي!" },
    ],
    quizSentences: [
      { form: "presens", sentence: "Han ___ varje dag att förstå.", answer: "försöker", translation: "هو يحاول كل يوم أن يفهم." },
      { form: "preteritum", sentence: "Vi ___ tre gånger.", answer: "försökte", translation: "حاولنا ثلاث مرات." },
      { form: "imperativ", sentence: "___ igen, du klarar det!", answer: "Försök", translation: "حاول مرة أخرى، ستنجح!" },
    ],
  },
  {
    infinitiv: "kyssa",
    presens: "kysser",
    preteritum: "kysste",
    supinum: "kysst",
    imperativ: "kyss",
    futurum: "ska kyssa",
    presensParticip: "kyssande",
    perfektParticip: "kysst",
    passivPresens: "kysses",
    passivPreteritum: "kysste",
    translation: "يُقبّل",
    phonetic: "/ˈɕʏsa/",
    group: "2b",
    level: "A2",
    category: "social",
    imageUrl: IMG.love,
    notes: "مجموعة 2b. في السويد التحية بالتقبيل على الخد أقل شيوعاً مقارنة بدول أخرى.",
    examples: [
      { sv: "Han kysste henne på kinden.", ar: "قبّلها على خدّها." },
      { sv: "Mamma kysser barnet godnatt.", ar: "الأم تُقبّل طفلها مساء الخير." },
      { sv: "Kyss mig!", ar: "قبّلني!" },
    ],
    quizSentences: [
      { form: "presens", sentence: "Hon ___ sin hund varje dag.", answer: "kysser", translation: "هي تُقبّل كلبها كل يوم." },
      { form: "preteritum", sentence: "Han ___ henne vid bröllopet.", answer: "kysste", translation: "قبّلها في حفل الزفاف." },
      { form: "imperativ", sentence: "___ barnet god natt!", answer: "Kyss", translation: "قبّل الطفل مساء الخير!" },
    ],
  },

  // ══════════════════════════════════════════════════════════════════
  // OREGELBUNDNA — Irregular verbs
  // ══════════════════════════════════════════════════════════════════
  {
    infinitiv: "le",
    presens: "ler",
    preteritum: "log",
    supinum: "lett",
    imperativ: "le",
    futurum: "ska le",
    presensParticip: "leende",
    perfektParticip: "lett",
    passivPresens: "les",
    passivPreteritum: "logs",
    translation: "يبتسم",
    phonetic: "/leː/",
    group: "oregelbundet",
    level: "A1",
    category: "känsla",
    imageUrl: IMG.laugh,
    notes: "فعل غير منتظم قصير جداً. الماضي 'log' مختلف تماماً. 'leende' = ابتسامة (اسم أيضاً).",
    examples: [
      { sv: "Hon ler alltid mot kunderna.", ar: "هي تبتسم دائماً للعملاء." },
      { sv: "Han log och tackade.", ar: "ابتسم وشكر." },
      { sv: "Le lite, det kostar inget!", ar: "ابتسم قليلاً، لا يُكلّف شيئاً!" },
    ],
    quizSentences: [
      { form: "presens", sentence: "Han ___ när han ser henne.", answer: "ler", translation: "هو يبتسم عندما يراها." },
      { form: "preteritum", sentence: "Barnet ___ mot sin mamma.", answer: "log", translation: "ابتسم الطفل لأمه." },
      { form: "imperativ", sentence: "___ för kameran!", answer: "Le", translation: "ابتسم أمام الكاميرا!" },
    ],
  },
  {
    infinitiv: "gråta",
    presens: "gråter",
    preteritum: "grät",
    supinum: "gråtit",
    imperativ: "gråt",
    futurum: "ska gråta",
    presensParticip: "gråtande",
    perfektParticip: "gråtit",
    passivPresens: "gråtes",
    passivPreteritum: "grät",
    translation: "يبكي",
    phonetic: "/ˈɡroːta/",
    group: "oregelbundet",
    level: "A2",
    category: "känsla",
    imageUrl: IMG.emotion,
    notes: "فعل غير منتظم. الماضي 'grät' مختلف عن المضارع. 'gråta av glädje' = يبكي فرحاً.",
    examples: [
      { sv: "Hon grät när hon hörde nyheten.", ar: "بكت عندما سمعت الخبر." },
      { sv: "Barnet gråter hela natten.", ar: "الطفل يبكي طوال الليل." },
      { sv: "Det är okej att gråta.", ar: "لا بأس في البكاء." },
    ],
    quizSentences: [
      { form: "presens", sentence: "Han ___ av lycka.", answer: "gråter", translation: "هو يبكي من السعادة." },
      { form: "preteritum", sentence: "Hon ___ hela vägen hem.", answer: "grät", translation: "بكت طوال الطريق إلى البيت." },
      { form: "imperativ", sentence: "___ inte, allt löser sig!", answer: "Gråt", translation: "لا تبكِ، كل شيء سيُحلّ!" },
    ],
  },
  {
    infinitiv: "bjuda",
    presens: "bjuder",
    preteritum: "bjöd",
    supinum: "bjudit",
    imperativ: "bjud",
    futurum: "ska bjuda",
    presensParticip: "bjudande",
    perfektParticip: "bjuden",
    passivPresens: "bjuds",
    passivPreteritum: "bjöds",
    translation: "يدعو / يُقدّم / يُكرم",
    phonetic: "/ˈbjʉːda/",
    group: "oregelbundet",
    level: "A2",
    category: "social",
    imageUrl: IMG.social,
    notes: "فعل متعدد المعاني: 'bjuda på' = يُكرم بـ (يدفع الحساب)، 'bjuda in' = يدعو، 'bjuda hem' = يدعو للبيت.",
    examples: [
      { sv: "Jag bjuder på kaffet!", ar: "أنا أدفع ثمن القهوة!" },
      { sv: "Hon bjöd sina vänner på middag.", ar: "دعت أصدقاءها على العشاء." },
      { sv: "Bjud hit dem på lördag!", answer: "ادعُهم للمجيء هنا يوم السبت!" },
    ],
    quizSentences: [
      { form: "presens", sentence: "Han ___ alltid på fikabrödet.", answer: "bjuder", translation: "هو دائماً يُكرم بمعجنات القهوة." },
      { form: "preteritum", sentence: "Vi ___ grannarna på middag.", answer: "bjöd", translation: "دعونا الجيران على العشاء." },
      { form: "imperativ", sentence: "___ på en kaffe, du är rik!", answer: "Bjud", translation: "أكرمنا بقهوة، أنت ثري!" },
    ],
  },
  {
    infinitiv: "stryka",
    presens: "stryker",
    preteritum: "strök",
    supinum: "strukit",
    imperativ: "stryk",
    futurum: "ska stryka",
    presensParticip: "strykande",
    perfektParticip: "struken",
    passivPresens: "stryks",
    passivPreteritum: "ströks",
    translation: "يكوي (الملابس) / يُمرّر يده",
    phonetic: "/ˈstrʏka/",
    group: "oregelbundet",
    level: "B1",
    category: "hem",
    imageUrl: IMG.home,
    notes: "فعل غير منتظم. 'stryka kläder' = يكوي الملابس. 'stryka under' = يسطّر (يُسلّط خطاً).",
    examples: [
      { sv: "Stryker du dina skjortor?", ar: "هل تكوي قمصانك؟" },
      { sv: "Hon strök sin kjol.", ar: "كوت تنّورتها." },
      { sv: "Stryk under det viktiga!", ar: "سطّر على المهم!" },
    ],
    quizSentences: [
      { form: "presens", sentence: "Han ___ aldrig sina kläder.", answer: "stryker", translation: "هو لا يكوي ملابسه أبداً." },
      { form: "preteritum", sentence: "Hon ___ allt inför mötet.", answer: "strök", translation: "كوت كل شيء قبل الاجتماع." },
      { form: "imperativ", sentence: "___ skjortan, den är skrynklig!", answer: "Stryk", translation: "اكوِ القميص، إنه مجعّد!" },
    ],
  },
  {
    infinitiv: "fortsätta",
    presens: "fortsätter",
    preteritum: "fortsatte",
    supinum: "fortsatt",
    imperativ: "fortsätt",
    futurum: "ska fortsätta",
    presensParticip: "fortsättande",
    perfektParticip: "fortsatt",
    passivPresens: "fortsätts",
    passivPreteritum: "fortsattes",
    translation: "يُكمل / يستمرّ",
    phonetic: "/fɔrtˈsɛta/",
    group: "oregelbundet",
    level: "A2",
    category: "handling",
    imageUrl: IMG.sport,
    notes: "فعل غير منتظم. 'fortsätt så!' = هكذا أكمل! (تشجيع). 'fortsättning' = تتمّة.",
    examples: [
      { sv: "Fortsätt jobba, det går bra!", ar: "استمرّ في العمل، الأمور تسير على ما يرام!" },
      { sv: "Vi fortsatte trots svårigheterna.", ar: "واصلنا رغم الصعوبات." },
      { sv: "Filmen fortsätter nästa vecka.", ar: "الفيلم يتواصل الأسبوع القادم." },
    ],
    quizSentences: [
      { form: "presens", sentence: "Han ___ att studera trots allt.", answer: "fortsätter", translation: "هو يواصل الدراسة رغم كل شيء." },
      { form: "preteritum", sentence: "Vi ___ promenaden efter pausen.", answer: "fortsatte", translation: "واصلنا المشي بعد الاستراحة." },
      { form: "imperativ", sentence: "___ inte ge upp!", answer: "Fortsätt", translation: "لا تستسلم، استمرّ!" },
    ],
  },
  {
    infinitiv: "oroa sig",
    presens: "oroar sig",
    preteritum: "oroade sig",
    supinum: "oroat sig",
    imperativ: "oroa dig",
    futurum: "ska oroa sig",
    presensParticip: "oroande",
    perfektParticip: "oroad",
    passivPresens: "oroar sig",
    passivPreteritum: "oroade sig",
    translation: "يقلق / يخشى",
    phonetic: "/ˈuːrʊa sɛj/",
    group: "1",
    level: "B1",
    category: "känsla",
    imageUrl: IMG.emotion,
    notes: "فعل انعكاسي (reflexivt verb). 'oroa sig för' = يقلق بشأن. 'oroande' = مُقلق (صفة).",
    examples: [
      { sv: "Oroa dig inte, det ordnar sig.", ar: "لا تقلق، ستتحسّن الأمور." },
      { sv: "Hon oroar sig för sin hälsa.", ar: "هي تقلق على صحتها." },
      { sv: "Föräldrarna oroade sig hela natten.", ar: "قلق الوالدان طوال الليل." },
    ],
    quizSentences: [
      { form: "presens", sentence: "Han ___ mycket om jobbet.", answer: "oroar sig", translation: "هو يقلق كثيراً بشأن العمل." },
      { form: "preteritum", sentence: "Vi ___ men allt gick bra.", answer: "oroade oss", translation: "قلقنا لكن كل شيء سار بخير." },
      { form: "imperativ", sentence: "___ inte, allt löser sig!", answer: "Oroa dig", translation: "لا تقلق، كل شيء سيُحلّ!" },
    ],
  },
];

async function seedVerbsExtra2() {
  console.log("🌱 Adding extra verbs (batch 2)...\n");
  let added = 0;
  let skipped = 0;

  for (const verb of extraVerbs2) {
    try {
      await db.insert(verbsTable).values(verb as any);
      console.log(`✅ ${verb.infinitiv} — ${verb.translation}`);
      added++;
    } catch (err: any) {
      if (err?.code === "23505" || err?.message?.includes("unique")) {
        console.log(`⏭️  ${verb.infinitiv} — already exists, skipped`);
        skipped++;
      } else {
        console.error(`❌ ${verb.infinitiv}: ${err.message}`);
      }
    }
  }

  console.log(`\n🎉 Added ${added} verbs (${skipped} skipped as duplicates)!`);
  process.exit(0);
}

seedVerbsExtra2().catch((e) => {
  console.error(e);
  process.exit(1);
});
