import { db, verbsTable } from "@workspace/db";
import { sql } from "drizzle-orm";

// Extra verbs — inserts without deleting existing data

const IMG = {
  speak:    "https://images.pexels.com/photos/7516363/pexels-photo-7516363.jpeg?auto=compress&cs=tinysrgb&w=612&h=408&dpr=1",
  work:     "https://media.gettyimages.com/id/2198968434/photo/students-using-laptop-and-smartphone-in-malmo-sweden.jpg?s=612x612&w=0&k=20&c=CabGwvl3Hs5Mx7_rk0o7weZFg5t4KeAIzeUBNWIUED8=",
  food:     "https://media.gettyimages.com/id/2215023550/photo/traditional-swedish-meatballs-with-mashed-potatoes-pickles-and-cranberry-sauce.jpg?s=612x612&w=0&k=20&c=ZrzruuV67aiz_Eb-Howv1tBi1jw3yp-IvVGYl1MNzn0=",
  walk:     "https://i0.wp.com/atravelingfairy.com/wp-content/uploads/2022/11/DSC04547.jpg?w=1100&ssl=1",
  nature:   "https://images.pexels.com/photos/2422461/pexels-photo-2422461.jpeg?auto=compress&cs=tinysrgb&w=612&h=408&dpr=1",
  family:   "https://media.gettyimages.com/id/1300189216/photo/happy-family-eating-breakfast-seen-through-doorway-of-kitchen-at-home.jpg?s=612x612&w=0&k=20&c=tpaZ_wI_lBB7q4LN-GkHcQhkVleWUSO4qfb8_IxLeyE=",
  health:   "https://media.gettyimages.com/id/731741979/photo/doctor-walking-through-hospital-corridor.jpg?s=612x612&w=0&k=20&c=94a50kc59V322iYjCtqtAM2f6GmIW7T_hiDezvf5TsE=",
  school:   "https://media.gettyimages.com/id/1667940273/photo/portrait-of-smiling-female-student-with-friend-in-university.jpg?s=612x612&w=0&k=20&c=ePwPB-IfQ5SEUEQQMiN6LVIDDK6wTsAjHVH0b9Yy_5A=",
  city:     "https://thumbs.dreamstime.com/b/bright-interior-swedish-supermarket-food-products-discount-signs-shopping-carts-aisle-390370221.jpg",
  sleep:    "https://images.pexels.com/photos/3771069/pexels-photo-3771069.jpeg?auto=compress&cs=tinysrgb&w=612&h=408&dpr=1",
  travel:   "https://media.gettyimages.com/id/1346700045/photo/stockholm-sweden-aerial-view.jpg?s=612x612&w=0&k=20&c=1nBJIdZcIuBDnO2bZCdSPXFtFdj8V5Hx2FqxAaVlFk0=",
  sport:    "https://images.pexels.com/photos/3621104/pexels-photo-3621104.jpeg?auto=compress&cs=tinysrgb&w=612&h=408&dpr=1",
  tech:     "https://media.gettyimages.com/id/1486196733/photo/developer-coding-on-laptop.jpg?s=612x612&w=0&k=20&c=HkXR0AwGMHH6GFjVg6D-0XeIlYh5vBRBx9A-kV2rRFc=",
  shopping: "https://images.pexels.com/photos/5632388/pexels-photo-5632388.jpeg?auto=compress&cs=tinysrgb&w=612&h=408&dpr=1",
  cooking:  "https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=612&h=408&dpr=1",
  social:   "https://images.pexels.com/photos/1320701/pexels-photo-1320701.jpeg?auto=compress&cs=tinysrgb&w=612&h=408&dpr=1",
  emotion:  "https://images.pexels.com/photos/3807571/pexels-photo-3807571.jpeg?auto=compress&cs=tinysrgb&w=612&h=408&dpr=1",
  home:     "https://images.pexels.com/photos/1080721/pexels-photo-1080721.jpeg?auto=compress&cs=tinysrgb&w=612&h=408&dpr=1",
  music:    "https://images.pexels.com/photos/4088009/pexels-photo-4088009.jpeg?auto=compress&cs=tinysrgb&w=612&h=408&dpr=1",
  money:    "https://images.pexels.com/photos/4386373/pexels-photo-4386373.jpeg?auto=compress&cs=tinysrgb&w=612&h=408&dpr=1",
};

const extraVerbs = [
  // ══════════════════════════════════════════════════════════════════
  // GRUPP 1 — -ar verbs
  // ══════════════════════════════════════════════════════════════════
  {
    infinitiv: "beställa",
    presens: "beställer",
    preteritum: "beställde",
    supinum: "beställt",
    imperativ: "beställ",
    futurum: "ska beställa",
    presensParticip: "beställande",
    perfektParticip: "beställd",
    passivPresens: "beställs",
    passivPreteritum: "beställdes",
    translation: "يطلب (طلباً / أمراً)",
    phonetic: "/bɛˈɛtːəla/",
    group: "2a",
    level: "A2",
    category: "handel",
    imageUrl: IMG.shopping,
    notes: "يُستخدم لطلب الطعام أو البضاعة. مجموعة 2a: ينتهي الماضي بـ -de.",
    examples: [
      { sv: "Jag vill beställa pizza.", ar: "أريد طلب بيتزا." },
      { sv: "Hon beställde en ny bok online.", ar: "طلبت كتاباً جديداً على الإنترنت." },
      { sv: "Beställ det nu, annars slutar det!", ar: "اطلبه الآن وإلا ينتهي!" },
    ],
    quizSentences: [
      { form: "presens", sentence: "Jag ___ mat från restaurangen.", answer: "beställer", translation: "أنا أطلب طعاماً من المطعم." },
      { form: "preteritum", sentence: "Vi ___ bord till fredag.", answer: "beställde", translation: "حجزنا طاولة ليوم الجمعة." },
      { form: "imperativ", sentence: "___ den nu om du vill ha den!", answer: "Beställ", translation: "اطلبها الآن إذا أردتها!" },
    ],
  },
  {
    infinitiv: "dela",
    presens: "delar",
    preteritum: "delade",
    supinum: "delat",
    imperativ: "dela",
    futurum: "ska dela",
    presensParticip: "delande",
    perfektParticip: "delad",
    passivPresens: "delas",
    passivPreteritum: "delades",
    translation: "يُقسّم / يُشارك",
    phonetic: "/ˈdeːla/",
    group: "1",
    level: "A1",
    category: "social",
    imageUrl: IMG.social,
    notes: "يُستخدم لمشاركة الأشياء أو تقسيمها. 'dela med sig' = يُشارك مع الآخرين.",
    examples: [
      { sv: "Kan du dela det med mig?", ar: "هل يمكنك مشاركتي إياه؟" },
      { sv: "Vi delade räkningen.", ar: "قسّمنا الحساب." },
      { sv: "Dela inte lösenordet med någon!", ar: "لا تشارك كلمة المرور مع أحد!" },
    ],
    quizSentences: [
      { form: "presens", sentence: "Han ___ alltid sin mat med andra.", answer: "delar", translation: "هو دائماً يُشارك طعامه مع الآخرين." },
      { form: "preteritum", sentence: "Vi ___ på kakan.", answer: "delade", translation: "قسّمنا الكعكة." },
      { form: "imperativ", sentence: "___ inte allt på sociala medier!", answer: "Dela", translation: "لا تُشارك كل شيء على وسائل التواصل الاجتماعي!" },
    ],
  },
  {
    infinitiv: "diskutera",
    presens: "diskuterar",
    preteritum: "diskuterade",
    supinum: "diskuterat",
    imperativ: "diskutera",
    futurum: "ska diskutera",
    presensParticip: "diskuterande",
    perfektParticip: "diskuterad",
    passivPresens: "diskuteras",
    passivPreteritum: "diskuterades",
    translation: "يناقش",
    phonetic: "/dɪskʉˈteːra/",
    group: "1",
    level: "B1",
    category: "kommunikation",
    imageUrl: IMG.speak,
    notes: "فعل مهم في السياق الأكاديمي والمهني.",
    examples: [
      { sv: "Vi diskuterade ämnet i en timme.", ar: "ناقشنا الموضوع لمدة ساعة." },
      { sv: "Diskutera problemet med din chef.", ar: "ناقش المشكلة مع مديرك." },
      { sv: "De diskuterar alltid politik.", ar: "يناقشون السياسة دائماً." },
    ],
    quizSentences: [
      { form: "presens", sentence: "Vi ___ planen för projektet.", answer: "diskuterar", translation: "نحن نناقش خطة المشروع." },
      { form: "preteritum", sentence: "De ___ problemet igår.", answer: "diskuterade", translation: "ناقشوا المشكلة أمس." },
      { form: "imperativ", sentence: "___ det med teamet!", answer: "Diskutera", translation: "ناقشه مع الفريق!" },
    ],
  },
  {
    infinitiv: "flytta",
    presens: "flyttar",
    preteritum: "flyttade",
    supinum: "flyttat",
    imperativ: "flytta",
    futurum: "ska flytta",
    presensParticip: "flyttande",
    perfektParticip: "flyttad",
    passivPresens: "flyttas",
    passivPreteritum: "flyttades",
    translation: "ينتقل / يتحرك (مكان السكن)",
    phonetic: "/ˈflʏtːa/",
    group: "1",
    level: "A2",
    category: "boende",
    imageUrl: IMG.home,
    notes: "يُستخدم للتعبير عن الانتقال من مكان إلى آخر. 'flytta in' = يسكن. 'flytta ut' = يغادر.",
    examples: [
      { sv: "Vi ska flytta till Göteborg nästa år.", ar: "سننتقل إلى يوتبوري السنة القادمة." },
      { sv: "Hon har precis flyttat in.", ar: "لقد انتقلت للتو." },
      { sv: "Flytta inte utan att berätta!", ar: "لا تنتقل دون أن تُخبرني!" },
    ],
    quizSentences: [
      { form: "presens", sentence: "Han ___ till en ny lägenhet i januari.", answer: "flyttar", translation: "هو ينتقل إلى شقة جديدة في يناير." },
      { form: "preteritum", sentence: "Vi ___ från Stockholm för tre år sedan.", answer: "flyttade", translation: "انتقلنا من ستوكهولم منذ ثلاث سنوات." },
      { form: "imperativ", sentence: "___ inte nu — vänta till sommaren!", answer: "Flytta", translation: "لا تنتقل الآن — انتظر حتى الصيف!" },
    ],
  },
  {
    infinitiv: "glömma",
    presens: "glömmer",
    preteritum: "glömde",
    supinum: "glömt",
    imperativ: "glöm",
    futurum: "ska glömma",
    presensParticip: "glömmande",
    perfektParticip: "glömd",
    passivPresens: "glömmas",
    passivPreteritum: "glömdes",
    translation: "ينسى",
    phonetic: "/ˈɡlœmːa/",
    group: "2b",
    level: "A1",
    category: "kognition",
    imageUrl: IMG.school,
    notes: "مجموعة 2b. 'Glöm det!' = انسَ الأمر! (تعبير شائع).",
    examples: [
      { sv: "Jag glömde mitt lösenord.", ar: "نسيتُ كلمة مروري." },
      { sv: "Glöm inte att stänga dörren!", ar: "لا تنسَ إغلاق الباب!" },
      { sv: "Han glömmer alltid sina nycklar.", ar: "هو دائماً ينسى مفاتيحه." },
    ],
    quizSentences: [
      { form: "presens", sentence: "Hon ___ alltid sin telefon hemma.", answer: "glömmer", translation: "هي دائماً تنسى هاتفها في المنزل." },
      { form: "preteritum", sentence: "Jag ___ att ringa dig.", answer: "glömde", translation: "نسيتُ أن أتصل بك." },
      { form: "imperativ", sentence: "___ inte läxan till imorgon!", answer: "Glöm", translation: "لا تنسَ الواجب لغد!" },
    ],
  },
  {
    infinitiv: "hälsa",
    presens: "hälsar",
    preteritum: "hälsade",
    supinum: "hälsat",
    imperativ: "hälsa",
    futurum: "ska hälsa",
    presensParticip: "hälsande",
    perfektParticip: "hälsad",
    passivPresens: "hälsas",
    passivPreteritum: "hälsades",
    translation: "يُحيّي / يسلّم",
    phonetic: "/ˈhɛlːsa/",
    group: "1",
    level: "A1",
    category: "social",
    imageUrl: IMG.social,
    notes: "يُستخدم للتحية. 'Hälsa på' = يزور. 'Hälsa till' = أبلغ تحياتي.",
    examples: [
      { sv: "Hälsa till din familj från mig!", ar: "أبلغ تحياتي لعائلتك!" },
      { sv: "Han hälsade på oss med ett leende.", ar: "حيّانا بابتسامة." },
      { sv: "Vi ska hälsa på morföräldrarna i helgen.", ar: "سنزور الأجداد في عطلة نهاية الأسبوع." },
    ],
    quizSentences: [
      { form: "presens", sentence: "Jag ___ på grannarna varje dag.", answer: "hälsar", translation: "أُحيّي الجيران كل يوم." },
      { form: "preteritum", sentence: "Vi ___ på dem när vi kom.", answer: "hälsade", translation: "حيّيناهم عندما وصلنا." },
      { form: "imperativ", sentence: "___ på din mamma från mig!", answer: "Hälsa", translation: "أبلغ تحياتي لأمك!" },
    ],
  },
  {
    infinitiv: "jobba",
    presens: "jobbar",
    preteritum: "jobbade",
    supinum: "jobbat",
    imperativ: "jobba",
    futurum: "ska jobba",
    presensParticip: "jobbande",
    perfektParticip: "jobbad",
    passivPresens: "jobbas",
    passivPreteritum: "jobbades",
    translation: "يعمل (لغة يومية)",
    phonetic: "/ˈjɔbːa/",
    group: "1",
    level: "A1",
    category: "arbete",
    imageUrl: IMG.work,
    notes: "نسخة يومية من 'arbeta'. أكثر شيوعاً في المحادثات العادية.",
    examples: [
      { sv: "Var jobbar du?", ar: "أين تعمل؟" },
      { sv: "Jag jobbade övertid igår.", ar: "عملتُ ساعات إضافية أمس." },
      { sv: "Hon jobbar hemifrån nu.", ar: "هي تعمل من المنزل الآن." },
    ],
    quizSentences: [
      { form: "presens", sentence: "Jag ___ som lärare i en skola.", answer: "jobbar", translation: "أنا أعمل كمعلم في مدرسة." },
      { form: "preteritum", sentence: "Han ___ natt-skiftet igår.", answer: "jobbade", translation: "عمل في نوبة الليل أمس." },
      { form: "futurum", sentence: "Jag ___ hemifrån i nästa vecka.", answer: "ska jobba", translation: "سأعمل من المنزل الأسبوع القادم." },
    ],
  },
  {
    infinitiv: "kontakta",
    presens: "kontaktar",
    preteritum: "kontaktade",
    supinum: "kontaktat",
    imperativ: "kontakta",
    futurum: "ska kontakta",
    presensParticip: "kontaktande",
    perfektParticip: "kontaktad",
    passivPresens: "kontaktas",
    passivPreteritum: "kontaktades",
    translation: "يتصل / يتواصل مع",
    phonetic: "/kɔnˈtakːta/",
    group: "1",
    level: "B1",
    category: "kommunikation",
    imageUrl: IMG.speak,
    notes: "يُستخدم في السياق الرسمي واليومي للتواصل.",
    examples: [
      { sv: "Kontakta oss via e-post.", ar: "تواصل معنا عبر البريد الإلكتروني." },
      { sv: "Jag kontaktade banken om problemet.", ar: "تواصلتُ مع البنك بشأن المشكلة." },
      { sv: "Vi kontaktar dig när vi vet mer.", ar: "سنتواصل معك حين نعلم المزيد." },
    ],
    quizSentences: [
      { form: "presens", sentence: "Du kan ___ mig när som helst.", answer: "kontakta", translation: "يمكنك التواصل معي في أي وقت." },
      { form: "preteritum", sentence: "Hon ___ företaget direkt.", answer: "kontaktade", translation: "تواصلت مع الشركة مباشرة." },
      { form: "imperativ", sentence: "___ oss för mer information!", answer: "Kontakta", translation: "تواصل معنا للمزيد من المعلومات!" },
    ],
  },
  {
    infinitiv: "lova",
    presens: "lovar",
    preteritum: "lovade",
    supinum: "lovat",
    imperativ: "lova",
    futurum: "ska lova",
    presensParticip: "lovande",
    perfektParticip: "lovad",
    passivPresens: "lovas",
    passivPreteritum: "lovades",
    translation: "يَعِد / يُعطي وعداً",
    phonetic: "/ˈluːva/",
    group: "1",
    level: "A2",
    category: "social",
    imageUrl: IMG.social,
    notes: "'Jag lovar!' = أعدك! 'Håll ditt löfte' = أوفِ بوعدك.",
    examples: [
      { sv: "Jag lovar att inte berätta.", ar: "أعدك أن لا أُخبر أحداً." },
      { sv: "Han lovade att komma i tid.", ar: "وَعَد بأن يأتي في الوقت المحدد." },
      { sv: "Lova mig att du tar hand om dig!", ar: "عِدني أن تعتني بنفسك!" },
    ],
    quizSentences: [
      { form: "presens", sentence: "Jag ___ att hjälpa dig.", answer: "lovar", translation: "أعدك بمساعدتك." },
      { form: "preteritum", sentence: "Han ___ att betala tillbaka pengarna.", answer: "lovade", translation: "وعد بإعادة المال." },
      { form: "imperativ", sentence: "___ mig att inte göra det igen!", answer: "Lova", translation: "عِدني ألّا تفعل ذلك مجدداً!" },
    ],
  },
  {
    infinitiv: "ordna",
    presens: "ordnar",
    preteritum: "ordnade",
    supinum: "ordnat",
    imperativ: "ordna",
    futurum: "ska ordna",
    presensParticip: "ordnande",
    perfektParticip: "ordnad",
    passivPresens: "ordnas",
    passivPreteritum: "ordnades",
    translation: "يُنظّم / يُرتّب",
    phonetic: "/ˈɔrdːna/",
    group: "1",
    level: "A2",
    category: "organisation",
    imageUrl: IMG.work,
    notes: "'Det ordnar sig' = سيُحلّ الأمر (تعبير مُطمئن شائع جداً).",
    examples: [
      { sv: "Det ordnar sig säkert!", ar: "سيُحلّ الأمر بالتأكيد!" },
      { sv: "Kan du ordna ett möte?", ar: "هل يمكنك ترتيب اجتماع؟" },
      { sv: "Jag ordnade allt inför festen.", ar: "رتّبتُ كل شيء قبل الحفلة." },
    ],
    quizSentences: [
      { form: "presens", sentence: "Det ___ sig, oroa dig inte!", answer: "ordnar", translation: "سيُحلّ الأمر، لا تقلق!" },
      { form: "preteritum", sentence: "Hon ___ mötet till nästa vecka.", answer: "ordnade", translation: "رتّبت الاجتماع للأسبوع القادم." },
      { form: "imperativ", sentence: "___ det så snart som möjligt!", answer: "Ordna", translation: "رتّبه في أقرب وقت ممكن!" },
    ],
  },
  {
    infinitiv: "prata",
    presens: "pratar",
    preteritum: "pratade",
    supinum: "pratat",
    imperativ: "prata",
    futurum: "ska prata",
    presensParticip: "pratande",
    perfektParticip: "pratad",
    passivPresens: "pratas",
    passivPreteritum: "pratades",
    translation: "يتكلم / يتحدث (لغة يومية)",
    phonetic: "/ˈprɑːta/",
    group: "1",
    level: "A1",
    category: "kommunikation",
    imageUrl: IMG.speak,
    notes: "أكثر شيوعاً من 'tala' في المحادثات اليومية غير الرسمية.",
    examples: [
      { sv: "Vi pratade hela kvällen.", ar: "تحدثنا طوال المساء." },
      { sv: "Kan vi prata lite?", ar: "هل يمكننا التحدث قليلاً؟" },
      { sv: "Prata inte under lektionen!", ar: "لا تتكلم أثناء الدرس!" },
    ],
    quizSentences: [
      { form: "presens", sentence: "Vi ___ om vädret varje dag.", answer: "pratar", translation: "نتحدث عن الطقس كل يوم." },
      { form: "preteritum", sentence: "De ___ med varandra i en timme.", answer: "pratade", translation: "تحدثا مع بعض لمدة ساعة." },
      { form: "imperativ", sentence: "___ inte med mat i munnen!", answer: "Prata", translation: "لا تتكلم والطعام في فمك!" },
    ],
  },
  {
    infinitiv: "sakna",
    presens: "saknar",
    preteritum: "saknade",
    supinum: "saknat",
    imperativ: "sakna",
    futurum: "ska sakna",
    presensParticip: "saknande",
    perfektParticip: "saknad",
    passivPresens: "saknas",
    passivPreteritum: "saknades",
    translation: "يفتقد / يشتاق",
    phonetic: "/ˈsɑːkna/",
    group: "1",
    level: "A2",
    category: "känsla",
    imageUrl: IMG.emotion,
    notes: "'Jag saknar dig' = أشتاق إليك. من أجمل التعابير السويدية.",
    examples: [
      { sv: "Jag saknar min familj.", ar: "أشتاق لعائلتي." },
      { sv: "Han saknade jobbet när han slutade.", ar: "افتقد العمل عندما استقال." },
      { sv: "Du kommer att sakna den!", ar: "ستشتاق إليه!" },
    ],
    quizSentences: [
      { form: "presens", sentence: "Jag ___ dig så mycket.", answer: "saknar", translation: "أشتاق إليك كثيراً." },
      { form: "preteritum", sentence: "Hon ___ sin hemstad när hon bodde utomlands.", answer: "saknade", translation: "اشتاقت لمدينتها عندما كانت تعيش خارج البلاد." },
      { form: "presens", sentence: "Vad ___ du mest från ditt hemland?", answer: "saknar", translation: "ما الذي تشتاق إليه أكثر من وطنك؟" },
    ],
  },
  {
    infinitiv: "skicka",
    presens: "skickar",
    preteritum: "skickade",
    supinum: "skickat",
    imperativ: "skicka",
    futurum: "ska skicka",
    presensParticip: "skickande",
    perfektParticip: "skickad",
    passivPresens: "skickas",
    passivPreteritum: "skickades",
    translation: "يُرسل",
    phonetic: "/ˈɧɪkːa/",
    group: "1",
    level: "A1",
    category: "kommunikation",
    imageUrl: IMG.tech,
    notes: "يُستخدم للبريد الإلكتروني والرسائل والطرود. 'Skicka till' = يُرسل إلى.",
    examples: [
      { sv: "Skicka mig mejlet!", ar: "أرسل لي البريد الإلكتروني!" },
      { sv: "Jag skickade paketet igår.", ar: "أرسلتُ الطرد أمس." },
      { sv: "Han skickar ett SMS varje kväll.", ar: "يُرسل رسالة نصية كل مساء." },
    ],
    quizSentences: [
      { form: "presens", sentence: "Jag ___ ett mejl till chefen.", answer: "skickar", translation: "أنا أُرسل بريداً إلكترونياً للمدير." },
      { form: "preteritum", sentence: "Hon ___ brevet för en vecka sedan.", answer: "skickade", translation: "أرسلت الرسالة منذ أسبوع." },
      { form: "imperativ", sentence: "___ det till mig om du kan!", answer: "Skicka", translation: "أرسله لي إذا أمكنك!" },
    ],
  },
  {
    infinitiv: "studera",
    presens: "studerar",
    preteritum: "studerade",
    supinum: "studerat",
    imperativ: "studera",
    futurum: "ska studera",
    presensParticip: "studerande",
    perfektParticip: "studerad",
    passivPresens: "studeras",
    passivPreteritum: "studerades",
    translation: "يدرس (دراسة جادة / في الجامعة)",
    phonetic: "/stʉˈdeːra/",
    group: "1",
    level: "A2",
    category: "utbildning",
    imageUrl: IMG.school,
    notes: "يُستخدم للدراسة الجامعية والتعلّم الجاد. 'läsa' أيضاً يعني يدرس.",
    examples: [
      { sv: "Hon studerar medicin i Uppsala.", ar: "تدرس الطب في أوبسالا." },
      { sv: "Jag studerade hela natten.", ar: "درستُ طوال الليل." },
      { sv: "Studera hårt inför provet!", ar: "ادرس بجد قبل الامتحان!" },
    ],
    quizSentences: [
      { form: "presens", sentence: "Han ___ juridik vid universitetet.", answer: "studerar", translation: "هو يدرس القانون في الجامعة." },
      { form: "preteritum", sentence: "Vi ___ svenska i ett år.", answer: "studerade", translation: "درسنا السويدية لمدة عام." },
      { form: "imperativ", sentence: "___ mer, annars klarar du inte provet!", answer: "Studera", translation: "ادرس أكثر وإلا لن تنجح في الامتحان!" },
    ],
  },
  {
    infinitiv: "svara",
    presens: "svarar",
    preteritum: "svarade",
    supinum: "svarat",
    imperativ: "svara",
    futurum: "ska svara",
    presensParticip: "svarande",
    perfektParticip: "svarad",
    passivPresens: "svaras",
    passivPreteritum: "svarades",
    translation: "يُجيب / يردّ",
    phonetic: "/ˈsvɑːra/",
    group: "1",
    level: "A1",
    category: "kommunikation",
    imageUrl: IMG.speak,
    notes: "'svara på' = يُجيب على. 'Svara i telefon' = يردّ على الهاتف.",
    examples: [
      { sv: "Svara på telefonen!", ar: "ردّ على الهاتف!" },
      { sv: "Hon svarade inte på mejlet.", ar: "لم تردّ على البريد الإلكتروني." },
      { sv: "Kan du svara på min fråga?", ar: "هل يمكنك الإجابة على سؤالي؟" },
    ],
    quizSentences: [
      { form: "presens", sentence: "Jag ___ alltid på dina mejl.", answer: "svarar", translation: "أنا دائماً أردّ على رسائلك." },
      { form: "preteritum", sentence: "Han ___ inte när jag ringde.", answer: "svarade", translation: "لم يردّ عندما اتصلتُ." },
      { form: "imperativ", sentence: "___ på frågan, tack!", answer: "Svara", translation: "أجب على السؤال من فضلك!" },
    ],
  },
  {
    infinitiv: "tacka",
    presens: "tackar",
    preteritum: "tackade",
    supinum: "tackat",
    imperativ: "tacka",
    futurum: "ska tacka",
    presensParticip: "tackande",
    perfektParticip: "tackad",
    passivPresens: "tackas",
    passivPreteritum: "tackades",
    translation: "يشكر",
    phonetic: "/ˈtakːa/",
    group: "1",
    level: "A1",
    category: "social",
    imageUrl: IMG.social,
    notes: "'tacka för' = يشكر على. 'Tack!' = شكراً. جذر الفعل هو 'tack'.",
    examples: [
      { sv: "Jag vill tacka dig för hjälpen.", ar: "أريد أن أشكرك على مساعدتك." },
      { sv: "Hon tackade läraren för undervisningen.", ar: "شكرت المعلم على التدريس." },
      { sv: "Tacka alla som kom!", ar: "اشكر جميع من حضروا!" },
    ],
    quizSentences: [
      { form: "presens", sentence: "Jag ___ dig för ditt stöd.", answer: "tackar", translation: "أشكرك على دعمك." },
      { form: "preteritum", sentence: "Vi ___ henne för presenten.", answer: "tackade", translation: "شكرناها على الهدية." },
      { form: "imperativ", sentence: "___ för maten!", answer: "Tacka", translation: "اشكر على الطعام!" },
    ],
  },
  {
    infinitiv: "vänta",
    presens: "väntar",
    preteritum: "väntade",
    supinum: "väntat",
    imperativ: "vänta",
    futurum: "ska vänta",
    presensParticip: "väntande",
    perfektParticip: "väntad",
    passivPresens: "väntas",
    passivPreteritum: "väntades",
    translation: "ينتظر",
    phonetic: "/ˈvɛnːta/",
    group: "1",
    level: "A1",
    category: "allmänt",
    imageUrl: IMG.city,
    notes: "'Vänta på' = ينتظر. 'Vänta lite!' = انتظر قليلاً!",
    examples: [
      { sv: "Vänta på mig!", ar: "انتظرني!" },
      { sv: "Jag väntade i en timme.", ar: "انتظرتُ لمدة ساعة." },
      { sv: "Vänta tills det är klart.", ar: "انتظر حتى ينتهي." },
    ],
    quizSentences: [
      { form: "presens", sentence: "Vi ___ på bussen nu.", answer: "väntar", translation: "نحن ننتظر الحافلة الآن." },
      { form: "preteritum", sentence: "Han ___ länge vid stationen.", answer: "väntade", translation: "انتظر طويلاً في المحطة." },
      { form: "imperativ", sentence: "___ inte, gå in direkt!", answer: "Vänta", translation: "لا تنتظر، ادخل مباشرة!" },
    ],
  },
  {
    infinitiv: "visa",
    presens: "visar",
    preteritum: "visade",
    supinum: "visat",
    imperativ: "visa",
    futurum: "ska visa",
    presensParticip: "visande",
    perfektParticip: "visad",
    passivPresens: "visas",
    passivPreteritum: "visades",
    translation: "يُظهر / يعرض",
    phonetic: "/ˈviːsa/",
    group: "1",
    level: "A1",
    category: "kommunikation",
    imageUrl: IMG.school,
    notes: "'Visa mig' = أرني. 'Visa upp' = يعرض رسمياً.",
    examples: [
      { sv: "Kan du visa mig vägen?", ar: "هل يمكنك أن تُريني الطريق؟" },
      { sv: "Hon visade oss hela huset.", ar: "أرتنا المنزل كاملاً." },
      { sv: "Visa ditt körkort!", ar: "أرِ رخصة قيادتك!" },
    ],
    quizSentences: [
      { form: "presens", sentence: "Han ___ mig hur man gör det.", answer: "visar", translation: "هو يُريني كيف أفعل ذلك." },
      { form: "preteritum", sentence: "Läraren ___ ett exempel på tavlan.", answer: "visade", translation: "أرى المعلم مثالاً على السبورة." },
      { form: "imperativ", sentence: "___ mig ditt pass, tack!", answer: "Visa", translation: "أرِني جواز سفرك من فضلك!" },
    ],
  },
  {
    infinitiv: "tvätta",
    presens: "tvättar",
    preteritum: "tvättade",
    supinum: "tvättat",
    imperativ: "tvätta",
    futurum: "ska tvätta",
    presensParticip: "tvättande",
    perfektParticip: "tvättad",
    passivPresens: "tvättas",
    passivPreteritum: "tvättades",
    translation: "يغسل",
    phonetic: "/ˈtvɛtːa/",
    group: "1",
    level: "A1",
    category: "hem",
    imageUrl: IMG.home,
    notes: "'Tvätta bilen' = يغسل السيارة. 'Tvätta sig' = يستحم / ينظّف نفسه.",
    examples: [
      { sv: "Jag tvättar kläderna på lördagar.", ar: "أغسل الملابس يوم السبت." },
      { sv: "Tvätta händerna innan du äter!", ar: "اغسل يديك قبل الأكل!" },
      { sv: "Han tvättade bilen i morse.", ar: "غسل السيارة في الصباح الباكر." },
    ],
    quizSentences: [
      { form: "presens", sentence: "Hon ___ alltid disken direkt.", answer: "tvättar", translation: "هي دائماً تغسل الأطباق مباشرة." },
      { form: "preteritum", sentence: "Vi ___ kläderna igår.", answer: "tvättade", translation: "غسلنا الملابس أمس." },
      { form: "imperativ", sentence: "___ händerna noga!", answer: "Tvätta", translation: "اغسل يديك جيداً!" },
    ],
  },
  {
    infinitiv: "spara",
    presens: "sparar",
    preteritum: "sparade",
    supinum: "sparat",
    imperativ: "spara",
    futurum: "ska spara",
    presensParticip: "sparande",
    perfektParticip: "sparad",
    passivPresens: "sparas",
    passivPreteritum: "sparades",
    translation: "يوفّر / يدّخر",
    phonetic: "/ˈspɑːra/",
    group: "1",
    level: "A2",
    category: "ekonomi",
    imageUrl: IMG.money,
    notes: "'Spara pengar' = يدّخر المال. 'Spara' أيضاً = يحفظ (الملفات).",
    examples: [
      { sv: "Jag sparar pengar till en resa.", ar: "أدّخر المال لرحلة." },
      { sv: "Spara filen innan du stänger!", ar: "احفظ الملف قبل الإغلاق!" },
      { sv: "Han sparar 20% av lönen varje månad.", ar: "يدّخر 20% من راتبه كل شهر." },
    ],
    quizSentences: [
      { form: "presens", sentence: "Vi ___ till ett nytt hus.", answer: "sparar", translation: "نوفّر لبيت جديد." },
      { form: "preteritum", sentence: "Hon ___ pengar länge för att köpa bilen.", answer: "sparade", translation: "ادّخرت مالاً طويلاً لشراء السيارة." },
      { form: "imperativ", sentence: "___ dokumentet nu!", answer: "Spara", translation: "احفظ المستند الآن!" },
    ],
  },
  {
    infinitiv: "berömma",
    presens: "berömmer",
    preteritum: "berömde",
    supinum: "berömt",
    imperativ: "beröm",
    futurum: "ska berömma",
    presensParticip: "berömmande",
    perfektParticip: "berömd",
    passivPresens: "beröms",
    passivPreteritum: "berömdes",
    translation: "يمدح / يُثني على",
    phonetic: "/bɛˈrœmːa/",
    group: "2b",
    level: "B1",
    category: "social",
    imageUrl: IMG.social,
    notes: "مجموعة 2b. 'berömd' كصفة = مشهور.",
    examples: [
      { sv: "Läraren berömde eleverna.", ar: "أثنى المعلم على الطلاب." },
      { sv: "Beröm inte för mycket, det kan ge dåligt självförtroende.", ar: "لا تمدح كثيراً، قد يؤثر سلباً على الثقة بالنفس." },
      { sv: "Han är berömd för sina konstverk.", ar: "هو مشهور بأعماله الفنية." },
    ],
    quizSentences: [
      { form: "presens", sentence: "Chefen ___ alltid bra arbete.", answer: "berömmer", translation: "المدير دائماً يُثني على العمل الجيد." },
      { form: "preteritum", sentence: "Hon ___ mig för min svenska.", answer: "berömde", translation: "أثنت على سويديتي." },
      { form: "imperativ", sentence: "___ varandra mer!", answer: "Beröm", translation: "امدحوا بعضكم أكثر!" },
    ],
  },

  // ══════════════════════════════════════════════════════════════════
  // GRUPP 2a — -er/-de verbs
  // ══════════════════════════════════════════════════════════════════
  {
    infinitiv: "stanna",
    presens: "stannar",
    preteritum: "stannade",
    supinum: "stannat",
    imperativ: "stanna",
    futurum: "ska stanna",
    presensParticip: "stannande",
    perfektParticip: "stannad",
    passivPresens: "stannas",
    passivPreteritum: "stannades",
    translation: "يبقى / يتوقف",
    phonetic: "/ˈstanːa/",
    group: "1",
    level: "A1",
    category: "rörelse",
    imageUrl: IMG.city,
    notes: "'Stanna kvar' = يبقى. 'Stanna!' = قِف! للسيارة.",
    examples: [
      { sv: "Stanna här, kom inte in!", ar: "ابقَ هنا، لا تدخل!" },
      { sv: "Bussen stannade vid hållplatsen.", ar: "توقف الأتوبيس عند المحطة." },
      { sv: "Kan du stanna lite längre?", ar: "هل يمكنك البقاء قليلاً أطول؟" },
    ],
    quizSentences: [
      { form: "presens", sentence: "Tåget ___ i Uppsala i tre minuter.", answer: "stannar", translation: "القطار يتوقف في أوبسالا لثلاث دقائق." },
      { form: "preteritum", sentence: "Vi ___ kvar hos dem över natten.", answer: "stannade", translation: "بقينا عندهم طوال الليل." },
      { form: "imperativ", sentence: "___ här och vänta på mig!", answer: "Stanna", translation: "ابقَ هنا وانتظرني!" },
    ],
  },
  {
    infinitiv: "sälja",
    presens: "säljer",
    preteritum: "sålde",
    supinum: "sålt",
    imperativ: "sälj",
    futurum: "ska sälja",
    presensParticip: "säljande",
    perfektParticip: "såld",
    passivPresens: "säljs",
    passivPreteritum: "såldes",
    translation: "يبيع",
    phonetic: "/ˈsɛlːja/",
    group: "2b",
    level: "A2",
    category: "handel",
    imageUrl: IMG.shopping,
    notes: "مجموعة 2b غير منتظمة. ضد 'köpa'. 'Säljs!' = للبيع!",
    examples: [
      { sv: "Jag säljer min cykel.", ar: "أبيع دراجتي." },
      { sv: "De sålde huset för 3 miljoner.", ar: "باعوا البيت بـ 3 ملايين كرونا." },
      { sv: "Sälj den om du inte behöver den.", ar: "بعها إذا لم تكن بحاجة إليها." },
    ],
    quizSentences: [
      { form: "presens", sentence: "Affären ___ ekologiska produkter.", answer: "säljer", translation: "المتجر يبيع منتجات عضوية." },
      { form: "preteritum", sentence: "Han ___ sin gamla bil.", answer: "sålde", translation: "باع سيارته القديمة." },
      { form: "imperativ", sentence: "___ det om du kan!", answer: "Sälj", translation: "بعه إذا استطعت!" },
    ],
  },
  {
    infinitiv: "tycka",
    presens: "tycker",
    preteritum: "tyckte",
    supinum: "tyckt",
    imperativ: "tyck",
    futurum: "ska tycka",
    presensParticip: "tyckte",
    perfektParticip: "tyckt",
    passivPresens: "tycks",
    passivPreteritum: "tycktes",
    translation: "يعتقد / يرى (رأي)",
    phonetic: "/ˈtʏkːa/",
    group: "2b",
    level: "A1",
    category: "kognition",
    imageUrl: IMG.school,
    notes: "'Tycka om' = يُحب (يحب شيئاً). 'Tycka att' = يرى أن. مهم جداً للتعبير عن الرأي.",
    examples: [
      { sv: "Vad tycker du om Sverige?", ar: "ما رأيك في السويد؟" },
      { sv: "Jag tycker att det är bra.", ar: "أرى أنه جيد." },
      { sv: "Han tycker om jazz.", ar: "هو يحب الجاز." },
    ],
    quizSentences: [
      { form: "presens", sentence: "Jag ___ att hon har rätt.", answer: "tycker", translation: "أرى أنها على حق." },
      { form: "preteritum", sentence: "Vi ___ att filmen var lång.", answer: "tyckte", translation: "رأينا أن الفيلم كان طويلاً." },
      { form: "presens", sentence: "Vad ___ du om den nya lagen?", answer: "tycker", translation: "ما رأيك في القانون الجديد؟" },
    ],
  },

  // ══════════════════════════════════════════════════════════════════
  // OREGELBUNDNA — Irregular verbs
  // ══════════════════════════════════════════════════════════════════
  {
    infinitiv: "bli",
    presens: "blir",
    preteritum: "blev",
    supinum: "blivit",
    imperativ: "bli",
    futurum: "ska bli",
    presensParticip: "blivande",
    perfektParticip: "blivit",
    passivPresens: "blis",
    passivPreteritum: "blivit",
    translation: "يصبح / يكون",
    phonetic: "/bliː/",
    group: "oregelbundet",
    level: "A1",
    category: "tillstånd",
    imageUrl: IMG.city,
    notes: "فعل شائع جداً وغير منتظم. 'Bli glad' = يُصبح سعيداً. 'Vad vill du bli?' = ماذا تريد أن تصبح؟",
    examples: [
      { sv: "Jag vill bli läkare.", ar: "أريد أن أصبح طبيباً." },
      { sv: "Det blev kallt igår.", ar: "أصبح الجو بارداً أمس." },
      { sv: "Hon har blivit bättre.", ar: "لقد تحسّنت." },
    ],
    quizSentences: [
      { form: "presens", sentence: "Det ___ bättre snart!", answer: "blir", translation: "سيتحسّن الأمر قريباً!" },
      { form: "preteritum", sentence: "Han ___ lärare efter studierna.", answer: "blev", translation: "أصبح معلماً بعد الدراسة." },
      { form: "supinum", sentence: "Hon har ___ framgångsrik.", answer: "blivit", translation: "لقد أصبحت ناجحة." },
    ],
  },
  {
    infinitiv: "falla",
    presens: "faller",
    preteritum: "föll",
    supinum: "fallit",
    imperativ: "fall",
    futurum: "ska falla",
    presensParticip: "fallande",
    perfektParticip: "fallen",
    passivPresens: "falls",
    passivPreteritum: "fallit",
    translation: "يسقط",
    phonetic: "/ˈfalːa/",
    group: "oregelbundet",
    level: "A2",
    category: "rörelse",
    imageUrl: IMG.sport,
    notes: "فعل غير منتظم. 'Priser faller' = الأسعار تنخفض. 'Falla ihop' = ينهار.",
    examples: [
      { sv: "Löven faller på hösten.", ar: "تسقط الأوراق في الخريف." },
      { sv: "Jag föll på isen.", ar: "سقطتُ على الجليد." },
      { sv: "Var försiktig så du inte faller!", ar: "كن حذراً حتى لا تسقط!" },
    ],
    quizSentences: [
      { form: "presens", sentence: "Snön ___ tyst utanför.", answer: "faller", translation: "الثلج يسقط بهدوء في الخارج." },
      { form: "preteritum", sentence: "Han ___ och slog sig.", answer: "föll", translation: "سقط وأصيب." },
      { form: "imperativ", sentence: "Håll dig i räcket så du inte ___!", answer: "fall", translation: "تمسّك بالدرابزين حتى لا تسقط!" },
    ],
  },
  {
    infinitiv: "sitta",
    presens: "sitter",
    preteritum: "satt",
    supinum: "suttit",
    imperativ: "sitt",
    futurum: "ska sitta",
    presensParticip: "sittande",
    perfektParticip: "suttit",
    passivPresens: "sits",
    passivPreteritum: "satt",
    translation: "يجلس",
    phonetic: "/ˈsɪtːa/",
    group: "oregelbundet",
    level: "A1",
    category: "rörelse",
    imageUrl: IMG.city,
    notes: "فعل غير منتظم. 'Sitta ner' = يجلس. 'Sitta still' = يجلس ساكناً.",
    examples: [
      { sv: "Kan jag sitta här?", ar: "هل يمكنني الجلوس هنا؟" },
      { sv: "Vi satt och pratade hela kvällen.", ar: "جلسنا نتحدث طوال المساء." },
      { sv: "Sitt ner och lyssna!", ar: "اجلس واستمع!" },
    ],
    quizSentences: [
      { form: "presens", sentence: "Han ___ vid datorn hela dagen.", answer: "sitter", translation: "هو يجلس أمام الكمبيوتر طوال اليوم." },
      { form: "preteritum", sentence: "Vi ___ i parken och filade.", answer: "satt", translation: "جلسنا في الحديقة وتناولنا القهوة." },
      { form: "imperativ", sentence: "___ still, fotot tas nu!", answer: "Sitt", translation: "اجلس ساكناً، الصورة ستُلتقط الآن!" },
    ],
  },
  {
    infinitiv: "stå",
    presens: "står",
    preteritum: "stod",
    supinum: "stått",
    imperativ: "stå",
    futurum: "ska stå",
    presensParticip: "stående",
    perfektParticip: "stått",
    passivPresens: "stås",
    passivPreteritum: "stods",
    translation: "يقف",
    phonetic: "/stoː/",
    group: "oregelbundet",
    level: "A1",
    category: "rörelse",
    imageUrl: IMG.city,
    notes: "فعل شائع جداً وغير منتظم. 'Stå i kö' = ينتظر في الطابور. 'Det står...' = مكتوب...",
    examples: [
      { sv: "Jag stod i kö i en timme.", ar: "وقفتُ في الطابور لمدة ساعة." },
      { sv: "Var är du? Jag står utanför.", ar: "أين أنت؟ أنا واقف في الخارج." },
      { sv: "Stå inte där, det är farligt!", ar: "لا تقف هناك، إنه خطير!" },
    ],
    quizSentences: [
      { form: "presens", sentence: "Hon ___ och väntar vid ingången.", answer: "står", translation: "هي واقفة تنتظر عند المدخل." },
      { form: "preteritum", sentence: "Vi ___ i kö i en halvtimme.", answer: "stod", translation: "وقفنا في الطابور نصف ساعة." },
      { form: "imperativ", sentence: "___ inte för länge i solen!", answer: "Stå", translation: "لا تقف طويلاً في الشمس!" },
    ],
  },
  {
    infinitiv: "ligga",
    presens: "ligger",
    preteritum: "låg",
    supinum: "legat",
    imperativ: "ligg",
    futurum: "ska ligga",
    presensParticip: "liggande",
    perfektParticip: "legat",
    passivPresens: "liggas",
    passivPreteritum: "lades",
    translation: "يستلقي / يقع (موقعاً)",
    phonetic: "/ˈlɪgːa/",
    group: "oregelbundet",
    level: "A2",
    category: "tillstånd",
    imageUrl: IMG.sleep,
    notes: "فعل غير منتظم. 'Stockholm ligger i Sverige' = ستوكهولم تقع في السويد.",
    examples: [
      { sv: "Sverige ligger i Skandinavien.", ar: "السويد تقع في اسكندنافيا." },
      { sv: "Han låg sjuk i en vecka.", ar: "مرض وبقي في فراشه أسبوعاً." },
      { sv: "Ligg still, jag undersöker dig.", ar: "استلقِ ساكناً، سأفحصك." },
    ],
    quizSentences: [
      { form: "presens", sentence: "Boken ___ på bordet.", answer: "ligger", translation: "الكتاب على الطاولة." },
      { form: "preteritum", sentence: "Han ___ och sov hela dagen.", answer: "låg", translation: "استلقى ينام طوال اليوم." },
      { form: "imperativ", sentence: "___ stilla och vila!", answer: "Ligg", translation: "استلقِ ساكناً واسترح!" },
    ],
  },
  {
    infinitiv: "slå",
    presens: "slår",
    preteritum: "slog",
    supinum: "slagit",
    imperativ: "slå",
    futurum: "ska slå",
    presensParticip: "slående",
    perfektParticip: "slagen",
    passivPresens: "slås",
    passivPreteritum: "slogs",
    translation: "يضرب / يُحقق رقماً قياسياً",
    phonetic: "/sloː/",
    group: "oregelbundet",
    level: "B1",
    category: "sport",
    imageUrl: IMG.sport,
    notes: "فعل غير منتظم متعدد الاستخدامات. 'Slå rekord' = يُحقق رقماً قياسياً. 'Slå upp' = يبحث في القاموس.",
    examples: [
      { sv: "Hon slog ett nytt rekord.", ar: "حقّقت رقماً قياسياً جديداً." },
      { sv: "Slå upp ordet i ordboken.", ar: "ابحث عن الكلمة في القاموس." },
      { sv: "Slå inte andra barn!", ar: "لا تضرب الأطفال الآخرين!" },
    ],
    quizSentences: [
      { form: "presens", sentence: "Laget ___ motståndarna med 3-0.", answer: "slår", translation: "الفريق يتغلب على الخصم 3-0." },
      { form: "preteritum", sentence: "Hon ___ världsrekordet.", answer: "slog", translation: "حطّمت الرقم القياسي العالمي." },
      { form: "imperativ", sentence: "___ upp det i lexikonet!", answer: "Slå", translation: "ابحث عنه في المعجم!" },
    ],
  },
  {
    infinitiv: "vinna",
    presens: "vinner",
    preteritum: "vann",
    supinum: "vunnit",
    imperativ: "vinn",
    futurum: "ska vinna",
    presensParticip: "vinnande",
    perfektParticip: "vunnen",
    passivPresens: "vinns",
    passivPreteritum: "vanns",
    translation: "يفوز / يكسب",
    phonetic: "/ˈvɪnːa/",
    group: "oregelbundet",
    level: "A2",
    category: "sport",
    imageUrl: IMG.sport,
    notes: "فعل غير منتظم. 'Vinnare' = الفائز. 'Vinna på' = يفوز في (الروليت مثلاً).",
    examples: [
      { sv: "Sverige vann matchen!", ar: "السويد فازت في المباراة!" },
      { sv: "Vem vann i VM?", ar: "من فاز في كأس العالم؟" },
      { sv: "Vinn om du kan!", ar: "افز إذا استطعت!" },
    ],
    quizSentences: [
      { form: "presens", sentence: "Laget ___ varje vecka.", answer: "vinner", translation: "الفريق يفوز كل أسبوع." },
      { form: "preteritum", sentence: "Vi ___ tävlingen!", answer: "vann", translation: "فزنا في المسابقة!" },
      { form: "imperativ", sentence: "___ det här för oss!", answer: "Vinn", translation: "أحرز هذا الفوز لنا!" },
    ],
  },
  {
    infinitiv: "minnas",
    presens: "minns",
    preteritum: "mindes",
    supinum: "mints",
    imperativ: "minns",
    futurum: "ska minnas",
    presensParticip: "minnedes",
    perfektParticip: "mints",
    passivPresens: null,
    passivPreteritum: null,
    translation: "يتذكر",
    phonetic: "/ˈmɪnːas/",
    group: "oregelbundet",
    level: "A2",
    category: "kognition",
    imageUrl: IMG.school,
    notes: "فعل غير منتظم يأتي في الصيغة الإبداعية. 'Minns du?' = هل تتذكر؟ لاحظ: 'minns' = المضارع والأمر.",
    examples: [
      { sv: "Minns du när vi träffades?", ar: "هل تتذكر عندما التقينا؟" },
      { sv: "Jag minns inte hans namn.", ar: "لا أتذكر اسمه." },
      { sv: "De mindes kriget tydligt.", ar: "تذكّروا الحرب بوضوح." },
    ],
    quizSentences: [
      { form: "presens", sentence: "Jag ___ inte var jag la nycklarna.", answer: "minns", translation: "لا أتذكر أين وضعتُ المفاتيح." },
      { form: "preteritum", sentence: "Han ___ allt från barndomen.", answer: "mindes", translation: "تذكّر كل شيء من الطفولة." },
      { form: "presens", sentence: "___ du vad vi pratade om igår?", answer: "Minns", translation: "هل تتذكر ما تحدثنا عنه أمس؟" },
    ],
  },
  {
    infinitiv: "njuta",
    presens: "njuter",
    preteritum: "njöt",
    supinum: "njutit",
    imperativ: "njut",
    futurum: "ska njuta",
    presensParticip: "njutande",
    perfektParticip: "njutit",
    passivPresens: null,
    passivPreteritum: null,
    translation: "يستمتع",
    phonetic: "/ˈnjʉːta/",
    group: "oregelbundet",
    level: "B1",
    category: "känsla",
    imageUrl: IMG.emotion,
    notes: "فعل غير منتظم. 'njuta av' = يستمتع بـ. تعبير جميل للسعادة.",
    examples: [
      { sv: "Njut av livet!", ar: "استمتع بالحياة!" },
      { sv: "Vi njöt av semestern.", ar: "استمتعنا بالإجازة." },
      { sv: "Han njuter av en kopp kaffe.", ar: "يستمتع بكوب قهوة." },
    ],
    quizSentences: [
      { form: "presens", sentence: "Jag ___ av naturen i Sverige.", answer: "njuter", translation: "أستمتع بطبيعة السويد." },
      { form: "preteritum", sentence: "Vi ___ av kvällen.", answer: "njöt", translation: "استمتعنا بالمساء." },
      { form: "imperativ", sentence: "___ av din semester!", answer: "Njut", translation: "استمتع بإجازتك!" },
    ],
  },
  {
    infinitiv: "förstöra",
    presens: "förstör",
    preteritum: "förstörde",
    supinum: "förstört",
    imperativ: "förstör",
    futurum: "ska förstöra",
    presensParticip: "förstörande",
    perfektParticip: "förstörd",
    passivPresens: "förstörs",
    passivPreteritum: "förstördes",
    translation: "يُدمّر / يُتلف",
    phonetic: "/fœɧˈtøːra/",
    group: "2a",
    level: "B1",
    category: "allmänt",
    imageUrl: IMG.city,
    notes: "مجموعة 2a. 'Förstör inte!' = لا تُتلف!",
    examples: [
      { sv: "Regnet förstörde festen.", ar: "المطر أفسد الحفلة." },
      { sv: "Förstör inte möblerna!", ar: "لا تُتلف الأثاث!" },
      { sv: "Han har förstört mitt förtroendet.", ar: "لقد دمّر ثقتي." },
    ],
    quizSentences: [
      { form: "presens", sentence: "Inget ___ min dag idag!", answer: "förstör", translation: "لا شيء يُفسد يومي اليوم!" },
      { form: "preteritum", sentence: "Branden ___ hela byggnaden.", answer: "förstörde", translation: "الحريق دمّر المبنى بالكامل." },
      { form: "imperativ", sentence: "___ inte relationen!", answer: "Förstör", translation: "لا تُدمّر العلاقة!" },
    ],
  },
  {
    infinitiv: "hinna",
    presens: "hinner",
    preteritum: "hann",
    supinum: "hunnit",
    imperativ: "hinn",
    futurum: "ska hinna",
    presensParticip: "hinnande",
    perfektParticip: "hunnit",
    passivPresens: null,
    passivPreteritum: null,
    translation: "يلحق / يجد الوقت لـ",
    phonetic: "/ˈhɪnːa/",
    group: "oregelbundet",
    level: "A2",
    category: "tid",
    imageUrl: IMG.city,
    notes: "فعل غير منتظم. 'Hinner du?' = هل لديك وقت؟ 'Jag hinner inte' = ليس لديّ وقت.",
    examples: [
      { sv: "Jag hinner inte till mötet.", ar: "لن أستطيع اللحق بالاجتماع." },
      { sv: "Vi hann precis med tåget!", ar: "لحقنا بالقطار بالكاد!" },
      { sv: "Hinner du äta lunch med mig?", ar: "هل لديك وقت لتناول الغداء معي؟" },
    ],
    quizSentences: [
      { form: "presens", sentence: "Jag ___ inte med allt idag.", answer: "hinner", translation: "لن أستطيع إنجاز كل شيء اليوم." },
      { form: "preteritum", sentence: "Vi ___ knappt med bussen.", answer: "hann", translation: "كدنا أن نلحق بالأتوبيس." },
      { form: "presens", sentence: "___ du komma på mötet?", answer: "Hinner", translation: "هل يمكنك حضور الاجتماع؟" },
    ],
  },
  {
    infinitiv: "dra",
    presens: "drar",
    preteritum: "drog",
    supinum: "dragit",
    imperativ: "dra",
    futurum: "ska dra",
    presensParticip: "dragande",
    perfektParticip: "dragen",
    passivPresens: "dras",
    passivPreteritum: "drogs",
    translation: "يسحب / يجرّ",
    phonetic: "/drɑː/",
    group: "oregelbundet",
    level: "A2",
    category: "rörelse",
    imageUrl: IMG.sport,
    notes: "فعل غير منتظم. 'Dra i' = يسحب. 'Dra sig tillbaka' = ينسحب. 'Dra slutsatser' = يستنتج.",
    examples: [
      { sv: "Dra i handtaget!", ar: "اسحب المقبض!" },
      { sv: "Han drog henne ut ur faran.", ar: "سحبها بعيداً عن الخطر." },
      { sv: "Vi drog slutsatsen att...", ar: "استنتجنا أن..." },
    ],
    quizSentences: [
      { form: "presens", sentence: "Vinden ___ i skyltarna.", answer: "drar", translation: "الريح تسحب اللافتات." },
      { form: "preteritum", sentence: "Han ___ kortet ur plånboken.", answer: "drog", translation: "سحب البطاقة من المحفظة." },
      { form: "imperativ", sentence: "___ dörrn, inte trycka!", answer: "Dra", translation: "اسحب الباب، لا تدفعه!" },
    ],
  },
  {
    infinitiv: "leka",
    presens: "leker",
    preteritum: "lekte",
    supinum: "lekt",
    imperativ: "lek",
    futurum: "ska leka",
    presensParticip: "lekande",
    perfektParticip: "lekt",
    passivPresens: "lekas",
    passivPreteritum: "lektes",
    translation: "يلعب (لعب أطفال)",
    phonetic: "/ˈleːka/",
    group: "2b",
    level: "A1",
    category: "barn",
    imageUrl: IMG.family,
    notes: "يُستخدم للأطفال. الكبار يستخدمون 'spela' للألعاب. 'Lekplats' = ملعب أطفال.",
    examples: [
      { sv: "Barnen leker i parken.", ar: "الأطفال يلعبون في الحديقة." },
      { sv: "Lek med din syster!", ar: "العب مع أختك!" },
      { sv: "De lekte hela eftermiddagen.", ar: "لعبوا طوال بعد الظهر." },
    ],
    quizSentences: [
      { form: "presens", sentence: "Barnen ___ på gatan.", answer: "leker", translation: "الأطفال يلعبون في الشارع." },
      { form: "preteritum", sentence: "Vi ___ kurragömma som barn.", answer: "lekte", translation: "لعبنا الغميضة وكنّا أطفالاً." },
      { form: "imperativ", sentence: "___ lite, det är bra för dig!", answer: "Lek", translation: "العب قليلاً، إنه مفيد لك!" },
    ],
  },
  {
    infinitiv: "löpa",
    presens: "löper",
    preteritum: "löpte",
    supinum: "löpt",
    imperativ: "löp",
    futurum: "ska löpa",
    presensParticip: "löpande",
    perfektParticip: "löpt",
    passivPresens: "löps",
    passivPreteritum: "löptes",
    translation: "يجري (رياضة / عدو)",
    phonetic: "/ˈløːpa/",
    group: "2b",
    level: "B1",
    category: "sport",
    imageUrl: IMG.sport,
    notes: "مجموعة 2b. أكثر رسمية من 'springa'. 'Löpband' = جهاز الجري.",
    examples: [
      { sv: "Han löper 10 km varje dag.", ar: "يجري 10 كيلومترات كل يوم." },
      { sv: "De löpte mot mål.", ar: "جروا نحو الهدف." },
      { sv: "Löp inte inomhus!", ar: "لا تجرِ في الداخل!" },
    ],
    quizSentences: [
      { form: "presens", sentence: "Hon ___ maraton varje år.", answer: "löper", translation: "هي تجري ماراثوناً كل عام." },
      { form: "preteritum", sentence: "Vi ___ 5 km i parken.", answer: "löpte", translation: "جرينا 5 كيلومترات في الحديقة." },
      { form: "imperativ", sentence: "___ fortare, vi är sena!", answer: "Löp", translation: "اجرِ بسرعة، نحن متأخرون!" },
    ],
  },
  {
    infinitiv: "kasta",
    presens: "kastar",
    preteritum: "kastade",
    supinum: "kastat",
    imperativ: "kasta",
    futurum: "ska kasta",
    presensParticip: "kastande",
    perfektParticip: "kastad",
    passivPresens: "kastas",
    passivPreteritum: "kastades",
    translation: "يرمي / يُلقي",
    phonetic: "/ˈkastːa/",
    group: "1",
    level: "A2",
    category: "sport",
    imageUrl: IMG.sport,
    notes: "فعل مجموعة 1. 'Kasta bort' = يتخلص من. 'Kasta sig' = ينقض.",
    examples: [
      { sv: "Kasta bollen hit!", ar: "ارمِ الكرة هنا!" },
      { sv: "Kasta inte skräp på marken.", ar: "لا ترمِ القمامة على الأرض." },
      { sv: "Han kastade sig in i projektet.", ar: "انغمس في المشروع بحماس." },
    ],
    quizSentences: [
      { form: "presens", sentence: "Han ___ papper i papperskorgen.", answer: "kastar", translation: "هو يرمي الورق في سلة المهملات." },
      { form: "preteritum", sentence: "Barnet ___ bollen ut i sjön.", answer: "kastade", translation: "رمى الطفل الكرة في البحيرة." },
      { form: "imperativ", sentence: "___ inte det, det är viktigt!", answer: "Kasta", translation: "لا تُلقِ بذلك، إنه مهم!" },
    ],
  },
  {
    infinitiv: "sätta",
    presens: "sätter",
    preteritum: "satte",
    supinum: "satt",
    imperativ: "sätt",
    futurum: "ska sätta",
    presensParticip: "sättande",
    perfektParticip: "satt",
    passivPresens: "sätts",
    passivPreteritum: "sattes",
    translation: "يضع / يُثبّت",
    phonetic: "/ˈsɛtːa/",
    group: "oregelbundet",
    level: "A2",
    category: "allmänt",
    imageUrl: IMG.home,
    notes: "فعل غير منتظم. 'Sätta på' = يُشغّل. 'Sätta sig' = يجلس. 'Sätta ihop' = يُركّب.",
    examples: [
      { sv: "Sätt på musiken!", ar: "شغّل الموسيقى!" },
      { sv: "Hon satte kaffekoppen på bordet.", ar: "وضعت كوب القهوة على الطاولة." },
      { sv: "Sätt dig och vila.", ar: "اجلس واسترح." },
    ],
    quizSentences: [
      { form: "presens", sentence: "Han ___ glasögonen på.", answer: "sätter", translation: "هو يضع نظارته." },
      { form: "preteritum", sentence: "Hon ___ blomman i vasen.", answer: "satte", translation: "وضعت الزهرة في المزهرية." },
      { form: "imperativ", sentence: "___ på TV:n, nyheterna börjar!", answer: "Sätt", translation: "شغّل التلفزيون، الأخبار تبدأ!" },
    ],
  },
  {
    infinitiv: "bryta",
    presens: "bryter",
    preteritum: "bröt",
    supinum: "brutit",
    imperativ: "bryt",
    futurum: "ska bryta",
    presensParticip: "brytande",
    perfektParticip: "bruten",
    passivPresens: "bryts",
    passivPreteritum: "bröts",
    translation: "يكسر / يخرق",
    phonetic: "/ˈbrʏːta/",
    group: "oregelbundet",
    level: "B1",
    category: "allmänt",
    imageUrl: IMG.home,
    notes: "فعل غير منتظم. 'Bryta mot lagen' = يُخالف القانون. 'Bryta ihop' = ينهار عاطفياً.",
    examples: [
      { sv: "Bryt inte mot reglerna!", ar: "لا تُخالف القواعد!" },
      { sv: "Han bröt armen i fotbollsmatchen.", ar: "كسر ذراعه في مباراة كرة قدم." },
      { sv: "Isen bröt under honom.", ar: "انكسر الجليد تحته." },
    ],
    quizSentences: [
      { form: "presens", sentence: "Hon ___ alltid sina löften.", answer: "bryter", translation: "هي دائماً تنقض وعودها." },
      { form: "preteritum", sentence: "Han ___ fönstret av misstag.", answer: "bröt", translation: "كسر النافذة بالخطأ." },
      { form: "imperativ", sentence: "___ inte reglerna!", answer: "Bryt", translation: "لا تُخالف القواعد!" },
    ],
  },
  {
    infinitiv: "förlora",
    presens: "förlorar",
    preteritum: "förlorade",
    supinum: "förlorat",
    imperativ: "förlora",
    futurum: "ska förlora",
    presensParticip: "förlorande",
    perfektParticip: "förlorad",
    passivPresens: "förloras",
    passivPreteritum: "förlorades",
    translation: "يخسر / يفقد",
    phonetic: "/fœrˈluːra/",
    group: "1",
    level: "A2",
    category: "sport",
    imageUrl: IMG.sport,
    notes: "فعل مجموعة 1. ضد 'vinna'. 'Förlora hoppet' = يفقد الأمل.",
    examples: [
      { sv: "Laget förlorade 1-3.", ar: "الفريق خسر 1-3." },
      { sv: "Förlora inte hoppet!", ar: "لا تفقد الأمل!" },
      { sv: "Han förlorade plånboken.", ar: "فقد محفظته." },
    ],
    quizSentences: [
      { form: "presens", sentence: "Ingen vill ___ en tävling.", answer: "förlora", translation: "لا أحد يريد أن يخسر مسابقة." },
      { form: "preteritum", sentence: "Sverige ___ finalen.", answer: "förlorade", translation: "السويد خسرت في النهائي." },
      { form: "imperativ", sentence: "___ inte självförtroendet!", answer: "Förlora", translation: "لا تفقد ثقتك بنفسك!" },
    ],
  },
  {
    infinitiv: "växa",
    presens: "växer",
    preteritum: "växte",
    supinum: "vuxit",
    imperativ: "väx",
    futurum: "ska växa",
    presensParticip: "växande",
    perfektParticip: "vuxit",
    passivPresens: "växas",
    passivPreteritum: "växtes",
    translation: "ينمو / يكبر",
    phonetic: "/ˈvɛkːsa/",
    group: "oregelbundet",
    level: "A2",
    category: "natur",
    imageUrl: IMG.nature,
    notes: "فعل غير منتظم. 'Växa upp' = يكبر. 'Växande' = متنامٍ.",
    examples: [
      { sv: "Träd växer sakta.", ar: "الأشجار تنمو ببطء." },
      { sv: "Han växte upp i Stockholm.", ar: "كبر في ستوكهولم." },
      { sv: "Företaget har vuxit snabbt.", ar: "الشركة نمت بسرعة." },
    ],
    quizSentences: [
      { form: "presens", sentence: "Blommorna ___ bra i solen.", answer: "växer", translation: "الزهور تنمو بشكل جيد في الشمس." },
      { form: "preteritum", sentence: "Han ___ upp utan sin pappa.", answer: "växte", translation: "كبر بدون والده." },
      { form: "supinum", sentence: "Företaget har ___ till ett stort bolag.", answer: "vuxit", translation: "الشركة نمت لتصبح شركة كبيرة." },
    ],
  },
  {
    infinitiv: "smaka",
    presens: "smakar",
    preteritum: "smakade",
    supinum: "smakat",
    imperativ: "smaka",
    futurum: "ska smaka",
    presensParticip: "smakande",
    perfektParticip: "smakad",
    passivPresens: "smakas",
    passivPreteritum: "smakades",
    translation: "يتذوق / له نكهة",
    phonetic: "/ˈsmɑːka/",
    group: "1",
    level: "A1",
    category: "mat",
    imageUrl: IMG.food,
    notes: "فعل مجموعة 1. 'Hur smakar det?' = كيف نكهته؟ 'Det smakar gott!' = إنه لذيذ!",
    examples: [
      { sv: "Smaka på den här soppan!", ar: "تذوّق هذه الشوربة!" },
      { sv: "Det smakar sött.", ar: "نكهته حلوة." },
      { sv: "Hur smakade maten?", ar: "كيف كانت نكهة الطعام؟" },
    ],
    quizSentences: [
      { form: "presens", sentence: "Det ___ fantastiskt!", answer: "smakar", translation: "نكهته رائعة!" },
      { form: "preteritum", sentence: "Kakan ___ inte som jag förväntade.", answer: "smakade", translation: "نكهة الكعكة لم تكن كما توقّعت." },
      { form: "imperativ", sentence: "___ och berätta vad du tycker!", answer: "Smaka", translation: "تذوّق وأخبرني رأيك!" },
    ],
  },
  {
    infinitiv: "uppfatta",
    presens: "uppfattar",
    preteritum: "uppfattade",
    supinum: "uppfattat",
    imperativ: "uppfatta",
    futurum: "ska uppfatta",
    presensParticip: "uppfattande",
    perfektParticip: "uppfattad",
    passivPresens: "uppfattas",
    passivPreteritum: "uppfattades",
    translation: "يُدرك / يفهم / يستوعب",
    phonetic: "/ˈɵpːˌfatːa/",
    group: "1",
    level: "B1",
    category: "kognition",
    imageUrl: IMG.school,
    notes: "فعل مجموعة 1. 'Uppfattar du?' = هل تفهم؟ 'Jag uppfattade inte' = لم أفهم.",
    examples: [
      { sv: "Uppfattar du vad jag menar?", ar: "هل تُدرك ما أعنيه؟" },
      { sv: "Jag uppfattade inte vad du sa.", ar: "لم أفهم ما قلته." },
      { sv: "Det uppfattades fel av alla.", ar: "فهمه الجميع بطريقة خاطئة." },
    ],
    quizSentences: [
      { form: "presens", sentence: "Jag ___ inte din fråga.", answer: "uppfattar", translation: "لا أفهم سؤالك." },
      { form: "preteritum", sentence: "Han ___ hennes ironi.", answer: "uppfattade", translation: "أدرك تهكّمها." },
      { form: "imperativ", sentence: "___ situationen korrekt!", answer: "Uppfatta", translation: "استوعب الموقف بشكل صحيح!" },
    ],
  },
  {
    infinitiv: "erbjuda",
    presens: "erbjuder",
    preteritum: "erbjöd",
    supinum: "erbjudit",
    imperativ: "erbjud",
    futurum: "ska erbjuda",
    presensParticip: "erbjudande",
    perfektParticip: "erbjuden",
    passivPresens: "erbjuds",
    passivPreteritum: "erbjöds",
    translation: "يعرض / يُقدّم (عرضاً)",
    phonetic: "/ɛrˈbjʉːda/",
    group: "oregelbundet",
    level: "B1",
    category: "handel",
    imageUrl: IMG.work,
    notes: "فعل غير منتظم. 'Erbjudande' = عرض (اسم). 'Erbjuda hjälp' = يعرض المساعدة.",
    examples: [
      { sv: "Företaget erbjuder bra förmåner.", ar: "الشركة تقدّم مزايا جيدة." },
      { sv: "Han erbjöd henne jobbet.", ar: "عرض عليها الوظيفة." },
      { sv: "Erbjud din hjälp!", ar: "قدّم مساعدتك!" },
    ],
    quizSentences: [
      { form: "presens", sentence: "Skolan ___ gratis kurser.", answer: "erbjuder", translation: "المدرسة تقدّم دورات مجانية." },
      { form: "preteritum", sentence: "De ___ oss bra villkor.", answer: "erbjöd", translation: "قدّموا لنا شروطاً جيدة." },
      { form: "imperativ", sentence: "___ dem din kompetens!", answer: "Erbjud", translation: "قدّم لهم كفاءتك!" },
    ],
  },
  {
    infinitiv: "förklara",
    presens: "förklarar",
    preteritum: "förklarade",
    supinum: "förklarat",
    imperativ: "förklara",
    futurum: "ska förklara",
    presensParticip: "förklarande",
    perfektParticip: "förklarad",
    passivPresens: "förklaras",
    passivPreteritum: "förklarades",
    translation: "يشرح / يُوضّح",
    phonetic: "/fœrˈklɑːra/",
    group: "1",
    level: "A2",
    category: "kommunikation",
    imageUrl: IMG.school,
    notes: "فعل مجموعة 1 مهم جداً في التعليم. 'Kan du förklara?' = هل يمكنك الشرح؟",
    examples: [
      { sv: "Kan du förklara det en gång till?", ar: "هل يمكنك الشرح مرة أخرى؟" },
      { sv: "Läraren förklarade grammatiken.", ar: "شرح المعلم القواعد النحوية." },
      { sv: "Förklara vad du menar!", ar: "وضّح ما تعنيه!" },
    ],
    quizSentences: [
      { form: "presens", sentence: "Jag ___ reglerna för dig.", answer: "förklarar", translation: "سأشرح لك القواعد." },
      { form: "preteritum", sentence: "Han ___ varför han var sen.", answer: "förklarade", translation: "أوضح سبب تأخّره." },
      { form: "imperativ", sentence: "___ det lite enklare!", answer: "Förklara", translation: "اشرحه بطريقة أبسط!" },
    ],
  },
  {
    infinitiv: "bestämma sig",
    presens: "bestämmer sig",
    preteritum: "bestämde sig",
    supinum: "bestämt sig",
    imperativ: "bestäm dig",
    futurum: "ska bestämma sig",
    presensParticip: "bestämmandes",
    perfektParticip: "bestämt sig",
    passivPresens: null,
    passivPreteritum: null,
    translation: "يقرر / يتخذ قراراً",
    phonetic: "/bɛˈɛtːəma sej/",
    group: "2a",
    level: "A2",
    category: "kognition",
    imageUrl: IMG.work,
    notes: "فعل انعكاسي: يأتي دائماً مع 'sig/dig/mig'. 'Bestämma sig för' = يقرر شيئاً محدداً.",
    examples: [
      { sv: "Jag har bestämt mig för att lära svenska.", ar: "قررتُ تعلّم السويدية." },
      { sv: "Bestäm dig nu, vi väntar!", ar: "قرّر الآن، نحن ننتظر!" },
      { sv: "Hon bestämde sig för att sluta jobbet.", ar: "قرّرت الاستقالة من العمل." },
    ],
    quizSentences: [
      { form: "presens", sentence: "Jag ___ nu!", answer: "bestämmer mig", translation: "أنا أقرر الآن!" },
      { form: "preteritum", sentence: "De ___ för att flytta.", answer: "bestämde sig", translation: "قرّروا الانتقال." },
      { form: "imperativ", sentence: "___ du snabbt!", answer: "Bestäm dig", translation: "قرّر بسرعة!" },
    ],
  },
  {
    infinitiv: "klä",
    presens: "klär",
    preteritum: "klädde",
    supinum: "klätt",
    imperativ: "klä",
    futurum: "ska klä",
    presensParticip: "klädande",
    perfektParticip: "klädd",
    passivPresens: "kläs",
    passivPreteritum: "kläddes",
    translation: "يُلبس / يرتدي (يلبس الملابس)",
    phonetic: "/klɛː/",
    group: "oregelbundet",
    level: "A2",
    category: "hem",
    imageUrl: IMG.home,
    notes: "فعل غير منتظم. 'Klä sig' = يرتدي. 'Klä på sig' = يلبس. 'Klä av sig' = يخلع.",
    examples: [
      { sv: "Klä dig varmt, det är kallt ute!", ar: "البس دافئاً، الجو بارد خارجاً!" },
      { sv: "Hon klädde sig fort och gick.", ar: "ارتدت ملابسها بسرعة وذهبت." },
      { sv: "Klä barnen nu, vi ska gå.", ar: "البس الأطفال الآن، سنذهب." },
    ],
    quizSentences: [
      { form: "presens", sentence: "Jag ___ mig alltid i svart.", answer: "klär", translation: "أنا دائماً أرتدي اللون الأسود." },
      { form: "preteritum", sentence: "Hon ___ på sig och gick till jobbet.", answer: "klädde", translation: "ارتدت ملابسها وذهبت للعمل." },
      { form: "imperativ", sentence: "___ dig i tid, vi måste gå!", answer: "Klä", translation: "البس في الوقت المناسب، يجب أن نذهب!" },
    ],
  },
  {
    infinitiv: "prova",
    presens: "provar",
    preteritum: "provade",
    supinum: "provat",
    imperativ: "prova",
    futurum: "ska prova",
    presensParticip: "provande",
    perfektParticip: "provad",
    passivPresens: "provas",
    passivPreteritum: "provades",
    translation: "يُجرّب / يقيس (ملابس)",
    phonetic: "/ˈpruːva/",
    group: "1",
    level: "A1",
    category: "handel",
    imageUrl: IMG.shopping,
    notes: "فعل مجموعة 1. 'Provrum' = غرفة القياس. 'Prova på' = يتذوق / يجرّب شيئاً جديداً.",
    examples: [
      { sv: "Kan jag prova den här jackan?", ar: "هل يمكنني قياس هذه الجاكيت؟" },
      { sv: "Prova ny mat, det är roligt!", ar: "جرّب طعاماً جديداً، إنه ممتع!" },
      { sv: "Hon provade tio klänningar.", ar: "جرّبت عشرة فساتين." },
    ],
    quizSentences: [
      { form: "presens", sentence: "Jag ___ den här skon.", answer: "provar", translation: "أنا أقيس هذا الحذاء." },
      { form: "preteritum", sentence: "Vi ___ alla rätterna på menyn.", answer: "provade", translation: "جرّبنا كل الأطباق في القائمة." },
      { form: "imperativ", sentence: "___ den, du kanske gillar den!", answer: "Prova", translation: "جرّبها، ربما تعجبك!" },
    ],
  },
  {
    infinitiv: "sjunka",
    presens: "sjunker",
    preteritum: "sjönk",
    supinum: "sjunkit",
    imperativ: "sjunk",
    futurum: "ska sjunka",
    presensParticip: "sjunkande",
    perfektParticip: "sjunkit",
    passivPresens: "sjunks",
    passivPreteritum: "sjönks",
    translation: "يغرق / ينخفض",
    phonetic: "/ˈɧɵŋːka/",
    group: "oregelbundet",
    level: "B1",
    category: "rörelse",
    imageUrl: IMG.nature,
    notes: "فعل غير منتظم. 'Sjunka ner' = ينخفض. ضد 'stiga upp'. يُستخدم للأسعار أيضاً.",
    examples: [
      { sv: "Priserna sjunker just nu.", ar: "الأسعار تنخفض الآن." },
      { sv: "Skeppet sjönk under stormen.", ar: "غرق السفينة أثناء العاصفة." },
      { sv: "Mitt hjärta sjönk när jag hörde det.", ar: "انقلب قلبي حين سمعت ذلك." },
    ],
    quizSentences: [
      { form: "presens", sentence: "Temperaturen ___ varje natt.", answer: "sjunker", translation: "درجة الحرارة تنخفض كل ليلة." },
      { form: "preteritum", sentence: "Bolaget ___ under krisen.", answer: "sjönk", translation: "الشركة انهارت أثناء الأزمة." },
      { form: "imperativ", sentence: "Låt inte modet ___!", answer: "sjunka", translation: "لا تدع الحماس ينخفض!" },
    ],
  },
  {
    infinitiv: "förbereda",
    presens: "förbereder",
    preteritum: "förberedde",
    supinum: "förberett",
    imperativ: "förbered",
    futurum: "ska förbereda",
    presensParticip: "förberedande",
    perfektParticip: "förberedd",
    passivPresens: "förberedas",
    passivPreteritum: "förbereddes",
    translation: "يُعدّ / يُحضّر",
    phonetic: "/fœrˈbeːrəda/",
    group: "2a",
    level: "B1",
    category: "organisation",
    imageUrl: IMG.work,
    notes: "مجموعة 2a. 'Förberedelse' = إعداد. 'Förberedd för' = مستعد لـ.",
    examples: [
      { sv: "Jag förbereder presentationen.", ar: "أُعدّ العرض التقديمي." },
      { sv: "Förbered dig för intervjun.", ar: "استعدّ للمقابلة." },
      { sv: "Hon förberedde allt för gästerna.", ar: "أعدّت كل شيء للضيوف." },
    ],
    quizSentences: [
      { form: "presens", sentence: "Kocken ___ maten sedan en timme.", answer: "förbereder", translation: "الطاهي يُحضّر الطعام منذ ساعة." },
      { form: "preteritum", sentence: "Vi ___ oss noga inför resan.", answer: "förberedde", translation: "استعددنا جيداً قبل الرحلة." },
      { form: "imperativ", sentence: "___ dig för det värsta!", answer: "Förbered", translation: "استعدّ للأسوأ!" },
    ],
  },
  {
    infinitiv: "jämföra",
    presens: "jämför",
    preteritum: "jämförde",
    supinum: "jämfört",
    imperativ: "jämför",
    futurum: "ska jämföra",
    presensParticip: "jämförande",
    perfektParticip: "jämförd",
    passivPresens: "jämförs",
    passivPreteritum: "jämfördes",
    translation: "يُقارن",
    phonetic: "/ˈjɛmːˌføːra/",
    group: "2a",
    level: "B1",
    category: "kognition",
    imageUrl: IMG.school,
    notes: "مجموعة 2a. 'Jämför inte dig med andra!' = لا تُقارن نفسك بالآخرين!",
    examples: [
      { sv: "Jämför priserna innan du köper.", ar: "قارن الأسعار قبل الشراء." },
      { sv: "Jämför inte äpplen och päron.", ar: "لا تُقارن بين شيئين مختلفين (مثل: بين التفاح والكمثرى)." },
      { sv: "De jämförde resultaten.", ar: "قارنوا النتائج." },
    ],
    quizSentences: [
      { form: "presens", sentence: "Jag ___ alltid priser online.", answer: "jämför", translation: "أنا دائماً أُقارن الأسعار على الإنترنت." },
      { form: "preteritum", sentence: "Vi ___ de två alternativen.", answer: "jämförde", translation: "قارنّا الخيارين." },
      { form: "imperativ", sentence: "___ dessa produkter och välj!", answer: "Jämför", translation: "قارن هذه المنتجات واختر!" },
    ],
  },
  {
    infinitiv: "åka",
    presens: "åker",
    preteritum: "åkte",
    supinum: "åkt",
    imperativ: "åk",
    futurum: "ska åka",
    presensParticip: "åkande",
    perfektParticip: "åkt",
    passivPresens: "åks",
    passivPreteritum: "åktes",
    translation: "يذهب (بوسيلة نقل) / يسافر",
    phonetic: "/ˈoːka/",
    group: "2b",
    level: "A1",
    category: "rörelse",
    imageUrl: IMG.travel,
    notes: "مجموعة 2b. يُستخدم مع وسائل النقل. 'Åka bil' = يذهب بالسيارة. 'Åka hem' = يعود للمنزل.",
    examples: [
      { sv: "Vi åker tåg till Stockholm.", ar: "نذهب إلى ستوكهولم بالقطار." },
      { sv: "Åk hem nu, det är sent!", ar: "عُد للمنزل الآن، الوقت متأخر!" },
      { sv: "Jag åker ofta utomlands.", ar: "أسافر خارج البلاد كثيراً." },
    ],
    quizSentences: [
      { form: "presens", sentence: "Jag ___ tunnelbana varje dag.", answer: "åker", translation: "أركب المترو كل يوم." },
      { form: "preteritum", sentence: "Vi ___ buss till centrum.", answer: "åkte", translation: "ذهبنا بالأتوبيس إلى وسط المدينة." },
      { form: "imperativ", sentence: "___ dit nu!", answer: "Åk", translation: "اذهب إلى هناك الآن!" },
    ],
  },
  {
    infinitiv: "rengöra",
    presens: "rengör",
    preteritum: "rengjorde",
    supinum: "rengjort",
    imperativ: "rengör",
    futurum: "ska rengöra",
    presensParticip: "rengörande",
    perfektParticip: "rengjord",
    passivPresens: "rengörs",
    passivPreteritum: "rengjordes",
    translation: "يُنظّف (بشكل جيد)",
    phonetic: "/ˈreːnˌjøːra/",
    group: "oregelbundet",
    level: "B1",
    category: "hem",
    imageUrl: IMG.home,
    notes: "فعل غير منتظم. أقوى من 'städa'. 'Rengöra ordentligt' = ينظّف بدقة.",
    examples: [
      { sv: "Rengör badrummet noga.", ar: "نظّف الحمام بعناية." },
      { sv: "Han rengjorde hela köket.", ar: "نظّف المطبخ بالكامل." },
      { sv: "Rengöring är viktigt för hälsan.", ar: "النظافة مهمة للصحة." },
    ],
    quizSentences: [
      { form: "presens", sentence: "Hon ___ tandproteser dagligen.", answer: "rengör", translation: "هي تُنظّف طقم الأسنان يومياً." },
      { form: "preteritum", sentence: "Vi ___ hela lägenheten inför flytten.", answer: "rengjorde", translation: "نظّفنا الشقة بالكامل قبل الانتقال." },
      { form: "imperativ", sentence: "___ filtret nu!", answer: "Rengör", translation: "نظّف الفلتر الآن!" },
    ],
  },
  {
    infinitiv: "fixa",
    presens: "fixar",
    preteritum: "fixade",
    supinum: "fixat",
    imperativ: "fixa",
    futurum: "ska fixa",
    presensParticip: "fixande",
    perfektParticip: "fixad",
    passivPresens: "fixas",
    passivPreteritum: "fixades",
    translation: "يُصلح / يُرتّب / يحلّ",
    phonetic: "/ˈfɪkːsa/",
    group: "1",
    level: "A1",
    category: "hem",
    imageUrl: IMG.home,
    notes: "فعل يومي مجموعة 1 مستعار من الإنجليزية. شائع جداً. 'Fixa det!' = رتّبه / أصلحه!",
    examples: [
      { sv: "Kan du fixa bilen?", ar: "هل يمكنك إصلاح السيارة؟" },
      { sv: "Jag fixar det till imorgon.", ar: "سأُرتّبه بحلول الغد." },
      { sv: "Fixa problemet nu!", ar: "حلّ المشكلة الآن!" },
    ],
    quizSentences: [
      { form: "presens", sentence: "Jag ___ det snart, lugna dig!", answer: "fixar", translation: "سأُصلحه قريباً، اهدأ!" },
      { form: "preteritum", sentence: "Rörmokaren ___ röret.", answer: "fixade", translation: "السبّاك أصلح الأنبوب." },
      { form: "imperativ", sentence: "___ det innan chefen kommer!", answer: "Fixa", translation: "أصلحه قبل أن يأتي المدير!" },
    ],
  },
];

async function seed() {
  console.log("🌱 Adding extra verbs...");
  let added = 0;
  let skipped = 0;

  for (const v of extraVerbs) {
    try {
      await db.insert(verbsTable).values({
        infinitiv: v.infinitiv,
        presens: v.presens,
        preteritum: v.preteritum,
        supinum: v.supinum,
        imperativ: v.imperativ,
        futurum: v.futurum,
        presensParticip: v.presensParticip,
        perfektParticip: v.perfektParticip,
        passivPresens: v.passivPresens ?? null,
        passivPreteritum: v.passivPreteritum ?? null,
        translation: v.translation,
        phonetic: v.phonetic,
        group: v.group,
        level: v.level,
        category: v.category,
        imageUrl: v.imageUrl ?? null,
        notes: v.notes ?? null,
        examples: v.examples,
        quizSentences: v.quizSentences,
      });
      console.log(`✅ ${v.infinitiv} — ${v.translation}`);
      added++;
    } catch (e: unknown) {
      if (e instanceof Error && e.message.includes("unique")) {
        console.log(`⏭️  ${v.infinitiv} — already exists, skipped`);
        skipped++;
      } else {
        throw e;
      }
    }
  }

  console.log(`\n🎉 Added ${added} verbs (${skipped} skipped as duplicates)!`);
  process.exit(0);
}

seed().catch(e => { console.error(e); process.exit(1); });
