import { db, verbsTable } from "@workspace/db";

// Image URLs
const IMG = {
  speak:    "https://www.tripsavvy.com/thmb/DVttYFkCp1z2QyOTNE4vmoauL4A=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/GettyImages-683747793-b05182cacdd94fd793240cd4d6b4f9de.jpg",
  work:     "https://media.gettyimages.com/id/2198968434/photo/students-using-laptop-and-smartphone-in-malmo-sweden.jpg?s=612x612&w=0&k=20&c=CabGwvl3Hs5Mx7_rk0o7weZFg5t4KeAIzeUBNWIUED8=",
  food:     "https://media.gettyimages.com/id/2215023550/photo/traditional-swedish-meatballs-with-mashed-potatoes-pickles-and-cranberry-sauce.jpg?s=612x612&w=0&k=20&c=ZrzruuV67aiz_Eb-Howv1tBi1jw3yp-IvVGYl1MNzn0=",
  walk:     "https://i0.wp.com/atravelingfairy.com/wp-content/uploads/2022/11/DSC04547.jpg?w=1100&ssl=1",
  nature:   "https://images.pexels.com/photos/33077333/pexels-photo-33077333/free-photo-of-serene-swedish-forest-view-with-reflective-lake.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
  family:   "https://media.gettyimages.com/id/1300189216/photo/happy-family-eating-breakfast-seen-through-doorway-of-kitchen-at-home.jpg?s=612x612&w=0&k=20&c=tpaZ_wI_lBB7q4LN-GkHcQhkVleWUSO4qfb8_IxLeyE=",
  health:   "https://media.gettyimages.com/id/731741979/photo/doctor-walking-through-hospital-corridor.jpg?s=612x612&w=0&k=20&c=94a50kc59V322iYjCtqtAM2f6GmIW7T_hiDezvf5TsE=",
  school:   "https://media.gettyimages.com/id/1667940273/photo/portrait-of-smiling-female-student-with-friend-in-university.jpg?s=612x612&w=0&k=20&c=ePwPB-IfQ5SEUEQQMiN6LVIDDK6wTsAjHVH0b9Yy_5A=",
  city:     "https://thumbs.dreamstime.com/b/bright-interior-swedish-supermarket-food-products-discount-signs-shopping-carts-aisle-390370221.jpg",
  sleep:    "https://media.gettyimages.com/id/1278673078/photo/empty-table-and-chair-against-window-at-new-workplace.jpg?s=612x612&w=0&k=20&c=ktE2JWrBuWhe6vmk18E1QsnswMPllZ0s3v96a5ivPlo=",
  travel:   "https://media.gettyimages.com/id/1346700045/photo/stockholm-sweden-aerial-view.jpg?s=612x612&w=0&k=20&c=1nBJIdZcIuBDnO2bZCdSPXFtFdj8V5Hx2FqxAaVlFk0=",
  sport:    "https://images.pexels.com/photos/3621104/pexels-photo-3621104.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
  tech:     "https://media.gettyimages.com/id/1486196733/photo/developer-coding-on-laptop.jpg?s=612x612&w=0&k=20&c=HkXR0AwGMHH6GFjVg6D-0XeIlYh5vBRBx9A-kV2rRFc=",
  shopping: "https://images.pexels.com/photos/5632388/pexels-photo-5632388.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
};

const verbs = [
  // ══════════════════════════════════════════════════════════════════
  // GRUPP 1 — -ar verbs (talat, -ade, -at)
  // ══════════════════════════════════════════════════════════════════
  {
    infinitiv: "tala",
    presens: "talar",
    preteritum: "talade",
    supinum: "talat",
    imperativ: "tala",
    futurum: "ska tala",
    presensParticip: "talande",
    perfektParticip: "talad",
    passivPresens: "talas",
    passivPreteritum: "talades",
    translation: "يتكلم / يتحدث",
    phonetic: "/ˈtɑːla/",
    group: "1",
    level: "A1",
    category: "kommunikation",
    imageUrl: IMG.speak,
    notes: "الفعل الأكثر شيوعاً للتحدث. مجموعة 1: ينتهي الماضي بـ -ade والمصدر المضارع بـ -at.",
    examples: [
      { sv: "Jag talar svenska.", ar: "أنا أتحدث السويدية." },
      { sv: "De talade om vädret.", ar: "تحدثوا عن الطقس." },
      { sv: "Tala långsammare, tack!", ar: "تحدث بشكل أبطأ، من فضلك!" },
    ],
    quizSentences: [
      { form: "presens", sentence: "Jag ___ svenska varje dag.", answer: "talar", translation: "أنا أتحدث السويدية كل يوم." },
      { form: "preteritum", sentence: "Vi ___ med läraren igår.", answer: "talade", translation: "تحدثنا مع المعلم أمس." },
      { form: "imperativ", sentence: "___ lite tystare!", answer: "Tala", translation: "تحدث بصوت أهدأ!" },
    ],
  },
  {
    infinitiv: "arbeta",
    presens: "arbetar",
    preteritum: "arbetade",
    supinum: "arbetat",
    imperativ: "arbeta",
    futurum: "ska arbeta",
    presensParticip: "arbetande",
    perfektParticip: "arbetad",
    passivPresens: "arbetas",
    passivPreteritum: "arbetades",
    translation: "يعمل",
    phonetic: "/arˈbeːta/",
    group: "1",
    level: "A1",
    category: "arbete",
    imageUrl: IMG.work,
    notes: "فعل مجموعة 1 شائع جداً في السياق المهني.",
    examples: [
      { sv: "Jag arbetar på ett kontor.", ar: "أعمل في مكتب." },
      { sv: "Hon arbetade hela natten.", ar: "عملت طوال الليل." },
      { sv: "Vi kommer att arbeta tillsammans.", ar: "سنعمل معاً." },
    ],
    quizSentences: [
      { form: "presens", sentence: "Han ___ som lärare.", answer: "arbetar", translation: "هو يعمل كمعلم." },
      { form: "preteritum", sentence: "Vi ___ sent igår.", answer: "arbetade", translation: "عملنا متأخراً أمس." },
      { form: "futurum", sentence: "Jag ___ i Stockholm nästa år.", answer: "ska arbeta", translation: "سأعمل في ستوكهولم السنة القادمة." },
    ],
  },
  {
    infinitiv: "lyssna",
    presens: "lyssnar",
    preteritum: "lyssnade",
    supinum: "lyssnat",
    imperativ: "lyssna",
    futurum: "ska lyssna",
    presensParticip: "lyssnande",
    perfektParticip: "lyssnad",
    passivPresens: "lyssnas",
    passivPreteritum: "lyssnaddes",
    translation: "يستمع",
    phonetic: "/ˈlʏsːna/",
    group: "1",
    level: "A1",
    category: "kommunikation",
    imageUrl: IMG.speak,
    notes: "يُستخدم مع حرف الجر 'på' للدلالة على الاستماع لشيء ما.",
    examples: [
      { sv: "Lyssna på mig!", ar: "استمع إليّ!" },
      { sv: "Jag lyssnar på musik.", ar: "أنا أستمع إلى الموسيقى." },
      { sv: "Hon lyssnade noga.", ar: "استمعت بانتباه." },
    ],
    quizSentences: [
      { form: "presens", sentence: "Jag ___ på svenska poddar.", answer: "lyssnar", translation: "أستمع إلى بودكاست سويدي." },
      { form: "imperativ", sentence: "___ på läraren!", answer: "Lyssna", translation: "استمع للمعلم!" },
      { form: "preteritum", sentence: "De ___ på musik igår.", answer: "lyssnade", translation: "استمعوا إلى الموسيقى أمس." },
    ],
  },
  {
    infinitiv: "köpa",
    presens: "köper",
    preteritum: "köpte",
    supinum: "köpt",
    imperativ: "köp",
    futurum: "ska köpa",
    presensParticip: "köpande",
    perfektParticip: "köpt",
    passivPresens: "köps",
    passivPreteritum: "köptes",
    translation: "يشتري",
    phonetic: "/ˈɕøːpa/",
    group: "2b",
    level: "A1",
    category: "handel",
    imageUrl: IMG.city,
    notes: "مجموعة 2b. الأمر: köp (بدون -a).",
    examples: [
      { sv: "Jag köper mat i affären.", ar: "أشتري الطعام من المتجر." },
      { sv: "Hon köpte en ny bok.", ar: "اشترت كتاباً جديداً." },
      { sv: "Köp mjölk på vägen hem!", ar: "اشتر حليباً في الطريق إلى المنزل!" },
    ],
    quizSentences: [
      { form: "presens", sentence: "Han ___ en ny jacka idag.", answer: "köper", translation: "هو يشتري جاكيت جديداً اليوم." },
      { form: "preteritum", sentence: "Vi ___ mat igår.", answer: "köpte", translation: "اشترينا طعاماً أمس." },
      { form: "imperativ", sentence: "___ inte för mycket!", answer: "Köp", translation: "لا تشتر كثيراً!" },
    ],
  },
  {
    infinitiv: "stänga",
    presens: "stänger",
    preteritum: "stängde",
    supinum: "stängt",
    imperativ: "stäng",
    futurum: "ska stänga",
    presensParticip: "stängande",
    perfektParticip: "stängd",
    passivPresens: "stängs",
    passivPreteritum: "stängdes",
    translation: "يُغلق",
    phonetic: "/ˈstɛŋːa/",
    group: "2a",
    level: "A2",
    category: "rörelse",
    imageUrl: IMG.city,
    notes: "مجموعة 2a. ضد: öppna (يفتح).",
    examples: [
      { sv: "Stäng dörren!", ar: "أغلق الباب!" },
      { sv: "Affären stänger klockan åtta.", ar: "المحل يغلق الساعة الثامنة." },
      { sv: "Han stängde fönstret.", ar: "أغلق النافذة." },
    ],
    quizSentences: [
      { form: "presens", sentence: "Biblioteket ___ tidigt på lördagar.", answer: "stänger", translation: "المكتبة تغلق مبكراً أيام السبت." },
      { form: "imperativ", sentence: "___ dörren, det är kallt!", answer: "Stäng", translation: "أغلق الباب، إنه بارد!" },
      { form: "preteritum", sentence: "Hon ___ datorn och gick hem.", answer: "stängde", translation: "أغلقت الحاسوب وذهبت إلى المنزل." },
    ],
  },
  {
    infinitiv: "titta",
    presens: "tittar",
    preteritum: "tittade",
    supinum: "tittat",
    imperativ: "titta",
    futurum: "ska titta",
    presensParticip: "tittande",
    perfektParticip: "tittad",
    passivPresens: "tittas",
    passivPreteritum: "tittades",
    translation: "ينظر / يشاهد",
    phonetic: "/ˈtɪtːa/",
    group: "1",
    level: "A1",
    category: "sinnen",
    imageUrl: IMG.school,
    notes: "يُستخدم مع 'på' للنظر إلى شيء: titta på TV (يشاهد التلفاز).",
    examples: [
      { sv: "Titta på mig!", ar: "انظر إليّ!" },
      { sv: "Vi tittar på film.", ar: "نحن نشاهد فيلماً." },
      { sv: "Han tittade ut genom fönstret.", ar: "نظر من خلال النافذة." },
    ],
    quizSentences: [
      { form: "presens", sentence: "Jag ___ på nyheter varje kväll.", answer: "tittar", translation: "أشاهد الأخبار كل مساء." },
      { form: "preteritum", sentence: "De ___ på fotboll igår.", answer: "tittade", translation: "شاهدوا كرة القدم أمس." },
      { form: "imperativ", sentence: "___ hit!", answer: "Titta", translation: "انظر هنا!" },
    ],
  },
  {
    infinitiv: "laga",
    presens: "lagar",
    preteritum: "lagade",
    supinum: "lagat",
    imperativ: "laga",
    futurum: "ska laga",
    presensParticip: "lagande",
    perfektParticip: "lagad",
    passivPresens: "lagas",
    passivPreteritum: "lagades",
    translation: "يطبخ / يصلح",
    phonetic: "/ˈlɑːɡa/",
    group: "1",
    level: "A1",
    category: "mat",
    imageUrl: IMG.food,
    notes: "laga mat = يطبخ الطعام. laga bilen = يصلح السيارة.",
    examples: [
      { sv: "Mamma lagar mat.", ar: "الأم تطبخ الطعام." },
      { sv: "Kan du laga cykeln?", ar: "هل يمكنك إصلاح الدراجة؟" },
      { sv: "Jag lagade köttbullar igår.", ar: "طبخت كرات اللحم أمس." },
    ],
    quizSentences: [
      { form: "presens", sentence: "Hon ___ mat varje dag.", answer: "lagar", translation: "هي تطبخ الطعام كل يوم." },
      { form: "preteritum", sentence: "Pappa ___ fisk till middag.", answer: "lagade", translation: "الأب طبخ السمك للعشاء." },
      { form: "futurum", sentence: "Jag ___ pannkakor imorgon.", answer: "ska laga", translation: "سأطبخ الفطائر غداً." },
    ],
  },
  {
    infinitiv: "fråga",
    presens: "frågar",
    preteritum: "frågade",
    supinum: "frågat",
    imperativ: "fråga",
    futurum: "ska fråga",
    presensParticip: "frågande",
    perfektParticip: "frågad",
    passivPresens: "frågas",
    passivPreteritum: "frågades",
    translation: "يسأل",
    phonetic: "/ˈfrɔːɡa/",
    group: "1",
    level: "A1",
    category: "kommunikation",
    imageUrl: IMG.school,
    notes: "ضده: svara (يجيب). fråga om = يسأل عن.",
    examples: [
      { sv: "Fråga läraren om du inte förstår.", ar: "اسأل المعلم إن لم تفهم." },
      { sv: "Jag frågade om vägen.", ar: "سألت عن الطريق." },
      { sv: "Hon frågade vad klockan är.", ar: "سألت كم الساعة." },
    ],
    quizSentences: [
      { form: "presens", sentence: "Varför ___ du alltid?", answer: "frågar", translation: "لماذا تسأل دائماً؟" },
      { form: "preteritum", sentence: "Han ___ om priset.", answer: "frågade", translation: "سأل عن السعر." },
      { form: "imperativ", sentence: "___ om du behöver hjälp!", answer: "Fråga", translation: "اسأل إذا احتجت مساعدة!" },
    ],
  },

  // ══════════════════════════════════════════════════════════════════
  // GRUPP 2a — short -er verbs (-de, -t)
  // ══════════════════════════════════════════════════════════════════
  {
    infinitiv: "ringa",
    presens: "ringer",
    preteritum: "ringde",
    supinum: "ringt",
    imperativ: "ring",
    futurum: "ska ringa",
    presensParticip: "ringande",
    perfektParticip: "ringt",
    passivPresens: "rings",
    passivPreteritum: "ringdes",
    translation: "يتصل (هاتفياً) / يرن",
    phonetic: "/ˈrɪŋːa/",
    group: "2a",
    level: "A1",
    category: "kommunikation",
    imageUrl: IMG.speak,
    notes: "مجموعة 2a — ينتهي الماضي بـ -de. ringa till = يتصل بـ.",
    examples: [
      { sv: "Jag ringer dig ikväll.", ar: "سأتصل بك الليلة." },
      { sv: "Ring ambulansen!", ar: "اتصل بالإسعاف!" },
      { sv: "Hon ringde mig tre gånger.", ar: "اتصلت بي ثلاث مرات." },
    ],
    quizSentences: [
      { form: "presens", sentence: "Jag ___ mamma varje söndag.", answer: "ringer", translation: "أتصل بأمي كل أحد." },
      { form: "preteritum", sentence: "Han ___ polisen.", answer: "ringde", translation: "اتصل بالشرطة." },
      { form: "imperativ", sentence: "___ mig när du är framme!", answer: "Ring", translation: "اتصل بي عندما تصل!" },
    ],
  },
  {
    infinitiv: "läsa",
    presens: "läser",
    preteritum: "läste",
    supinum: "läst",
    imperativ: "läs",
    futurum: "ska läsa",
    presensParticip: "läsande",
    perfektParticip: "läst",
    passivPresens: "läses",
    passivPreteritum: "lästes",
    translation: "يقرأ / يدرس",
    phonetic: "/ˈlɛːsa/",
    group: "2b",
    level: "A1",
    category: "skola",
    imageUrl: IMG.school,
    notes: "مجموعة 2b. läsa + ämne = يدرس مادة. الأمر: läs.",
    examples: [
      { sv: "Jag läser en bok.", ar: "أنا أقرأ كتاباً." },
      { sv: "Han läser medicin.", ar: "هو يدرس الطب." },
      { sv: "Läs texten noga!", ar: "اقرأ النص بعناية!" },
    ],
    quizSentences: [
      { form: "presens", sentence: "Hon ___ tidningen varje morgon.", answer: "läser", translation: "هي تقرأ الجريدة كل صباح." },
      { form: "preteritum", sentence: "Vi ___ boken i skolan.", answer: "läste", translation: "قرأنا الكتاب في المدرسة." },
      { form: "imperativ", sentence: "___ kapitel tre!", answer: "Läs", translation: "اقرأ الفصل الثالث!" },
    ],
  },

  // ══════════════════════════════════════════════════════════════════
  // GRUPP 3 — short verbs (-r, -dde, -tt)
  // ══════════════════════════════════════════════════════════════════
  {
    infinitiv: "bo",
    presens: "bor",
    preteritum: "bodde",
    supinum: "bott",
    imperativ: "bo",
    futurum: "ska bo",
    presensParticip: "boende",
    perfektParticip: "bott",
    passivPresens: "bos",
    passivPreteritum: "boddes",
    translation: "يسكن / يعيش",
    phonetic: "/buː/",
    group: "3",
    level: "A1",
    category: "hem",
    imageUrl: IMG.nature,
    notes: "مجموعة 3 — أفعال قصيرة. الماضي: -dde.",
    examples: [
      { sv: "Jag bor i Sverige.", ar: "أسكن في السويد." },
      { sv: "Han bodde i Göteborg.", ar: "عاش في يوتيبوري." },
      { sv: "Var bor du?", ar: "أين تسكن؟" },
    ],
    quizSentences: [
      { form: "presens", sentence: "Vi ___ nära skolan.", answer: "bor", translation: "نسكن قرب المدرسة." },
      { form: "preteritum", sentence: "Hon ___ i London för länge sedan.", answer: "bodde", translation: "سكنت في لندن منذ زمن طويل." },
      { form: "futurum", sentence: "Jag ___ i Stockholm nästa år.", answer: "ska bo", translation: "سأسكن في ستوكهولم السنة القادمة." },
    ],
  },
  {
    infinitiv: "tro",
    presens: "tror",
    preteritum: "trodde",
    supinum: "trott",
    imperativ: "tro",
    futurum: "ska tro",
    presensParticip: "troende",
    perfektParticip: "trott",
    passivPresens: "tros",
    passivPreteritum: "troddes",
    translation: "يعتقد / يؤمن",
    phonetic: "/truː/",
    group: "3",
    level: "A2",
    category: "tanke",
    imageUrl: IMG.school,
    notes: "مجموعة 3. tro att = يعتقد أن. tro på = يؤمن بـ.",
    examples: [
      { sv: "Jag tror att det regnar imorgon.", ar: "أعتقد أنه سيمطر غداً." },
      { sv: "Tror du på mig?", ar: "هل تصدقني / تؤمن بي؟" },
      { sv: "Han trodde att hon var sjuk.", ar: "اعتقد أنها كانت مريضة." },
    ],
    quizSentences: [
      { form: "presens", sentence: "Jag ___ att han har rätt.", answer: "tror", translation: "أعتقد أنه على حق." },
      { form: "preteritum", sentence: "Vi ___ att det var sant.", answer: "trodde", translation: "اعتقدنا أن ذلك كان صحيحاً." },
    ],
  },

  // ══════════════════════════════════════════════════════════════════
  // OREGELBUNDET (Irregular)
  // ══════════════════════════════════════════════════════════════════
  {
    infinitiv: "vara",
    presens: "är",
    preteritum: "var",
    supinum: "varit",
    imperativ: "var",
    futurum: "ska vara / kommer att vara",
    presensParticip: "varande",
    perfektParticip: "varit",
    passivPresens: null,
    passivPreteritum: null,
    translation: "يكون / يوجد",
    phonetic: "/ˈvɑːra/",
    group: "oregelbundet",
    level: "A1",
    category: "kärnverb",
    imageUrl: IMG.school,
    notes: "الفعل الأساسي في السويدية. غير منتظم تماماً: presens = är (وليس *varar).",
    examples: [
      { sv: "Jag är student.", ar: "أنا طالب." },
      { sv: "Det var kallt igår.", ar: "كان الجو بارداً أمس." },
      { sv: "Var snäll!", ar: "كن لطيفاً!" },
    ],
    quizSentences: [
      { form: "presens", sentence: "Hon ___ lärare.", answer: "är", translation: "هي معلمة." },
      { form: "preteritum", sentence: "Vi ___ trötta efter resan.", answer: "var", translation: "كنا متعبين بعد الرحلة." },
      { form: "imperativ", sentence: "___ försiktig!", answer: "Var", translation: "كن حذراً!" },
    ],
  },
  {
    infinitiv: "ha",
    presens: "har",
    preteritum: "hade",
    supinum: "haft",
    imperativ: "ha",
    futurum: "ska ha",
    presensParticip: "havande",
    perfektParticip: "haft",
    passivPresens: null,
    passivPreteritum: null,
    translation: "يملك / لديه",
    phonetic: "/hɑː/",
    group: "oregelbundet",
    level: "A1",
    category: "kärnverb",
    imageUrl: IMG.family,
    notes: "الفعل المساعد الأساسي. يُستخدم لبناء المضارع التام: jag har ätit = أكلت.",
    examples: [
      { sv: "Jag har en hund.", ar: "لدي كلب." },
      { sv: "Har du tid?", ar: "هل لديك وقت؟" },
      { sv: "Vi har haft tur.", ar: "لقد كنا محظوظين." },
    ],
    quizSentences: [
      { form: "presens", sentence: "Hon ___ två katter.", answer: "har", translation: "لديها قطتان." },
      { form: "preteritum", sentence: "De ___ inte råd.", answer: "hade", translation: "لم يكن لديهم المال الكافي." },
      { form: "supinum", sentence: "Jag ___ aldrig smakat köttbullar.", answer: "har ... haft / har aldrig ätit", translation: "لم أتذوق كرات اللحم قط." },
    ],
  },
  {
    infinitiv: "gå",
    presens: "går",
    preteritum: "gick",
    supinum: "gått",
    imperativ: "gå",
    futurum: "ska gå",
    presensParticip: "gående",
    perfektParticip: "gången",
    passivPresens: "gås",
    passivPreteritum: null,
    translation: "يمشي / يذهب",
    phonetic: "/ɡɔː/",
    group: "oregelbundet",
    level: "A1",
    category: "rörelse",
    imageUrl: IMG.walk,
    notes: "الماضي 'gick' غير منتظم تماماً. gå till = يذهب إلى. gå på = يحضر.",
    examples: [
      { sv: "Jag går till skolan.", ar: "أذهب إلى المدرسة." },
      { sv: "Vi gick i parken.", ar: "مشينا في الحديقة." },
      { sv: "Gå rakt fram!", ar: "امش مستقيماً!" },
    ],
    quizSentences: [
      { form: "presens", sentence: "Han ___ till jobbet varje dag.", answer: "går", translation: "هو يذهب إلى العمل كل يوم." },
      { form: "preteritum", sentence: "Vi ___ hem tidigt.", answer: "gick", translation: "ذهبنا إلى المنزل مبكراً." },
      { form: "imperativ", sentence: "___ och köp mjölk!", answer: "Gå", translation: "اذهب واشتر حليباً!" },
    ],
  },
  {
    infinitiv: "komma",
    presens: "kommer",
    preteritum: "kom",
    supinum: "kommit",
    imperativ: "kom",
    futurum: "ska komma / kommer att komma",
    presensParticip: "kommande",
    perfektParticip: "kommen",
    passivPresens: null,
    passivPreteritum: null,
    translation: "يأتي / يصل",
    phonetic: "/ˈkɔmːa/",
    group: "oregelbundet",
    level: "A1",
    category: "rörelse",
    imageUrl: IMG.walk,
    notes: "مهم: 'kommer att + infinitiv' = المستقبل القريب. 'kom' هو الماضي الغير منتظم.",
    examples: [
      { sv: "Kom hit!", ar: "تعال إلى هنا!" },
      { sv: "När kommer du?", ar: "متى ستأتي؟" },
      { sv: "Hon kom sent till mötet.", ar: "وصلت متأخرة إلى الاجتماع." },
    ],
    quizSentences: [
      { form: "presens", sentence: "Tåget ___ klockan tre.", answer: "kommer", translation: "القطار يصل الساعة الثالثة." },
      { form: "preteritum", sentence: "Han ___ inte igår.", answer: "kom", translation: "لم يأتِ أمس." },
      { form: "imperativ", sentence: "___ och hjälp mig!", answer: "Kom", translation: "تعال وساعدني!" },
    ],
  },
  {
    infinitiv: "se",
    presens: "ser",
    preteritum: "såg",
    supinum: "sett",
    imperativ: "se",
    futurum: "ska se",
    presensParticip: "seende",
    perfektParticip: "sedd",
    passivPresens: "ses",
    passivPreteritum: "sågst",
    translation: "يرى / يشاهد",
    phonetic: "/seː/",
    group: "oregelbundet",
    level: "A1",
    category: "sinnen",
    imageUrl: IMG.school,
    notes: "غير منتظم: såg (ماضٍ). se ut = يبدو. vi ses = إلى اللقاء.",
    examples: [
      { sv: "Jag ser dig!", ar: "أراك!" },
      { sv: "Vi såg en film igår.", ar: "شاهدنا فيلماً أمس." },
      { sv: "Vi ses imorgon!", ar: "إلى اللقاء غداً!" },
    ],
    quizSentences: [
      { form: "presens", sentence: "Kan du ___ tavlan?", answer: "se", translation: "هل يمكنك رؤية اللوحة؟" },
      { form: "preteritum", sentence: "Jag ___ honom igår.", answer: "såg", translation: "رأيته أمس." },
      { form: "presens (3sg)", sentence: "Hon ___ trött ut.", answer: "ser", translation: "تبدو متعبة." },
    ],
  },
  {
    infinitiv: "ta",
    presens: "tar",
    preteritum: "tog",
    supinum: "tagit",
    imperativ: "ta",
    futurum: "ska ta",
    presensParticip: "tagande",
    perfektParticip: "tagen",
    passivPresens: "tas",
    passivPreteritum: "togs",
    translation: "يأخذ",
    phonetic: "/tɑː/",
    group: "oregelbundet",
    level: "A1",
    category: "rörelse",
    imageUrl: IMG.walk,
    notes: "ta bussen = يركب الحافلة. ta tid = يستغرق وقتاً. ماضٍ: tog.",
    examples: [
      { sv: "Ta en kaka!", ar: "خذ كعكة!" },
      { sv: "Jag tar bussen till jobbet.", ar: "أركب الحافلة إلى العمل." },
      { sv: "Han tog sin jacka.", ar: "أخذ جاكيته." },
    ],
    quizSentences: [
      { form: "presens", sentence: "Hon ___ alltid tåget.", answer: "tar", translation: "هي دائماً تركب القطار." },
      { form: "preteritum", sentence: "Vi ___ en fika.", answer: "tog", translation: "أخذنا استراحة قهوة." },
      { form: "imperativ", sentence: "___ det lugnt!", answer: "Ta", translation: "هدّئ من روعك!" },
    ],
  },
  {
    infinitiv: "ge",
    presens: "ger",
    preteritum: "gav",
    supinum: "gett",
    imperativ: "ge",
    futurum: "ska ge",
    presensParticip: "givande",
    perfektParticip: "given",
    passivPresens: "ges",
    passivPreteritum: "gavs",
    translation: "يعطي",
    phonetic: "/jeː/",
    group: "oregelbundet",
    level: "A1",
    category: "kommunikation",
    imageUrl: IMG.family,
    notes: "ماضٍ: gav. ge sig = يستسلم. ge upp = يستسلم.",
    examples: [
      { sv: "Ge mig boken!", ar: "أعطني الكتاب!" },
      { sv: "Han gav henne en blomma.", ar: "أعطاها وردة." },
      { sv: "Jag ska ge dig ett tips.", ar: "سأعطيك نصيحة." },
    ],
    quizSentences: [
      { form: "presens", sentence: "Läraren ___ oss läxor.", answer: "ger", translation: "المعلم يعطينا واجباً." },
      { form: "preteritum", sentence: "Mamma ___ mig en present.", answer: "gav", translation: "الأم أعطتني هدية." },
      { form: "imperativ", sentence: "___ mig en chans!", answer: "Ge", translation: "أعطني فرصة!" },
    ],
  },
  {
    infinitiv: "veta",
    presens: "vet",
    preteritum: "visste",
    supinum: "vetat",
    imperativ: "vet",
    futurum: "ska veta",
    presensParticip: "vetande",
    perfektParticip: "vetat",
    passivPresens: null,
    passivPreteritum: null,
    translation: "يعرف / يعلم",
    phonetic: "/ˈveːta/",
    group: "oregelbundet",
    level: "A1",
    category: "tanke",
    imageUrl: IMG.school,
    notes: "مهم: المضارع 'vet' (لا 'vetar'). ماضٍ: visste.",
    examples: [
      { sv: "Jag vet inte.", ar: "لا أعرف." },
      { sv: "Vet du var han bor?", ar: "هل تعرف أين يسكن؟" },
      { sv: "Hon visste svaret.", ar: "كانت تعرف الإجابة." },
    ],
    quizSentences: [
      { form: "presens", sentence: "Jag ___ inte vad det betyder.", answer: "vet", translation: "لا أعرف ماذا يعني." },
      { form: "preteritum", sentence: "Vi ___ inte att det var svårt.", answer: "visste", translation: "لم نكن نعلم أن ذلك كان صعباً." },
    ],
  },
  {
    infinitiv: "vilja",
    presens: "vill",
    preteritum: "ville",
    supinum: "velat",
    imperativ: "–",
    futurum: "ska vilja",
    presensParticip: "villjande",
    perfektParticip: "velat",
    passivPresens: null,
    passivPreteritum: null,
    translation: "يريد",
    phonetic: "/ˈvɪlːja/",
    group: "oregelbundet",
    level: "A1",
    category: "känsla",
    imageUrl: IMG.family,
    notes: "فعل مودالي — لا أمر له. vill + infinitiv: Jag vill äta = أريد أن آكل.",
    examples: [
      { sv: "Jag vill lära mig svenska.", ar: "أريد أن أتعلم السويدية." },
      { sv: "Vad vill du ha?", ar: "ماذا تريد؟" },
      { sv: "Hon ville inte komma.", ar: "لم تكن تريد أن تأتي." },
    ],
    quizSentences: [
      { form: "presens", sentence: "Jag ___ ha en kopp kaffe.", answer: "vill", translation: "أريد كوب قهوة." },
      { form: "preteritum", sentence: "Han ___ inte äta.", answer: "ville", translation: "لم يكن يريد أن يأكل." },
    ],
  },
  {
    infinitiv: "kunna",
    presens: "kan",
    preteritum: "kunde",
    supinum: "kunnat",
    imperativ: "–",
    futurum: "ska kunna",
    presensParticip: "kunnande",
    perfektParticip: "kunnat",
    passivPresens: null,
    passivPreteritum: null,
    translation: "يستطيع / يقدر",
    phonetic: "/ˈkɵnːa/",
    group: "oregelbundet",
    level: "A1",
    category: "kärnverb",
    imageUrl: IMG.school,
    notes: "فعل مودالي. kan + infinitiv = يستطيع. kan du? = هل تستطيع؟",
    examples: [
      { sv: "Kan du tala svenska?", ar: "هل تستطيع التحدث السويدية؟" },
      { sv: "Jag kan inte komma.", ar: "لا أستطيع المجيء." },
      { sv: "Hon kunde simma när hon var liten.", ar: "كانت تستطيع السباحة وهي صغيرة." },
    ],
    quizSentences: [
      { form: "presens", sentence: "Jag ___ inte förstå.", answer: "kan", translation: "لا أستطيع الفهم." },
      { form: "preteritum", sentence: "Han ___ inte sova.", answer: "kunde", translation: "لم يستطع النوم." },
    ],
  },
  {
    infinitiv: "skriva",
    presens: "skriver",
    preteritum: "skrev",
    supinum: "skrivit",
    imperativ: "skriv",
    futurum: "ska skriva",
    presensParticip: "skrivande",
    perfektParticip: "skriven",
    passivPresens: "skrivs",
    passivPreteritum: "skrevs",
    translation: "يكتب",
    phonetic: "/ˈskriːva/",
    group: "oregelbundet",
    level: "A1",
    category: "kommunikation",
    imageUrl: IMG.school,
    notes: "غير منتظم. skriva ett brev = يكتب رسالة. الأمر: skriv.",
    examples: [
      { sv: "Jag skriver ett brev.", ar: "أكتب رسالة." },
      { sv: "Skriv ditt namn här!", ar: "اكتب اسمك هنا!" },
      { sv: "Hon skrev ett långt mejl.", ar: "كتبت بريداً إلكترونياً طويلاً." },
    ],
    quizSentences: [
      { form: "presens", sentence: "Han ___ en roman.", answer: "skriver", translation: "هو يكتب رواية." },
      { form: "preteritum", sentence: "Jag ___ ett brev till min familj.", answer: "skrev", translation: "كتبت رسالة لعائلتي." },
      { form: "imperativ", sentence: "___ tydligare!", answer: "Skriv", translation: "اكتب بشكل أوضح!" },
    ],
  },
  {
    infinitiv: "äta",
    presens: "äter",
    preteritum: "åt",
    supinum: "ätit",
    imperativ: "ät",
    futurum: "ska äta",
    presensParticip: "ätande",
    perfektParticip: "äten",
    passivPresens: "äts",
    passivPreteritum: "åts",
    translation: "يأكل",
    phonetic: "/ˈɛːta/",
    group: "oregelbundet",
    level: "A1",
    category: "mat",
    imageUrl: IMG.food,
    notes: "غير منتظم. الماضي: åt. äta frukost/lunch/middag = يتناول الفطور/الغداء/العشاء.",
    examples: [
      { sv: "Jag äter frukost varje dag.", ar: "آكل الفطور كل يوم." },
      { sv: "Vi åt middag klockan sex.", ar: "تناولنا العشاء الساعة السادسة." },
      { sv: "Ät upp maten!", ar: "أكمل طعامك!" },
    ],
    quizSentences: [
      { form: "presens", sentence: "Vad ___ du till lunch?", answer: "äter", translation: "ماذا تأكل على الغداء؟" },
      { form: "preteritum", sentence: "Vi ___ pizza igår.", answer: "åt", translation: "أكلنا بيتزا أمس." },
      { form: "imperativ", sentence: "___ mer grönsaker!", answer: "Ät", translation: "كل المزيد من الخضار!" },
    ],
  },
  {
    infinitiv: "dricka",
    presens: "dricker",
    preteritum: "drack",
    supinum: "druckit",
    imperativ: "drick",
    futurum: "ska dricka",
    presensParticip: "drickande",
    perfektParticip: "drucken",
    passivPresens: "dricks",
    passivPreteritum: "dracks",
    translation: "يشرب",
    phonetic: "/ˈdrɪkːa/",
    group: "oregelbundet",
    level: "A1",
    category: "mat",
    imageUrl: IMG.food,
    notes: "غير منتظم. الماضي: drack. dricka kaffe/te/vatten = يشرب قهوة/شاياً/ماء.",
    examples: [
      { sv: "Jag dricker kaffe på morgonen.", ar: "أشرب القهوة في الصباح." },
      { sv: "Drick mer vatten!", ar: "اشرب المزيد من الماء!" },
      { sv: "Han drack te på kvällen.", ar: "شرب شاياً في المساء." },
    ],
    quizSentences: [
      { form: "presens", sentence: "Vad ___ du vanligtvis?", answer: "dricker", translation: "ماذا تشرب عادةً؟" },
      { form: "preteritum", sentence: "Vi ___ juice till frukost.", answer: "drack", translation: "شربنا عصيراً على الفطور." },
      { form: "imperativ", sentence: "___ upp din mjölk!", answer: "Drick", translation: "اشرب حليبك!" },
    ],
  },
  {
    infinitiv: "sova",
    presens: "sover",
    preteritum: "sov",
    supinum: "sovit",
    imperativ: "sov",
    futurum: "ska sova",
    presensParticip: "sovande",
    perfektParticip: "sovet",
    passivPresens: null,
    passivPreteritum: null,
    translation: "ينام",
    phonetic: "/ˈsuːva/",
    group: "oregelbundet",
    level: "A1",
    category: "vardag",
    imageUrl: IMG.sleep,
    notes: "غير منتظم. الماضي: sov. sova gott = ينام جيداً.",
    examples: [
      { sv: "Jag sover åtta timmar.", ar: "أنام ثماني ساعات." },
      { sv: "Barnet sov länge.", ar: "نام الطفل طويلاً." },
      { sv: "Sov gott!", ar: "نم هنيئاً!" },
    ],
    quizSentences: [
      { form: "presens", sentence: "Han ___ fortfarande.", answer: "sover", translation: "لا يزال نائماً." },
      { form: "preteritum", sentence: "Jag ___ dåligt igår.", answer: "sov", translation: "نمت بشكل سيء أمس." },
      { form: "imperativ", sentence: "___ nu, det är sent!", answer: "Sov", translation: "نم الآن، الوقت متأخر!" },
    ],
  },
  {
    infinitiv: "förstå",
    presens: "förstår",
    preteritum: "förstod",
    supinum: "förstått",
    imperativ: "förstå",
    futurum: "ska förstå",
    presensParticip: "förstående",
    perfektParticip: "förstådd",
    passivPresens: "förstås",
    passivPreteritum: "förstods",
    translation: "يفهم",
    phonetic: "/fœˈstɔː/",
    group: "oregelbundet",
    level: "A1",
    category: "tanke",
    imageUrl: IMG.school,
    notes: "غير منتظم. الماضي: förstod. förstå sig på = يفهم في مجال.",
    examples: [
      { sv: "Förstår du?", ar: "هل تفهم؟" },
      { sv: "Jag förstår inte.", ar: "لا أفهم." },
      { sv: "Han förstod äntligen.", ar: "فهم أخيراً." },
    ],
    quizSentences: [
      { form: "presens", sentence: "Jag ___ inte den här meningen.", answer: "förstår", translation: "لا أفهم هذه الجملة." },
      { form: "preteritum", sentence: "Vi ___ inte frågan.", answer: "förstod", translation: "لم نفهم السؤال." },
    ],
  },

  // ══════════════════════════════════════════════════════════════════
  // NEW VERBS — GRUPP 1 (-ar, -ade, -at)
  // ══════════════════════════════════════════════════════════════════
  {
    infinitiv: "handla",
    presens: "handlar",
    preteritum: "handlade",
    supinum: "handlat",
    imperativ: "handla",
    futurum: "ska handla",
    presensParticip: "handlande",
    perfektParticip: "handlad",
    passivPresens: "handlas",
    passivPreteritum: "handlades",
    translation: "يتسوق / يتصرف",
    phonetic: "/ˈhandla/",
    group: "1",
    level: "A1",
    category: "handel",
    imageUrl: IMG.shopping,
    notes: "مجموعة 1. handla mat = يتسوق الطعام. يُستخدم أيضاً بمعنى يتصرف.",
    examples: [
      { sv: "Jag handlar varje lördag.", ar: "أتسوق كل سبت." },
      { sv: "Hon handlade på nätet.", ar: "تسوقت عبر الإنترنت." },
      { sv: "Handla snabbt, affären stänger!", ar: "تسوق بسرعة، المتجر سيغلق!" },
    ],
    quizSentences: [
      { form: "presens", sentence: "Vi ___ på stormarknaden.", answer: "handlar", translation: "نتسوق في السوبرماركت." },
      { form: "preteritum", sentence: "Hon ___ nya kläder igår.", answer: "handlade", translation: "تسوقت ملابس جديدة أمس." },
      { form: "imperativ", sentence: "___ inte för mycket!", answer: "Handla", translation: "لا تتسوق أكثر مما تحتاج!" },
    ],
  },
  {
    infinitiv: "berätta",
    presens: "berättar",
    preteritum: "berättade",
    supinum: "berättat",
    imperativ: "berätta",
    futurum: "ska berätta",
    presensParticip: "berättande",
    perfektParticip: "berättad",
    passivPresens: "berättas",
    passivPreteritum: "berättades",
    translation: "يحكي / يروي / يخبر",
    phonetic: "/bɛˈrɛtːa/",
    group: "1",
    level: "A2",
    category: "kommunikation",
    imageUrl: IMG.speak,
    notes: "مجموعة 1. berätta för någon = يخبر شخصاً ما. berätta om = يحكي عن.",
    examples: [
      { sv: "Berätta vad som hände!", ar: "أخبرني ماذا حدث!" },
      { sv: "Hon berättade en rolig historia.", ar: "روت قصة مضحكة." },
      { sv: "Jag ska berätta om min resa.", ar: "سأحكي عن رحلتي." },
    ],
    quizSentences: [
      { form: "presens", sentence: "Han ___ alltid långa historier.", answer: "berättar", translation: "هو دائماً يروي قصصاً طويلة." },
      { form: "preteritum", sentence: "Mamma ___ om sin barndom.", answer: "berättade", translation: "أخبرت الأم عن طفولتها." },
      { form: "imperativ", sentence: "___ mig mer om dig!", answer: "Berätta", translation: "أخبرني المزيد عنك!" },
    ],
  },
  {
    infinitiv: "hoppas",
    presens: "hoppas",
    preteritum: "hoppades",
    supinum: "hoppats",
    imperativ: "hoppas",
    futurum: "ska hoppas",
    presensParticip: "hoppandes",
    perfektParticip: "hoppats",
    passivPresens: null,
    passivPreteritum: null,
    translation: "يأمل / يتمنى",
    phonetic: "/ˈhɔpːas/",
    group: "1",
    level: "A2",
    category: "känsla",
    imageUrl: IMG.nature,
    notes: "فعل مجموعة 1 بصيغة ديبونينس (يصرّف دائماً بـ -s). hoppas att = يأمل أن.",
    examples: [
      { sv: "Jag hoppas att du mår bra.", ar: "أتمنى أن تكون بخير." },
      { sv: "Vi hoppas på bra väder.", ar: "نأمل في طقس جيد." },
      { sv: "Hon hoppades att de skulle komma.", ar: "كانت تأمل أن يأتوا." },
    ],
    quizSentences: [
      { form: "presens", sentence: "Jag ___ att klara provet.", answer: "hoppas", translation: "أتمنى أن أنجح في الامتحان." },
      { form: "preteritum", sentence: "Vi ___ på sol men det regnade.", answer: "hoppades", translation: "أملنا في شمس لكن أمطرت." },
      { form: "presens", sentence: "Hon ___ att allt blir bra.", answer: "hoppas", translation: "تتمنى أن يسير كل شيء على ما يرام." },
    ],
  },
  {
    infinitiv: "träna",
    presens: "tränar",
    preteritum: "tränade",
    supinum: "tränat",
    imperativ: "träna",
    futurum: "ska träna",
    presensParticip: "tränande",
    perfektParticip: "tränad",
    passivPresens: "tränas",
    passivPreteritum: "tränades",
    translation: "يتدرب / يمارس الرياضة",
    phonetic: "/ˈtrɛːna/",
    group: "1",
    level: "A1",
    category: "sport",
    imageUrl: IMG.sport,
    notes: "مجموعة 1. träna på gymmet = يتدرب في الصالة. träna fotboll = يتدرب على كرة القدم.",
    examples: [
      { sv: "Jag tränar tre gånger i veckan.", ar: "أتدرب ثلاث مرات في الأسبوع." },
      { sv: "Hon tränade hårt inför tävlingen.", ar: "تدربت بجد استعداداً للمسابقة." },
      { sv: "Träna mer så blir du starkare!", ar: "تدرب أكثر وستصبح أقوى!" },
    ],
    quizSentences: [
      { form: "presens", sentence: "Han ___ på gymmet varje dag.", answer: "tränar", translation: "هو يتدرب في الصالة كل يوم." },
      { form: "preteritum", sentence: "Vi ___ fotboll igår kväll.", answer: "tränade", translation: "تدربنا على كرة القدم أمس مساءً." },
      { form: "imperativ", sentence: "___ lite varje dag!", answer: "Träna", translation: "تدرب قليلاً كل يوم!" },
    ],
  },
  {
    infinitiv: "öppna",
    presens: "öppnar",
    preteritum: "öppnade",
    supinum: "öppnat",
    imperativ: "öppna",
    futurum: "ska öppna",
    presensParticip: "öppnande",
    perfektParticip: "öppnad",
    passivPresens: "öppnas",
    passivPreteritum: "öppnades",
    translation: "يفتح",
    phonetic: "/ˈœpːna/",
    group: "1",
    level: "A1",
    category: "vardag",
    imageUrl: IMG.city,
    notes: "مجموعة 1. ضد: stänga (يغلق). öppna ett konto = يفتح حساباً.",
    examples: [
      { sv: "Öppna dörren, tack!", ar: "افتح الباب، من فضلك!" },
      { sv: "Affären öppnar klockan nio.", ar: "المحل يفتح الساعة التاسعة." },
      { sv: "Han öppnade ett nytt konto.", ar: "فتح حساباً جديداً." },
    ],
    quizSentences: [
      { form: "presens", sentence: "Banken ___ klockan tio.", answer: "öppnar", translation: "البنك يفتح الساعة العاشرة." },
      { form: "preteritum", sentence: "Hon ___ fönstret för frisk luft.", answer: "öppnade", translation: "فتحت النافذة للهواء النقي." },
      { form: "imperativ", sentence: "___ paketet försiktigt!", answer: "Öppna", translation: "افتح الطرد بعناية!" },
    ],
  },
  {
    infinitiv: "betala",
    presens: "betalar",
    preteritum: "betalade",
    supinum: "betalat",
    imperativ: "betala",
    futurum: "ska betala",
    presensParticip: "betalande",
    perfektParticip: "betalad",
    passivPresens: "betalas",
    passivPreteritum: "betalades",
    translation: "يدفع",
    phonetic: "/bɛˈtɑːla/",
    group: "1",
    level: "A1",
    category: "handel",
    imageUrl: IMG.shopping,
    notes: "مجموعة 1. betala med kort/kontant = يدفع بالبطاقة/نقداً.",
    examples: [
      { sv: "Jag betalar med kort.", ar: "أدفع بالبطاقة." },
      { sv: "Vem betalar notan?", ar: "من يدفع الفاتورة؟" },
      { sv: "Han betalade för alla.", ar: "دفع للجميع." },
    ],
    quizSentences: [
      { form: "presens", sentence: "Jag ___ hyran varje månad.", answer: "betalar", translation: "أدفع الإيجار كل شهر." },
      { form: "preteritum", sentence: "Hon ___ räkningen online.", answer: "betalade", translation: "دفعت الفاتورة عبر الإنترنت." },
      { form: "imperativ", sentence: "___ i kassan, tack!", answer: "Betala", translation: "ادفع عند الصندوق، من فضلك!" },
    ],
  },
  {
    infinitiv: "simma",
    presens: "simmar",
    preteritum: "simmade",
    supinum: "simmat",
    imperativ: "simma",
    futurum: "ska simma",
    presensParticip: "simmande",
    perfektParticip: "simmad",
    passivPresens: null,
    passivPreteritum: null,
    translation: "يسبح",
    phonetic: "/ˈsɪmːa/",
    group: "1",
    level: "A1",
    category: "sport",
    imageUrl: IMG.sport,
    notes: "مجموعة 1. simma i sjön/havet/poolen = يسبح في البحيرة/البحر/حوض السباحة.",
    examples: [
      { sv: "Jag simmar varje morgon.", ar: "أسبح كل صباح." },
      { sv: "Barnen simmade i sjön.", ar: "سبح الأطفال في البحيرة." },
      { sv: "Kan du simma?", ar: "هل تستطيع السباحة؟" },
    ],
    quizSentences: [
      { form: "presens", sentence: "Hon ___ 50 meter varje dag.", answer: "simmar", translation: "تسبح 50 متراً كل يوم." },
      { form: "preteritum", sentence: "Vi ___ i havet förra sommaren.", answer: "simmade", translation: "سبحنا في البحر الصيف الماضي." },
      { form: "imperativ", sentence: "___ inte för långt ut!", answer: "Simma", translation: "لا تسبح بعيداً جداً!" },
    ],
  },
  {
    infinitiv: "cykla",
    presens: "cyklar",
    preteritum: "cyklade",
    supinum: "cyklat",
    imperativ: "cykla",
    futurum: "ska cykla",
    presensParticip: "cyklande",
    perfektParticip: "cyklad",
    passivPresens: null,
    passivPreteritum: null,
    translation: "يركب الدراجة",
    phonetic: "/ˈsʏkla/",
    group: "1",
    level: "A1",
    category: "sport",
    imageUrl: IMG.walk,
    notes: "مجموعة 1. cykla till jobbet = يذهب إلى العمل بالدراجة. شائع جداً في السويد.",
    examples: [
      { sv: "Jag cyklar till jobbet varje dag.", ar: "أذهب إلى العمل بالدراجة كل يوم." },
      { sv: "De cyklade genom parken.", ar: "تجولوا بالدراجة عبر الحديقة." },
      { sv: "Cykla försiktigt i trafiken!", ar: "اركب الدراجة بحذر في حركة المرور!" },
    ],
    quizSentences: [
      { form: "presens", sentence: "Hon ___ tre kilometer till skolan.", answer: "cyklar", translation: "تركب الدراجة ثلاثة كيلومترات إلى المدرسة." },
      { form: "preteritum", sentence: "Vi ___ längs sjön igår.", answer: "cyklade", translation: "تجولنا بالدراجة على طول البحيرة أمس." },
      { form: "imperativ", sentence: "___ hit, det är nära!", answer: "Cykla", translation: "تعال بالدراجة، إنه قريب!" },
    ],
  },
  {
    infinitiv: "starta",
    presens: "startar",
    preteritum: "startade",
    supinum: "startat",
    imperativ: "starta",
    futurum: "ska starta",
    presensParticip: "startande",
    perfektParticip: "startad",
    passivPresens: "startas",
    passivPreteritum: "startades",
    translation: "يبدأ / يشغّل",
    phonetic: "/ˈstɑːrta/",
    group: "1",
    level: "A2",
    category: "teknik",
    imageUrl: IMG.tech,
    notes: "مجموعة 1. starta datorn = يشغّل الحاسوب. starta ett företag = يؤسس شركة.",
    examples: [
      { sv: "Starta datorn!", ar: "شغّل الحاسوب!" },
      { sv: "Han startade ett eget företag.", ar: "أسّس شركته الخاصة." },
      { sv: "Mötet startar klockan tio.", ar: "يبدأ الاجتماع الساعة العاشرة." },
    ],
    quizSentences: [
      { form: "presens", sentence: "Filmen ___ om fem minuter.", answer: "startar", translation: "يبدأ الفيلم بعد خمس دقائق." },
      { form: "preteritum", sentence: "De ___ projektet i januari.", answer: "startade", translation: "بدأوا المشروع في يناير." },
      { form: "imperativ", sentence: "___ om från början!", answer: "Starta", translation: "ابدأ من البداية!" },
    ],
  },
  {
    infinitiv: "spela",
    presens: "spelar",
    preteritum: "spelade",
    supinum: "spelat",
    imperativ: "spela",
    futurum: "ska spela",
    presensParticip: "spelande",
    perfektParticip: "spelad",
    passivPresens: "spelas",
    passivPreteritum: "spelades",
    translation: "يلعب / يعزف",
    phonetic: "/ˈspeːla/",
    group: "1",
    level: "A1",
    category: "sport",
    imageUrl: IMG.sport,
    notes: "مجموعة 1. spela fotboll = يلعب كرة القدم. spela piano = يعزف البيانو.",
    examples: [
      { sv: "Vi spelar fotboll på helgerna.", ar: "نلعب كرة القدم في عطلة الأسبوع." },
      { sv: "Hon spelade piano i tio år.", ar: "عزفت البيانو لعشر سنوات." },
      { sv: "Spela rättvist!", ar: "العب بشكل عادل!" },
    ],
    quizSentences: [
      { form: "presens", sentence: "Han ___ gitarr i ett band.", answer: "spelar", translation: "هو يعزف الجيتار في فرقة." },
      { form: "preteritum", sentence: "Vi ___ kort hela kvällen.", answer: "spelade", translation: "لعبنا الورق طوال المساء." },
      { form: "imperativ", sentence: "___ lite tystare, tack!", answer: "Spela", translation: "العب بصوت أهدأ، من فضلك!" },
    ],
  },
  {
    infinitiv: "planera",
    presens: "planerar",
    preteritum: "planerade",
    supinum: "planerat",
    imperativ: "planera",
    futurum: "ska planera",
    presensParticip: "planerande",
    perfektParticip: "planerad",
    passivPresens: "planeras",
    passivPreteritum: "planerades",
    translation: "يخطط / ينظم",
    phonetic: "/plaˈneːra/",
    group: "1",
    level: "A2",
    category: "arbete",
    imageUrl: IMG.work,
    notes: "مجموعة 1. planera en resa = يخطط لرحلة. planera inför = يستعد لـ.",
    examples: [
      { sv: "Vi planerar en resa till Italien.", ar: "نخطط لرحلة إلى إيطاليا." },
      { sv: "Hon planerade mötet noggrant.", ar: "نظّمت الاجتماع بعناية." },
      { sv: "Planera i förväg!", ar: "خطط مسبقاً!" },
    ],
    quizSentences: [
      { form: "presens", sentence: "Jag ___ att flytta till Malmö.", answer: "planerar", translation: "أخطط للانتقال إلى مالمو." },
      { form: "preteritum", sentence: "De ___ festen länge.", answer: "planerade", translation: "خططوا للحفلة طويلاً." },
      { form: "imperativ", sentence: "___ din vecka i förväg!", answer: "Planera", translation: "خطط لأسبوعك مسبقاً!" },
    ],
  },
  {
    infinitiv: "städa",
    presens: "städar",
    preteritum: "städade",
    supinum: "städat",
    imperativ: "städa",
    futurum: "ska städa",
    presensParticip: "städande",
    perfektParticip: "städad",
    passivPresens: "städas",
    passivPreteritum: "städades",
    translation: "ينظّف / يرتّب",
    phonetic: "/ˈstɛːda/",
    group: "1",
    level: "A1",
    category: "vardag",
    imageUrl: IMG.family,
    notes: "مجموعة 1. städa hemma = ينظّف البيت. städa rummet = يرتّب الغرفة.",
    examples: [
      { sv: "Jag städar varje fredag.", ar: "أنظّف كل جمعة." },
      { sv: "Hon städade hela lägenheten.", ar: "نظّفت الشقة كاملة." },
      { sv: "Städa ditt rum!", ar: "رتّب غرفتك!" },
    ],
    quizSentences: [
      { form: "presens", sentence: "Vi ___ tillsammans på lördagen.", answer: "städar", translation: "ننظّف معاً يوم السبت." },
      { form: "preteritum", sentence: "Han ___ köket efter middagen.", answer: "städade", translation: "نظّف المطبخ بعد العشاء." },
      { form: "imperativ", sentence: "___ innan gästerna kommer!", answer: "Städa", translation: "نظّف قبل أن يصل الضيوف!" },
    ],
  },
  {
    infinitiv: "sluta",
    presens: "slutar",
    preteritum: "slutade",
    supinum: "slutat",
    imperativ: "sluta",
    futurum: "ska sluta",
    presensParticip: "slutande",
    perfektParticip: "slutad",
    passivPresens: "slutas",
    passivPreteritum: "slutades",
    translation: "يتوقف / ينتهي / يترك",
    phonetic: "/ˈslʉːta/",
    group: "1",
    level: "A2",
    category: "vardag",
    imageUrl: IMG.work,
    notes: "مجموعة 1. sluta röka = يتوقف عن التدخين. sluta jobba = ينتهي من العمل. Sluta! = توقف!",
    examples: [
      { sv: "Sluta prata!", ar: "توقف عن الكلام!" },
      { sv: "Han slutade röka förra året.", ar: "توقف عن التدخين العام الماضي." },
      { sv: "Skolan slutar klockan tre.", ar: "تنتهي المدرسة الساعة الثالثة." },
    ],
    quizSentences: [
      { form: "presens", sentence: "Filmen ___ om en timme.", answer: "slutar", translation: "ينتهي الفيلم خلال ساعة." },
      { form: "preteritum", sentence: "Hon ___ sitt arbete vid fem.", answer: "slutade", translation: "أنهت عملها عند الساعة الخامسة." },
      { form: "imperativ", sentence: "___ inte nu, fortsätt!", answer: "Sluta", translation: "لا تتوقف الآن، استمر!" },
    ],
  },
  {
    infinitiv: "börja",
    presens: "börjar",
    preteritum: "började",
    supinum: "börjat",
    imperativ: "börja",
    futurum: "ska börja",
    presensParticip: "börjande",
    perfektParticip: "börjad",
    passivPresens: "börjas",
    passivPreteritum: "börjades",
    translation: "يبدأ",
    phonetic: "/ˈbœrːja/",
    group: "1",
    level: "A1",
    category: "vardag",
    imageUrl: IMG.school,
    notes: "مجموعة 1. börja + infinitiv = يبدأ في. Börja från början = يبدأ من البداية.",
    examples: [
      { sv: "Börja nu!", ar: "ابدأ الآن!" },
      { sv: "Kursen börjar i januari.", ar: "يبدأ الكورس في يناير." },
      { sv: "Jag började lära mig svenska för ett år sedan.", ar: "بدأت تعلم السويدية منذ عام." },
    ],
    quizSentences: [
      { form: "presens", sentence: "Mötet ___ klockan nio.", answer: "börjar", translation: "يبدأ الاجتماع الساعة التاسعة." },
      { form: "preteritum", sentence: "Det ___ regna plötsligt.", answer: "började", translation: "بدأ المطر فجأة." },
      { form: "imperativ", sentence: "___ med det svåraste först!", answer: "Börja", translation: "ابدأ بالأصعب أولاً!" },
    ],
  },
  {
    infinitiv: "hitta",
    presens: "hittar",
    preteritum: "hittade",
    supinum: "hittat",
    imperativ: "hitta",
    futurum: "ska hitta",
    presensParticip: "hittande",
    perfektParticip: "hittad",
    passivPresens: "hittas",
    passivPreteritum: "hittades",
    translation: "يجد / يعثر على",
    phonetic: "/ˈhɪtːa/",
    group: "1",
    level: "A1",
    category: "vardag",
    imageUrl: IMG.city,
    notes: "مجموعة 1. hitta på = يخترع / يبتكر. hitta hem = يجد طريقه إلى البيت.",
    examples: [
      { sv: "Jag kan inte hitta mina nycklar.", ar: "لا أستطيع إيجاد مفاتيحي." },
      { sv: "Vi hittade en bra restaurang.", ar: "وجدنا مطعماً جيداً." },
      { sv: "Hitta på något roligt att göra!", ar: "ابتكر شيئاً ممتعاً للقيام به!" },
    ],
    quizSentences: [
      { form: "presens", sentence: "Jag ___ alltid vägen med GPS.", answer: "hittar", translation: "أجد دائماً الطريق بمساعدة GPS." },
      { form: "preteritum", sentence: "Hon ___ sin katt efter tre dagar.", answer: "hittade", translation: "وجدت قطتها بعد ثلاثة أيام." },
      { form: "imperativ", sentence: "___ ett bättre alternativ!", answer: "Hitta", translation: "اعثر على بديل أفضل!" },
    ],
  },
  {
    infinitiv: "lämna",
    presens: "lämnar",
    preteritum: "lämnade",
    supinum: "lämnat",
    imperativ: "lämna",
    futurum: "ska lämna",
    presensParticip: "lämnande",
    perfektParticip: "lämnad",
    passivPresens: "lämnas",
    passivPreteritum: "lämnades",
    translation: "يترك / يغادر",
    phonetic: "/ˈlɛmːna/",
    group: "1",
    level: "A2",
    category: "rörelse",
    imageUrl: IMG.walk,
    notes: "مجموعة 1. lämna ifrån sig = يسلّم. lämna landet = يغادر البلد. lämna ett meddelande = يترك رسالة.",
    examples: [
      { sv: "Lämna mig ifred!", ar: "اتركني وشأني!" },
      { sv: "Han lämnade huset tidigt.", ar: "غادر المنزل مبكراً." },
      { sv: "Lämna ett meddelande om jag inte svarar.", ar: "اترك رسالة إن لم أرد." },
    ],
    quizSentences: [
      { form: "presens", sentence: "Han ___ kontoret klockan fem.", answer: "lämnar", translation: "هو يغادر المكتب الساعة الخامسة." },
      { form: "preteritum", sentence: "Vi ___ hotellrummet klockan tolv.", answer: "lämnade", translation: "غادرنا غرفة الفندق الساعة الثانية عشرة." },
      { form: "imperativ", sentence: "___ nycklarna i receptionen!", answer: "Lämna", translation: "اترك المفاتيح في الاستقبال!" },
    ],
  },

  // ══════════════════════════════════════════════════════════════════
  // NEW VERBS — GRUPP 2a (-er, -de, -t)
  // ══════════════════════════════════════════════════════════════════
  {
    infinitiv: "lära",
    presens: "lär",
    preteritum: "lärde",
    supinum: "lärt",
    imperativ: "lär",
    futurum: "ska lära",
    presensParticip: "lärande",
    perfektParticip: "lärd",
    passivPresens: "lärs",
    passivPreteritum: "lärdes",
    translation: "يتعلم / يعلّم",
    phonetic: "/lɛːr/",
    group: "2a",
    level: "A2",
    category: "skola",
    imageUrl: IMG.school,
    notes: "مجموعة 2a. lära sig = يتعلم. lära ut = يعلّم. الأمر: lär.",
    examples: [
      { sv: "Jag lär mig svenska.", ar: "أنا أتعلم السويدية." },
      { sv: "Hon lärde sig cykla som barn.", ar: "تعلمت ركوب الدراجة وهي طفلة." },
      { sv: "Han lär ut matematik.", ar: "هو يدرّس الرياضيات." },
    ],
    quizSentences: [
      { form: "presens", sentence: "Jag ___ mig ett nytt ord varje dag.", answer: "lär", translation: "أتعلم كلمة جديدة كل يوم." },
      { form: "preteritum", sentence: "Vi ___ oss sången utantill.", answer: "lärde", translation: "حفظنا الأغنية عن ظهر قلب." },
      { form: "imperativ", sentence: "___ dig köra bil!", answer: "Lär", translation: "تعلّم قيادة السيارة!" },
    ],
  },
  {
    infinitiv: "använda",
    presens: "använder",
    preteritum: "använde",
    supinum: "använt",
    imperativ: "använd",
    futurum: "ska använda",
    presensParticip: "användande",
    perfektParticip: "använd",
    passivPresens: "används",
    passivPreteritum: "användes",
    translation: "يستخدم / يستعمل",
    phonetic: "/anˈvɛnːda/",
    group: "2a",
    level: "A2",
    category: "teknik",
    imageUrl: IMG.tech,
    notes: "مجموعة 2a. använda sig av = يستعين بـ. شائع جداً في السياق التقني.",
    examples: [
      { sv: "Jag använder telefonen hela dagen.", ar: "أستخدم الهاتف طوال اليوم." },
      { sv: "Hur använder man det här programmet?", ar: "كيف يستخدم هذا البرنامج؟" },
      { sv: "De använde en ny metod.", ar: "استخدموا طريقة جديدة." },
    ],
    quizSentences: [
      { form: "presens", sentence: "Han ___ datorn för att jobba.", answer: "använder", translation: "هو يستخدم الحاسوب للعمل." },
      { form: "preteritum", sentence: "Vi ___ GPS under resan.", answer: "använde", translation: "استخدمنا GPS خلال الرحلة." },
      { form: "imperativ", sentence: "___ inte mobilen under lektionen!", answer: "Använd", translation: "لا تستخدم الهاتف أثناء الدرس!" },
    ],
  },
  {
    infinitiv: "följa",
    presens: "följer",
    preteritum: "följde",
    supinum: "följt",
    imperativ: "följ",
    futurum: "ska följa",
    presensParticip: "följande",
    perfektParticip: "följd",
    passivPresens: "följs",
    passivPreteritum: "följdes",
    translation: "يتبع / يرافق",
    phonetic: "/ˈfœlːja/",
    group: "2a",
    level: "A2",
    category: "rörelse",
    imageUrl: IMG.walk,
    notes: "مجموعة 2a. följa med = يرافق / يأتي معاً. följa regler = يتّبع القواعد.",
    examples: [
      { sv: "Följ mig!", ar: "تبعني! / تعال معي!" },
      { sv: "Jag följde med henne hem.", ar: "رافقتها إلى المنزل." },
      { sv: "Det är viktigt att följa reglerna.", ar: "من المهم اتّباع القواعد." },
    ],
    quizSentences: [
      { form: "presens", sentence: "Han ___ alltid med sin hund.", answer: "följer", translation: "هو دائماً يأخذ كلبه معه." },
      { form: "preteritum", sentence: "Vi ___ guiden genom staden.", answer: "följde", translation: "اتّبعنا المرشد عبر المدينة." },
      { form: "imperativ", sentence: "___ inte mig, gå din egen väg!", answer: "Följ", translation: "لا تتبعني، امشِ في طريقك الخاص!" },
    ],
  },
  {
    infinitiv: "tänka",
    presens: "tänker",
    preteritum: "tänkte",
    supinum: "tänkt",
    imperativ: "tänk",
    futurum: "ska tänka",
    presensParticip: "tänkande",
    perfektParticip: "tänkt",
    passivPresens: "tänks",
    passivPreteritum: "tänktes",
    translation: "يفكّر / يعتزم",
    phonetic: "/ˈtɛŋːka/",
    group: "2b",
    level: "A2",
    category: "tanke",
    imageUrl: IMG.school,
    notes: "مجموعة 2b. tänka på = يفكر في. tänka på att = ينوي. Tänk efter! = فكّر مليّاً!",
    examples: [
      { sv: "Jag tänker på dig.", ar: "أنا أفكّر فيك." },
      { sv: "Tänk innan du pratar!", ar: "فكّر قبل أن تتكلم!" },
      { sv: "Han tänkte länge på svaret.", ar: "فكّر طويلاً في الإجابة." },
    ],
    quizSentences: [
      { form: "presens", sentence: "Vad ___ du om det?", answer: "tänker", translation: "ما رأيك في ذلك؟" },
      { form: "preteritum", sentence: "Jag ___ att gå hem tidigt.", answer: "tänkte", translation: "كنت أنوي الذهاب إلى المنزل مبكراً." },
      { form: "imperativ", sentence: "___ noga innan du bestämmer dig!", answer: "Tänk", translation: "فكّر جيداً قبل أن تقرر!" },
    ],
  },
  {
    infinitiv: "märka",
    presens: "märker",
    preteritum: "märkte",
    supinum: "märkt",
    imperativ: "märk",
    futurum: "ska märka",
    presensParticip: "märkande",
    perfektParticip: "märkt",
    passivPresens: "märks",
    passivPreteritum: "märktes",
    translation: "يلاحظ / يدرك",
    phonetic: "/ˈmɛrːka/",
    group: "2b",
    level: "B1",
    category: "sinnen",
    imageUrl: IMG.school,
    notes: "مجموعة 2b. märka att = يلاحظ أن. det märks = يبدو واضحاً.",
    examples: [
      { sv: "Jag märker att du är trött.", ar: "ألاحظ أنك متعب." },
      { sv: "Hon märkte inte att han gick.", ar: "لم تلاحظ أنه غادر." },
      { sv: "Det märks att du har övat!", ar: "يبدو واضحاً أنك تدرّبت!" },
    ],
    quizSentences: [
      { form: "presens", sentence: "Jag ___ en förändring i hans beteende.", answer: "märker", translation: "ألاحظ تغيّراً في سلوكه." },
      { form: "preteritum", sentence: "Vi ___ ingenting konstigt.", answer: "märkte", translation: "لم نلاحظ شيئاً غريباً." },
      { form: "presens", sentence: "Det ___ att hon är glad.", answer: "märks", translation: "يبدو واضحاً أنها سعيدة." },
    ],
  },
  {
    infinitiv: "känna",
    presens: "känner",
    preteritum: "kände",
    supinum: "känt",
    imperativ: "känn",
    futurum: "ska känna",
    presensParticip: "kännande",
    perfektParticip: "känd",
    passivPresens: "känns",
    passivPreteritum: "kändes",
    translation: "يعرف (شخصاً) / يشعر",
    phonetic: "/ˈɕɛnːa/",
    group: "2a",
    level: "A1",
    category: "känsla",
    imageUrl: IMG.family,
    notes: "مجموعة 2a. känna någon = يعرف شخصاً. känna sig = يشعر بـ. Det känns bra = يبدو جيداً.",
    examples: [
      { sv: "Känner du honom?", ar: "هل تعرفه؟" },
      { sv: "Jag känner mig trött.", ar: "أشعر بالتعب." },
      { sv: "Det kändes kallt.", ar: "شعرت بالبرد." },
    ],
    quizSentences: [
      { form: "presens", sentence: "Jag ___ inte din syster.", answer: "känner", translation: "لا أعرف أختك." },
      { form: "preteritum", sentence: "Han ___ sig ensam.", answer: "kände", translation: "شعر بالوحدة." },
      { form: "presens", sentence: "Det ___ bra att vara hemma.", answer: "känns", translation: "يشعر بالراحة أن يكون في البيت." },
    ],
  },
  {
    infinitiv: "bestämma",
    presens: "bestämmer",
    preteritum: "bestämde",
    supinum: "bestämt",
    imperativ: "bestäm",
    futurum: "ska bestämma",
    presensParticip: "bestämmande",
    perfektParticip: "bestämd",
    passivPresens: "bestäms",
    passivPreteritum: "bestämdes",
    translation: "يقرر / يحدّد",
    phonetic: "/bɛˈstɛmːa/",
    group: "2a",
    level: "B1",
    category: "arbete",
    imageUrl: IMG.work,
    notes: "مجموعة 2a. bestämma sig = يتّخذ قراراً. bestämma tid = يحدّد موعداً.",
    examples: [
      { sv: "Jag kan inte bestämma mig.", ar: "لا أستطيع أن أقرر." },
      { sv: "Chefen bestämde att mötet ställdes in.", ar: "قرّر المدير إلغاء الاجتماع." },
      { sv: "Bestäm dig nu!", ar: "اتّخذ قراراً الآن!" },
    ],
    quizSentences: [
      { form: "presens", sentence: "Vem ___ här?", answer: "bestämmer", translation: "من يقرر هنا؟" },
      { form: "preteritum", sentence: "Vi ___ oss för att stanna.", answer: "bestämde", translation: "قرّرنا البقاء." },
      { form: "imperativ", sentence: "___ dig innan imorgon!", answer: "Bestäm", translation: "اتّخذ قرارك قبل الغد!" },
    ],
  },

  // ══════════════════════════════════════════════════════════════════
  // NEW VERBS — GRUPP 3 (short verbs: -r, -dde, -tt)
  // ══════════════════════════════════════════════════════════════════
  {
    infinitiv: "sy",
    presens: "syr",
    preteritum: "sydde",
    supinum: "sytt",
    imperativ: "sy",
    futurum: "ska sy",
    presensParticip: "syende",
    perfektParticip: "sytt",
    passivPresens: "sys",
    passivPreteritum: "syddes",
    translation: "يخيط",
    phonetic: "/syː/",
    group: "3",
    level: "B1",
    category: "vardag",
    imageUrl: IMG.family,
    notes: "مجموعة 3. sy kläder = يخيط الملابس. sy ihop = يخيط معاً.",
    examples: [
      { sv: "Mormor syr kläder åt oss.", ar: "الجدّة تخيط لنا الملابس." },
      { sv: "Hon sydde sin bröllopsklänning själv.", ar: "خاطت فستان زفافها بنفسها." },
      { sv: "Kan du sy fast knappen?", ar: "هل يمكنك خياطة الزر؟" },
    ],
    quizSentences: [
      { form: "presens", sentence: "Hon ___ en ny kjol.", answer: "syr", translation: "هي تخيط تنورة جديدة." },
      { form: "preteritum", sentence: "Han ___ ihop såret.", answer: "sydde", translation: "خاط الجرح." },
      { form: "imperativ", sentence: "___ fast knappen på jackan!", answer: "Sy", translation: "اخِط الزر على الجاكيت!" },
    ],
  },
  {
    infinitiv: "nå",
    presens: "når",
    preteritum: "nådde",
    supinum: "nått",
    imperativ: "nå",
    futurum: "ska nå",
    presensParticip: "nående",
    perfektParticip: "nådd",
    passivPresens: "nås",
    passivPreteritum: "nåddes",
    translation: "يصل إلى / يتواصل مع",
    phonetic: "/nɔː/",
    group: "3",
    level: "B1",
    category: "kommunikation",
    imageUrl: IMG.speak,
    notes: "مجموعة 3. nå fram = يصل إلى الهدف. nå någon = يتواصل مع شخص ما.",
    examples: [
      { sv: "Jag kan inte nå honom på telefon.", ar: "لا أستطيع الوصول إليه بالهاتف." },
      { sv: "Vi nådde målet i tid.", ar: "وصلنا إلى الهدف في الوقت المحدد." },
      { sv: "Nå gärna ut till oss om du har frågor.", ar: "تواصل معنا إذا كانت لديك أسئلة." },
    ],
    quizSentences: [
      { form: "presens", sentence: "Brevet ___ dig imorgon.", answer: "når", translation: "ستصلك الرسالة غداً." },
      { form: "preteritum", sentence: "Vi ___ toppen av berget.", answer: "nådde", translation: "وصلنا إلى قمة الجبل." },
      { form: "futurum", sentence: "Jag ___ dig via mejl.", answer: "ska nå", translation: "سأتواصل معك عبر البريد الإلكتروني." },
    ],
  },

  // ══════════════════════════════════════════════════════════════════
  // NEW VERBS — OREGELBUNDET (Irregular / Strong)
  // ══════════════════════════════════════════════════════════════════
  {
    infinitiv: "springa",
    presens: "springer",
    preteritum: "sprang",
    supinum: "sprungit",
    imperativ: "spring",
    futurum: "ska springa",
    presensParticip: "springande",
    perfektParticip: "sprungen",
    passivPresens: null,
    passivPreteritum: null,
    translation: "يركض / يجري",
    phonetic: "/ˈsprɪŋːa/",
    group: "oregelbundet",
    level: "A1",
    category: "sport",
    imageUrl: IMG.sport,
    notes: "فعل قوي غير منتظم. الماضي: sprang. springa maraton = يجري ماراثون.",
    examples: [
      { sv: "Jag springer fem kilometer om dagen.", ar: "أركض خمسة كيلومترات يومياً." },
      { sv: "Han sprang ifrån dem.", ar: "ركض بعيداً عنهم." },
      { sv: "Spring fort, bussen går!", ar: "اركض بسرعة، الحافلة ستذهب!" },
    ],
    quizSentences: [
      { form: "presens", sentence: "Hon ___ varje morgon.", answer: "springer", translation: "هي تركض كل صباح." },
      { form: "preteritum", sentence: "Vi ___ i parken igår.", answer: "sprang", translation: "ركضنا في الحديقة أمس." },
      { form: "imperativ", sentence: "___ inte på hala underlag!", answer: "Spring", translation: "لا تركض على الأرض الزلقة!" },
    ],
  },
  {
    infinitiv: "sjunga",
    presens: "sjunger",
    preteritum: "sjöng",
    supinum: "sjungit",
    imperativ: "sjung",
    futurum: "ska sjunga",
    presensParticip: "sjungande",
    perfektParticip: "sjungen",
    passivPresens: "sjungs",
    passivPreteritum: "sjöngs",
    translation: "يغني",
    phonetic: "/ˈɧɵŋːa/",
    group: "oregelbundet",
    level: "A2",
    category: "social",
    imageUrl: IMG.family,
    notes: "فعل قوي. الماضي: sjöng. sjunga i kör = يغني في جوقة.",
    examples: [
      { sv: "Hon sjunger vackert.", ar: "هي تغني بشكل جميل." },
      { sv: "Vi sjöng julsånger.", ar: "غنّينا أغاني عيد الميلاد." },
      { sv: "Sjung med oss!", ar: "غنّي معنا!" },
    ],
    quizSentences: [
      { form: "presens", sentence: "Han ___ i ett band.", answer: "sjunger", translation: "هو يغني في فرقة موسيقية." },
      { form: "preteritum", sentence: "Barnen ___ på konserten.", answer: "sjöng", translation: "غنّى الأطفال في الحفلة الموسيقية." },
      { form: "imperativ", sentence: "___ lite högre, vi hör inte!", answer: "Sjung", translation: "غنّ بصوت أعلى، لا نسمعك!" },
    ],
  },
  {
    infinitiv: "byta",
    presens: "byter",
    preteritum: "bytte",
    supinum: "bytt",
    imperativ: "byt",
    futurum: "ska byta",
    presensParticip: "bytande",
    perfektParticip: "bytt",
    passivPresens: "byts",
    passivPreteritum: "byttes",
    translation: "يبدّل / يستبدل",
    phonetic: "/ˈbyːta/",
    group: "2b",
    level: "A2",
    category: "vardag",
    imageUrl: IMG.shopping,
    notes: "مجموعة 2b. byta kläder = يغيّر ملابسه. byta jobb = يغيّر وظيفته. بالماضي: bytte.",
    examples: [
      { sv: "Jag vill byta den här jackan.", ar: "أريد استبدال هذا الجاكيت." },
      { sv: "Han bytte jobb förra månaden.", ar: "غيّر وظيفته الشهر الماضي." },
      { sv: "Byt till ett bättre däck!", ar: "استبدل إطارات أفضل!" },
    ],
    quizSentences: [
      { form: "presens", sentence: "Jag ___ busslinje vid Centralen.", answer: "byter", translation: "أغيّر خط الحافلة عند المحطة المركزية." },
      { form: "preteritum", sentence: "Hon ___ lösenord på datorn.", answer: "bytte", translation: "غيّرت كلمة مرور الحاسوب." },
      { form: "imperativ", sentence: "___ till vinterdäck nu!", answer: "Byt", translation: "استبدل إطارات الشتاء الآن!" },
    ],
  },
  {
    infinitiv: "flyga",
    presens: "flyger",
    preteritum: "flög",
    supinum: "flugit",
    imperativ: "flyg",
    futurum: "ska flyga",
    presensParticip: "flygande",
    perfektParticip: "flugen",
    passivPresens: "flygs",
    passivPreteritum: "flögs",
    translation: "يطير",
    phonetic: "/ˈflyːɡa/",
    group: "oregelbundet",
    level: "A2",
    category: "resor",
    imageUrl: IMG.travel,
    notes: "فعل قوي. الماضي: flög. flyga med SAS = يسافر بالطائرة مع SAS.",
    examples: [
      { sv: "Vi flyger till London på fredag.", ar: "نطير إلى لندن يوم الجمعة." },
      { sv: "Fågeln flög bort.", ar: "طار الطائر بعيداً." },
      { sv: "Jag flyger helst direkt.", ar: "أفضّل أن أسافر مباشرة." },
    ],
    quizSentences: [
      { form: "presens", sentence: "Planet ___ på hög höjd.", answer: "flyger", translation: "الطائرة تطير على ارتفاع كبير." },
      { form: "preteritum", sentence: "De ___ till New York igår.", answer: "flög", translation: "طاروا إلى نيويورك أمس." },
      { form: "imperativ", sentence: "___ inte med för tungt bagage!", answer: "Flyg", translation: "لا تسافر بأمتعة ثقيلة جداً!" },
    ],
  },
  {
    infinitiv: "välja",
    presens: "väljer",
    preteritum: "valde",
    supinum: "valt",
    imperativ: "välj",
    futurum: "ska välja",
    presensParticip: "väljande",
    perfektParticip: "vald",
    passivPresens: "väljs",
    passivPreteritum: "valdes",
    translation: "يختار",
    phonetic: "/ˈvɛlːja/",
    group: "oregelbundet",
    level: "A2",
    category: "tanke",
    imageUrl: IMG.school,
    notes: "فعل قوي. الماضي: valde. välja mellan = يختار بين. bli vald = يُنتخب.",
    examples: [
      { sv: "Välj vad du vill ha!", ar: "اختر ما تريد!" },
      { sv: "Jag valde den blå jackan.", ar: "اخترت الجاكيت الأزرق." },
      { sv: "Det är svårt att välja.", ar: "من الصعب الاختيار." },
    ],
    quizSentences: [
      { form: "presens", sentence: "Vad ___ du — kaffe eller te?", answer: "väljer", translation: "ماذا تختار — قهوة أم شاي؟" },
      { form: "preteritum", sentence: "De ___ en ny ledare.", answer: "valde", translation: "اختاروا قائداً جديداً." },
      { form: "imperativ", sentence: "___ med omsorg!", answer: "Välj", translation: "اختر بعناية!" },
    ],
  },
  {
    infinitiv: "bära",
    presens: "bär",
    preteritum: "bar",
    supinum: "burit",
    imperativ: "bär",
    futurum: "ska bära",
    presensParticip: "bärande",
    perfektParticip: "buren",
    passivPresens: "bärs",
    passivPreteritum: "bars",
    translation: "يحمل",
    phonetic: "/bɛːr/",
    group: "oregelbundet",
    level: "A2",
    category: "rörelse",
    imageUrl: IMG.walk,
    notes: "فعل قوي. الماضي: bar. bära på något = يحمل شيئاً. bära ansvar = يتحمل المسؤولية.",
    examples: [
      { sv: "Kan du bära den här påsen?", ar: "هل يمكنك حمل هذه الحقيبة؟" },
      { sv: "Hon bar alla kassar själv.", ar: "حملت جميع الأكياس بنفسها." },
      { sv: "Han bär på ett tungt lass.", ar: "يحمل حملاً ثقيلاً." },
    ],
    quizSentences: [
      { form: "presens", sentence: "Jag ___ alltid ryggsäck till skolan.", answer: "bär", translation: "أحمل دائماً حقيبة ظهر إلى المدرسة." },
      { form: "preteritum", sentence: "De ___ lådorna till bilen.", answer: "bar", translation: "حملوا الصناديق إلى السيارة." },
      { form: "imperativ", sentence: "___ väskan för mormor!", answer: "Bär", translation: "احمل الحقيبة للجدة!" },
    ],
  },
  {
    infinitiv: "heta",
    presens: "heter",
    preteritum: "hette",
    supinum: "hetat",
    imperativ: "het",
    futurum: "ska heta",
    presensParticip: "hetande",
    perfektParticip: "hetat",
    passivPresens: null,
    passivPreteritum: null,
    translation: "يسمّى / اسمه",
    phonetic: "/ˈheːta/",
    group: "oregelbundet",
    level: "A1",
    category: "kommunikation",
    imageUrl: IMG.speak,
    notes: "فعل جامد — لا يستخدم في صيغة المجهول. Jag heter = اسمي. Vad heter du? = ما اسمك؟",
    examples: [
      { sv: "Jag heter Anna.", ar: "اسمي آنا." },
      { sv: "Vad heter du?", ar: "ما اسمك؟" },
      { sv: "Staden hette förr Kristianopel.", ar: "كانت المدينة تسمّى سابقاً كريستيانوبل." },
    ],
    quizSentences: [
      { form: "presens", sentence: "Vad ___ din lärare?", answer: "heter", translation: "ما اسم معلمك؟" },
      { form: "preteritum", sentence: "Hunden ___ Max.", answer: "hette", translation: "كان اسم الكلب ماكس." },
      { form: "presens", sentence: "Jag ___ Erik.", answer: "heter", translation: "اسمي إيريك." },
    ],
  },
  {
    infinitiv: "säga",
    presens: "säger",
    preteritum: "sa",
    supinum: "sagt",
    imperativ: "säg",
    futurum: "ska säga",
    presensParticip: "sägande",
    perfektParticip: "sagd",
    passivPresens: "sägs",
    passivPreteritum: "sades",
    translation: "يقول",
    phonetic: "/ˈsɛːja/",
    group: "oregelbundet",
    level: "A1",
    category: "kommunikation",
    imageUrl: IMG.speak,
    notes: "غير منتظم. الماضي: sa (أو sade). säga till = يخبر. Som sagt = كما قيل.",
    examples: [
      { sv: "Vad sa du?", ar: "ماذا قلت؟" },
      { sv: "Säg sanningen!", ar: "قل الحقيقة!" },
      { sv: "Hon säger alltid hej.", ar: "هي دائماً تقول مرحباً." },
    ],
    quizSentences: [
      { form: "presens", sentence: "Han ___ att han är sjuk.", answer: "säger", translation: "يقول إنه مريض." },
      { form: "preteritum", sentence: "Läraren ___ att vi hade gjort bra ifrån oss.", answer: "sa", translation: "قال المعلم إننا أحسنّا." },
      { form: "imperativ", sentence: "___ hej till din mamma!", answer: "Säg", translation: "قل مرحباً لأمك!" },
    ],
  },
  {
    infinitiv: "möta",
    presens: "möter",
    preteritum: "mötte",
    supinum: "mött",
    imperativ: "möt",
    futurum: "ska möta",
    presensParticip: "mötande",
    perfektParticip: "mött",
    passivPresens: "möts",
    passivPreteritum: "möttes",
    translation: "يلتقي / يقابل",
    phonetic: "/ˈmøːta/",
    group: "2b",
    level: "A2",
    category: "social",
    imageUrl: IMG.family,
    notes: "مجموعة 2b. möta upp = يلتقي بشخص. Vi möts = نلتقي. möta utmaningar = يواجه تحديات.",
    examples: [
      { sv: "Jag möter dig vid stationen.", ar: "سألتقي بك عند المحطة." },
      { sv: "De möttes av en trevlig personal.", ar: "استقبلهم موظفون لطيفون." },
      { sv: "Möt mig utanför bion!", ar: "قابلني خارج السينما!" },
    ],
    quizSentences: [
      { form: "presens", sentence: "Vi ___ varandra varje fredag.", answer: "möter", translation: "نلتقي ببعضنا كل جمعة." },
      { form: "preteritum", sentence: "Jag ___ en gammal vän på gatan.", answer: "mötte", translation: "قابلت صديقاً قديماً في الشارع." },
      { form: "imperativ", sentence: "___ oss utanför teatern!", answer: "Möt", translation: "قابلنا أمام المسرح!" },
    ],
  },
  {
    infinitiv: "resa",
    presens: "reser",
    preteritum: "reste",
    supinum: "rest",
    imperativ: "res",
    futurum: "ska resa",
    presensParticip: "resande",
    perfektParticip: "rest",
    passivPresens: "reses",
    passivPreteritum: "restes",
    translation: "يسافر",
    phonetic: "/ˈreːsa/",
    group: "2b",
    level: "A2",
    category: "resor",
    imageUrl: IMG.travel,
    notes: "مجموعة 2b. resa till = يسافر إلى. الأمر: res. الماضي: reste.",
    examples: [
      { sv: "Vi reser till Stockholm imorgon.", ar: "نسافر إلى ستوكهولم غداً." },
      { sv: "Hon reste ensam genom Europa.", ar: "سافرت وحدها عبر أوروبا." },
      { sv: "Res lätt — ta inte för mycket bagage!", ar: "سافر خفيفاً — لا تأخذ أمتعة كثيرة!" },
    ],
    quizSentences: [
      { form: "presens", sentence: "De ___ till Thailand varje vinter.", answer: "reser", translation: "يسافرون إلى تايلاند كل شتاء." },
      { form: "preteritum", sentence: "Jag ___ till Paris förra sommaren.", answer: "reste", translation: "سافرت إلى باريس الصيف الماضي." },
      { form: "imperativ", sentence: "___ säkert och ha det bra!", answer: "Res", translation: "سافر بأمان واستمتع!" },
    ],
  },
  {
    infinitiv: "hjälpa",
    presens: "hjälper",
    preteritum: "hjälpte",
    supinum: "hjälpt",
    imperativ: "hjälp",
    futurum: "ska hjälpa",
    presensParticip: "hjälpande",
    perfektParticip: "hjälpt",
    passivPresens: "hjälps",
    passivPreteritum: "hjälptes",
    translation: "يساعد",
    phonetic: "/ˈjɛlːpa/",
    group: "2b",
    level: "A1",
    category: "social",
    imageUrl: IMG.family,
    notes: "مجموعة 2b. hjälpa till = يساعد في. Kan du hjälpa mig? = هل يمكنك مساعدتي؟",
    examples: [
      { sv: "Kan du hjälpa mig med det här?", ar: "هل يمكنك مساعدتي في هذا؟" },
      { sv: "Hon hjälpte sin mamma med disken.", ar: "ساعدت أمها في غسيل الأطباق." },
      { sv: "Vi hjälps åt.", ar: "نساعد بعضنا البعض." },
    ],
    quizSentences: [
      { form: "presens", sentence: "Han ___ alltid sina vänner.", answer: "hjälper", translation: "هو دائماً يساعد أصدقاءه." },
      { form: "preteritum", sentence: "Läraren ___ oss med uppgiften.", answer: "hjälpte", translation: "ساعدنا المعلم في المهمة." },
      { form: "imperativ", sentence: "___ mig lyfta det här!", answer: "Hjälp", translation: "ساعدني في رفع هذا!" },
    ],
  },
];

// Fix duplicate infinitiv (stänga added twice, replace with läsa)
const uniqueVerbs = verbs.filter((v, i, arr) =>
  arr.findIndex(x => x.infinitiv === v.infinitiv) === i
);

async function seed() {
  console.log("🌱 Seeding verbs...");
  await db.delete(verbsTable);
  console.log("🗑️  Cleared existing verbs");

  for (let i = 0; i < uniqueVerbs.length; i++) {
    const v = uniqueVerbs[i];
    await db.insert(verbsTable).values({
      infinitiv: v.infinitiv,
      presens: v.presens,
      preteritum: v.preteritum,
      supinum: v.supinum,
      imperativ: v.imperativ,
      futurum: v.futurum,
      presensParticip: v.presensParticip,
      perfektParticip: v.perfektParticip,
      passivPresens: v.passivPresens ?? null,
      passivPreteritum: v.passivPreteritum ?? null,
      translation: v.translation,
      phonetic: v.phonetic,
      group: v.group,
      level: v.level,
      category: v.category,
      imageUrl: v.imageUrl ?? null,
      notes: v.notes ?? null,
      examples: v.examples,
      quizSentences: v.quizSentences,
    });
    console.log(`✅ [${i + 1}/${uniqueVerbs.length}] ${v.infinitiv} — ${v.translation}`);
  }

  console.log(`\n🎉 Seeded ${uniqueVerbs.length} verbs!`);
  process.exit(0);
}

seed().catch((e) => { console.error(e); process.exit(1); });
