import { Router, type IRouter } from "express";
import healthRouter from "./health";
import userProgressRouter from "./userProgress";
import lessonsRouter from "./lessons";
import lessonDetailRouter from "./lessonDetail";
import wordsRouter from "./words";
import statsRouter from "./stats";
import challengesRouter from "./challenges";
import conversationsRouter from "./conversations";
import chatRouter from "./chat";
import dictionaryRouter from "./dictionary";
import verbsRouter from "./verbs";
import aiTeacherRouter from "./aiTeacher";
import pronunciationRouter from "./pronunciation";
import examsRouter from "./exams";
import translateRouter from "./translate";
import statisticsRouter from "./statistics";
import achievementsRouter from "./achievements";
import communityRouter from "./community";
import adminRouter from "./admin";
import adminAuthRouter from "./adminAuth";
import adminKeysRouter from "./adminKeys";
import userSettingsRouter from "./userSettings";

const router: IRouter = Router();

router.use(healthRouter);
router.use(userProgressRouter);
router.use(lessonDetailRouter);
router.use(lessonsRouter);
router.use(wordsRouter);
router.use(statsRouter);
router.use(challengesRouter);
router.use(conversationsRouter);
router.use(chatRouter);
router.use(dictionaryRouter);
router.use(verbsRouter);
router.use(aiTeacherRouter);
router.use(pronunciationRouter);
router.use(examsRouter);
router.use(translateRouter);
router.use(statisticsRouter);
router.use(achievementsRouter);
router.use(communityRouter);
router.use(adminRouter);
router.use(adminAuthRouter);
router.use(adminKeysRouter);
router.use(userSettingsRouter);

export default router;
